import { FrameworkControlTemplate } from './soc2Controls';

/**
 * EU Data Act - Regulation (EU) 2023/2854
 * Fair access to and use of data
 */
export const DATA_ACT_CONTROLS: FrameworkControlTemplate[] = [
  // ===== Chapter II: Data Sharing (B2C and B2B) =====
  {
    controlId: 'DA-1.1',
    name: 'User Data Access Rights',
    description: 'Users of connected products and related services must have access to data generated by their use. Data holders must make data easily accessible, free of charge, and in comprehensive and machine-readable format.',
    category: 'Data Sharing',
    implementationGuidance: 'Implement data access mechanisms for product users. Design data export in machine-readable formats. Ensure access is free of charge. Provide real-time or near-real-time access where feasible.',
    evidenceRequirements: [
      'Data access mechanism documentation',
      'Machine-readable format specifications',
      'Pricing policy (free access verification)',
      'Access latency measurements'
    ],
    testProcedures: [
      'Test data access mechanism functionality',
      'Verify machine-readable format compliance',
      'Confirm free access implementation',
      'Measure access latency performance'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-1.2',
    name: 'Data Sharing with Third Parties',
    description: 'At user request, data holders must share data with third parties designated by the user. Sharing must be under fair, reasonable, and non-discriminatory (FRAND) terms.',
    category: 'Data Sharing',
    implementationGuidance: 'Implement third-party data sharing upon user request. Define FRAND terms for data sharing. Create secure data transfer mechanisms. Document sharing agreements.',
    evidenceRequirements: [
      'Third-party sharing procedures',
      'FRAND terms documentation',
      'Secure transfer mechanism documentation',
      'Sharing agreement records'
    ],
    testProcedures: [
      'Test third-party sharing process',
      'Review FRAND terms compliance',
      'Verify transfer security',
      'Assess agreement documentation'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-1.3',
    name: 'Pre-Contractual Information',
    description: 'Before purchase or contract, users must receive clear information about data generated by connected products, including what data, how to access it, and any third-party sharing.',
    category: 'Data Sharing',
    implementationGuidance: 'Develop pre-contractual data information materials. Include in product documentation and sales materials. Ensure information clarity and accessibility. Update when products change.',
    evidenceRequirements: [
      'Pre-contractual information materials',
      'Product documentation including data information',
      'Sales material compliance verification',
      'Update process documentation'
    ],
    testProcedures: [
      'Review information completeness',
      'Verify documentation inclusion',
      'Assess information clarity',
      'Test update process effectiveness'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-1.4',
    name: 'Technical Access Design',
    description: 'Connected products must be designed to allow users easy, secure, and direct access to data by default. Products should enable data sharing with third parties through secure means.',
    category: 'Data Sharing',
    implementationGuidance: 'Design products with built-in data access features. Implement secure data access interfaces. Enable third-party connectivity by design. Document access capabilities in specifications.',
    evidenceRequirements: [
      'Product design specifications for data access',
      'Secure interface implementation documentation',
      'Third-party connectivity documentation',
      'Capability documentation'
    ],
    testProcedures: [
      'Test built-in data access functionality',
      'Verify interface security',
      'Test third-party connectivity',
      'Review capability documentation accuracy'
    ],
    status: 'Not Started'
  },

  // ===== Chapter III: Unfair Contract Terms =====
  {
    controlId: 'DA-2.1',
    name: 'Fair Data Sharing Contracts',
    description: 'Contract terms for data sharing must not be unfair. Unfair terms are not binding. Assessment considers circumstances, other terms, and nature of data.',
    category: 'Contract Fairness',
    implementationGuidance: 'Review data sharing contracts for fairness. Identify potentially unfair terms. Revise contracts to ensure compliance. Document fairness assessment.',
    evidenceRequirements: [
      'Contract fairness review procedures',
      'Unfair term identification records',
      'Contract revision documentation',
      'Fairness assessment records'
    ],
    testProcedures: [
      'Review fairness assessment process',
      'Verify term identification accuracy',
      'Assess revision adequacy',
      'Test documentation completeness'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-2.2',
    name: 'SME Protection',
    description: 'SMEs receiving data must be protected from unfair contract terms imposed by larger enterprises. Unilaterally imposed terms are subject to fairness assessment.',
    category: 'Contract Fairness',
    implementationGuidance: 'Identify SME counterparties in data sharing. Apply enhanced fairness review for SME contracts. Avoid unilateral imposition of terms. Document SME-specific considerations.',
    evidenceRequirements: [
      'SME identification procedures',
      'Enhanced fairness review documentation',
      'Term negotiation records',
      'SME consideration documentation'
    ],
    testProcedures: [
      'Test SME identification accuracy',
      'Review enhanced review effectiveness',
      'Verify negotiation practices',
      'Assess documentation adequacy'
    ],
    status: 'Not Started'
  },

  // ===== Chapter IV: Data Holder Obligations =====
  {
    controlId: 'DA-3.1',
    name: 'Data Holder Compensation',
    description: 'Data holders may request reasonable compensation for making data available to businesses. Compensation must be transparent, non-discriminatory, and objectively justified.',
    category: 'Data Holder Obligations',
    implementationGuidance: 'Develop transparent compensation methodology. Ensure non-discriminatory pricing. Document cost basis for compensation. Publish compensation terms.',
    evidenceRequirements: [
      'Compensation methodology documentation',
      'Non-discrimination verification',
      'Cost basis documentation',
      'Published compensation terms'
    ],
    testProcedures: [
      'Review methodology transparency',
      'Verify non-discrimination compliance',
      'Test cost basis justification',
      'Assess terms publication compliance'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-3.2',
    name: 'Data Use Restrictions',
    description: 'Data holders must not use non-personal data from connected products to derive insights about economic situation, assets, or production methods of users or third parties.',
    category: 'Data Holder Obligations',
    implementationGuidance: 'Implement data use restrictions. Define prohibited use categories. Monitor data usage compliance. Train personnel on restrictions.',
    evidenceRequirements: [
      'Data use restriction policies',
      'Prohibited use category definitions',
      'Usage monitoring records',
      'Training documentation'
    ],
    testProcedures: [
      'Review restriction policy adequacy',
      'Test prohibition enforcement',
      'Verify monitoring effectiveness',
      'Assess training completion'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-3.3',
    name: 'Trade Secret Protection',
    description: 'Data holders may take measures to protect trade secrets when sharing data, but must not refuse access based on trade secret protection unless strictly necessary.',
    category: 'Data Holder Obligations',
    implementationGuidance: 'Identify trade secrets in shared data. Implement protection measures proportionate to risk. Document trade secret claims. Balance protection with access obligations.',
    evidenceRequirements: [
      'Trade secret identification records',
      'Protection measure documentation',
      'Trade secret claim documentation',
      'Balancing assessment records'
    ],
    testProcedures: [
      'Review trade secret identification',
      'Assess protection measure proportionality',
      'Verify claim documentation',
      'Test balancing assessment process'
    ],
    status: 'Not Started'
  },

  // ===== Chapter V: Data Access by Public Bodies =====
  {
    controlId: 'DA-4.1',
    name: 'Public Body Data Access',
    description: 'Public sector bodies and EU institutions may request access to private sector data in cases of exceptional need, such as public emergencies or statistical purposes.',
    category: 'Public Body Access',
    implementationGuidance: 'Establish public body request handling procedures. Verify request legitimacy per Data Act criteria. Implement secure data transmission. Document request handling.',
    evidenceRequirements: [
      'Request handling procedures',
      'Legitimacy verification documentation',
      'Secure transmission documentation',
      'Request handling records'
    ],
    testProcedures: [
      'Test request handling process',
      'Verify legitimacy verification accuracy',
      'Assess transmission security',
      'Review handling record completeness'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-4.2',
    name: 'Emergency Data Access',
    description: 'In public emergencies (pandemics, natural disasters, major cyber incidents), data access must be provided within shorter timeframes as specified by requesting body.',
    category: 'Public Body Access',
    implementationGuidance: 'Define emergency response procedures for data access. Establish expedited processing capability. Identify emergency-relevant data in advance. Test emergency response readiness.',
    evidenceRequirements: [
      'Emergency response procedures',
      'Expedited processing documentation',
      'Emergency data identification',
      'Response readiness testing records'
    ],
    testProcedures: [
      'Review emergency procedures adequacy',
      'Test expedited processing capability',
      'Verify emergency data identification',
      'Assess readiness testing results'
    ],
    status: 'Not Started'
  },

  // ===== Chapter VI: Cloud Switching =====
  {
    controlId: 'DA-5.1',
    name: 'Cloud Data Portability',
    description: 'Cloud service providers must enable customers to switch to other providers or on-premises systems, including data export in structured, commonly used format.',
    category: 'Cloud Switching',
    implementationGuidance: 'Implement data export functionality. Support standard data formats. Provide data migration tools. Document export capabilities.',
    evidenceRequirements: [
      'Data export capability documentation',
      'Supported format specifications',
      'Migration tool documentation',
      'Capability documentation'
    ],
    testProcedures: [
      'Test data export functionality',
      'Verify format compliance',
      'Assess migration tool effectiveness',
      'Review capability documentation'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-5.2',
    name: 'Switching Charge Phase-Out',
    description: 'Cloud providers must phase out switching charges over three years following regulation entry. After transition period, switching charges are prohibited.',
    category: 'Cloud Switching',
    implementationGuidance: 'Review current switching charges. Develop phase-out plan per regulatory timeline. Eliminate charges by deadline. Document charge changes.',
    evidenceRequirements: [
      'Current charge documentation',
      'Phase-out plan',
      'Charge elimination records',
      'Compliance timeline documentation'
    ],
    testProcedures: [
      'Verify current charge accuracy',
      'Review phase-out plan adequacy',
      'Confirm charge elimination',
      'Test timeline compliance'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-5.3',
    name: 'Functional Equivalence',
    description: 'Cloud providers must achieve open interoperability and functional equivalence to enable switching between services providing same service type and functionality.',
    category: 'Cloud Switching',
    implementationGuidance: 'Document service functionality specifications. Implement interoperability interfaces. Support standard APIs and protocols. Test equivalence with competing services.',
    evidenceRequirements: [
      'Functionality specification documentation',
      'Interoperability interface documentation',
      'Standard API support records',
      'Equivalence testing results'
    ],
    testProcedures: [
      'Review functionality specifications',
      'Test interoperability interfaces',
      'Verify standard API compliance',
      'Assess equivalence testing coverage'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-5.4',
    name: 'Switching Process Support',
    description: 'Cloud providers must offer maximum switching periods of 30 days and provide all necessary technical support for the switching process.',
    category: 'Cloud Switching',
    implementationGuidance: 'Define switching process with 30-day maximum timeline. Provide switching support resources. Assign switching assistance personnel. Track switching completion.',
    evidenceRequirements: [
      'Switching process documentation',
      'Support resource documentation',
      'Personnel assignment records',
      'Switching completion records'
    ],
    testProcedures: [
      'Verify timeline compliance',
      'Test support resource availability',
      'Review personnel capability',
      'Assess completion tracking accuracy'
    ],
    status: 'Not Started'
  },

  // ===== Chapter VII: International Data Access =====
  {
    controlId: 'DA-6.1',
    name: 'Third Country Data Access Safeguards',
    description: 'Data processing service providers must take measures to prevent unlawful third-country government access to non-personal data held in EU.',
    category: 'International Data Access',
    implementationGuidance: 'Assess third-country access risks. Implement technical and organizational safeguards. Establish government request handling procedures. Document safeguard measures.',
    evidenceRequirements: [
      'Third-country risk assessment',
      'Safeguard measure documentation',
      'Government request procedures',
      'Safeguard documentation'
    ],
    testProcedures: [
      'Review risk assessment comprehensiveness',
      'Test safeguard effectiveness',
      'Verify request handling procedures',
      'Assess documentation adequacy'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-6.2',
    name: 'International Transfer Requirements',
    description: 'Non-personal data may only be transferred to third countries where adequate safeguards exist or subject to supplementary measures ensuring equivalent protection.',
    category: 'International Data Access',
    implementationGuidance: 'Assess adequacy of third-country protection. Implement supplementary measures where needed. Document transfer legal basis. Monitor regulatory developments.',
    evidenceRequirements: [
      'Adequacy assessment documentation',
      'Supplementary measure records',
      'Transfer legal basis documentation',
      'Regulatory monitoring records'
    ],
    testProcedures: [
      'Review adequacy assessment accuracy',
      'Test supplementary measure effectiveness',
      'Verify legal basis documentation',
      'Assess monitoring process'
    ],
    status: 'Not Started'
  },

  // ===== Chapter VIII: Interoperability =====
  {
    controlId: 'DA-7.1',
    name: 'Data Interoperability Standards',
    description: 'Data must be made available in formats that enable interoperability. Commission may adopt common specifications for data formats and interoperability.',
    category: 'Interoperability',
    implementationGuidance: 'Adopt standard data formats. Implement API interoperability. Monitor Commission specifications. Update implementations for new standards.',
    evidenceRequirements: [
      'Standard format adoption records',
      'API interoperability documentation',
      'Commission specification monitoring',
      'Implementation update records'
    ],
    testProcedures: [
      'Test standard format compliance',
      'Verify API interoperability',
      'Review specification monitoring',
      'Assess update implementation'
    ],
    status: 'Not Started'
  },
  {
    controlId: 'DA-7.2',
    name: 'Smart Contract Interoperability',
    description: 'Smart contracts used for data sharing must meet essential requirements for interoperability, including safe termination, data archiving, and access control.',
    category: 'Interoperability',
    implementationGuidance: 'Design smart contracts meeting essential requirements. Implement safe termination mechanisms. Enable data archiving. Apply access control.',
    evidenceRequirements: [
      'Smart contract design documentation',
      'Termination mechanism documentation',
      'Data archiving implementation',
      'Access control documentation'
    ],
    testProcedures: [
      'Review design compliance',
      'Test termination mechanism',
      'Verify archiving functionality',
      'Assess access control effectiveness'
    ],
    status: 'Not Started'
  }
];
