/**
 * Regulatory Intelligence Fabric Service Unit Tests - Comprehensive Coverage
 */

import { jest, describe, it, expect, beforeEach } from '@jest/globals';
import { prismaMock } from '../../../mocks/prisma';

jest.mock('../../../../config/database', () => ({
  __esModule: true,
  default: prismaMock,
}));

jest.mock('../../../../config/logger', () => ({
  __esModule: true,
  default: {
    info: jest.fn(),
    error: jest.fn(),
    warn: jest.fn(),
    debug: jest.fn(),
  },
}));

jest.mock('../../../../services/notificationService', () => ({
  __esModule: true,
  default: {
    sendNotification: jest.fn<any>().mockResolvedValue(undefined),
    notifyAdmins: jest.fn<any>().mockResolvedValue(undefined),
  },
}));

const mockPdfParse = jest.fn<any>().mockResolvedValue({ text: 'Sample regulation text' });
jest.mock('pdf-parse', () => mockPdfParse);

const mockGenerateContent = jest.fn<any>().mockResolvedValue({
  response: {
    text: jest.fn<any>().mockReturnValue(JSON.stringify({
      requirements: ['Implement access controls', 'Maintain audit logs'],
    })),
  },
});

jest.mock('@google/generative-ai', () => ({
  GoogleGenerativeAI: jest.fn<any>().mockImplementation(() => ({
    getGenerativeModel: jest.fn<any>().mockReturnValue({
      generateContent: mockGenerateContent,
    }),
  })),
}));

jest.mock('axios', () => ({
  __esModule: true,
  default: {
    get: jest.fn<any>().mockResolvedValue({
      data: '<html><body>Regulation text content</body></html>',
    }),
  },
}));

jest.mock('../../../../utils/urlValidator', () => ({
  isUrlSafe: jest.fn<any>().mockReturnValue(true),
}));

import regulatoryIntelligenceFabricService from '../../../../services/advanced/regulatoryIntelligenceFabricService';

describe('RegulatoryIntelligenceFabricService', () => {
  const orgId = 'org-123';
  const userId = 'user-123';

  const mockRegChange = {
    id: 'reg-1',
    organizationId: orgId,
    regulationName: 'GDPR Amendment',
    jurisdiction: 'EU',
    effectiveDate: new Date(),
    changeType: 'new',
    affectedFrameworks: ['fw-1'],
    extractedRequirements: ['Implement DPA', 'Update consent forms'],
    autoGeneratedControls: [{ name: 'DPA Control', description: 'Implement DPA', category: 'Privacy' }],
    status: 'analyzed',
    regulationText: 'Regulation text content',
    source: null,
    feedId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const mockFramework = {
    id: 'fw-1',
    name: 'GDPR',
    organizationId: orgId,
    controls: [
      { id: 'c-1', name: 'Data Protection', description: 'data protection agreement', status: 'Implemented' },
    ],
  };

  beforeEach(() => {
    jest.clearAllMocks();

    const { GoogleGenerativeAI } = require('@google/generative-ai');
    GoogleGenerativeAI.mockImplementation(() => ({
      getGenerativeModel: jest.fn<any>().mockReturnValue({
        generateContent: mockGenerateContent,
      }),
    }));
    mockGenerateContent.mockResolvedValue({
      response: {
        text: jest.fn<any>().mockReturnValue(JSON.stringify({
          requirements: ['Implement access controls', 'Maintain audit logs'],
        })),
      },
    });

    const axios = require('axios').default;
    axios.get.mockResolvedValue({
      data: '<html><body>Regulation text content</body></html>',
    });

    const { isUrlSafe } = require('../../../../utils/urlValidator');
    isUrlSafe.mockReturnValue(true);

    const notificationService = require('../../../../services/notificationService').default;
    notificationService.sendNotification.mockResolvedValue(undefined);
    notificationService.notifyAdmins.mockResolvedValue(undefined);

    (prismaMock.auditLog.create as jest.Mock<any>).mockResolvedValue({});
    (prismaMock.auditLog.findFirst as jest.Mock<any>).mockResolvedValue(null);
    (prismaMock.auditLog.findMany as jest.Mock<any>).mockResolvedValue([]);
    (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([]);
    (prismaMock.frameworkControl.findFirst as jest.Mock<any>).mockResolvedValue(null);
    (prismaMock.frameworkControl.create as jest.Mock<any>).mockResolvedValue({});
    (prismaMock.frameworkControl.update as jest.Mock<any>).mockResolvedValue({});
    (prismaMock.user.findMany as jest.Mock<any>).mockResolvedValue([]);
    (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValue([]);
    (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockResolvedValue(null);
    (prismaMock.regulatoryChange.findUnique as jest.Mock<any>).mockResolvedValue(null);
    (prismaMock.regulatoryChange.create as jest.Mock<any>).mockResolvedValue(mockRegChange);
    (prismaMock.regulatoryChange.update as jest.Mock<any>).mockResolvedValue(mockRegChange);
    (prismaMock.regulatoryFeed.findMany as jest.Mock<any>).mockResolvedValue([]);
    (prismaMock.regulatoryFeed.create as jest.Mock<any>).mockResolvedValue({});
    (prismaMock.regulatoryFeed.delete as jest.Mock<any>).mockResolvedValue({});
    (prismaMock.regulatoryFeed.update as jest.Mock<any>).mockResolvedValue({});
    (prismaMock.regulatoryFeed.findFirst as jest.Mock<any>).mockResolvedValue(null);
  });

  // ===================== ingestRegulation =====================
  describe('ingestRegulation', () => {
    it('should ingest regulation from text', async () => {
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([mockFramework]);
      (prismaMock.user.findMany as jest.Mock<any>).mockResolvedValue([{ id: userId, role: 'Admin' }]);

      const result = await regulatoryIntelligenceFabricService.ingestRegulation(
        orgId,
        { text: 'New GDPR amendment requires organizations to implement data protection agreements...' },
        { name: 'GDPR Amendment', jurisdiction: 'EU', effectiveDate: new Date(Date.now() + 90 * 86400000) },
        userId
      );

      expect(result).toBeDefined();
      expect(result.regulationName).toBe('GDPR Amendment');
      expect(result.jurisdiction).toBe('EU');
    });

    it('should ingest regulation from URL', async () => {
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([mockFramework]);

      const result = await regulatoryIntelligenceFabricService.ingestRegulation(
        orgId,
        { url: 'https://example.com/regulation.html' },
        { name: 'CCPA Update', jurisdiction: 'US-CA', effectiveDate: new Date() },
        userId
      );

      expect(result).toBeDefined();
      expect(prismaMock.regulatoryChange.create).toHaveBeenCalled();
    });

    it('should throw error when no input provided', async () => {
      await expect(
        regulatoryIntelligenceFabricService.ingestRegulation(
          orgId, {}, { name: 'Test', jurisdiction: 'US', effectiveDate: new Date() }, userId
        )
      ).rejects.toThrow('No input provided');
    });

    it('should detect duplicate regulations', async () => {
      (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValue([
        { id: 'existing-1', regulationName: 'GDPR Amendment', regulationText: 'Same regulation text content' },
      ]);

      await expect(
        regulatoryIntelligenceFabricService.ingestRegulation(
          orgId,
          { text: 'Same regulation text content' },
          { name: 'GDPR Amendment', jurisdiction: 'EU', effectiveDate: new Date() },
          userId
        )
      ).rejects.toThrow('Duplicate regulation');
    });

    it('should handle URL fetch failure', async () => {
      const axios = require('axios').default;
      axios.get.mockRejectedValueOnce(new Error('Network error'));

      await expect(
        regulatoryIntelligenceFabricService.ingestRegulation(
          orgId,
          { url: 'https://example.com/bad-url' },
          { name: 'Test', jurisdiction: 'US', effectiveDate: new Date() },
          userId
        )
      ).rejects.toThrow('Failed to fetch regulation from URL');
    });

    it('should reject unsafe URLs (SSRF protection)', async () => {
      const { isUrlSafe } = require('../../../../utils/urlValidator');
      isUrlSafe.mockReturnValue(false);

      await expect(
        regulatoryIntelligenceFabricService.ingestRegulation(
          orgId,
          { url: 'http://169.254.169.254/latest/meta-data' },
          { name: 'Test', jurisdiction: 'US', effectiveDate: new Date() },
          userId
        )
      ).rejects.toThrow();
    });

    it('should set status to conflict when conflicts detected', async () => {
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([mockFramework]);
      (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValueOnce([]) // duplicate check
        .mockResolvedValue([
          {
            id: 'old-reg',
            regulationName: 'Existing Regulation',
            jurisdiction: 'EU',
            affectedFrameworks: ['fw-1'],
            extractedRequirements: ['must retain data for 7 years'],
            regulationText: 'must retain all records',
          },
        ]);

      const result = await regulatoryIntelligenceFabricService.ingestRegulation(
        orgId,
        { text: 'Organizations must delete all personal data after 30 days' },
        { name: 'Data Deletion Regulation', jurisdiction: 'EU', effectiveDate: new Date() },
        userId
      );

      expect(result).toBeDefined();
    });

    it('should ingest regulation with feedId', async () => {
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([mockFramework]);

      const result = await regulatoryIntelligenceFabricService.ingestRegulation(
        orgId,
        { text: 'New regulation text' },
        { name: 'Fed Rule', jurisdiction: 'US', effectiveDate: new Date(), feedId: 'feed-1' },
        userId
      );

      expect(result).toBeDefined();
    });
  });

  // ===================== detectConflicts =====================
  describe('detectConflicts', () => {
    it('should detect jurisdiction conflicts', async () => {
      (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValue([
        {
          id: 'reg-1',
          regulationName: 'EU Retention',
          jurisdiction: 'EU',
          extractedRequirements: ['must retain data for 7 years'],
          affectedFrameworks: ['fw-1'],
          regulationText: 'must retain data',
        },
      ]);
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([mockFramework]);

      const result = await (regulatoryIntelligenceFabricService as any).detectConflicts(
        'EU', ['fw-1'], orgId
      );

      expect(result).toBeDefined();
      expect(Array.isArray(result)).toBe(true);
    });

    it('should return empty when no conflicts exist', async () => {
      (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValue([]);

      const result = await (regulatoryIntelligenceFabricService as any).detectConflicts(
        'US', ['fw-2'], orgId
      );

      expect(result).toEqual([]);
    });
  });

  // ===================== bulkConflictAnalysis =====================
  describe('bulkConflictAnalysis', () => {
    it('should analyze conflicts across multiple regulations', async () => {
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockResolvedValue({
        id: 'reg-1',
        regulationName: 'EU GDPR',
        jurisdiction: 'EU',
        affectedFrameworks: ['fw-1'],
        regulationText: 'data must be retained',
      });
      (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValue([]);

      const result = await regulatoryIntelligenceFabricService.bulkConflictAnalysis(orgId, ['reg-1']);

      expect(result).toBeDefined();
      expect(result.totalConflicts).toBeDefined();
      expect(result.conflictsBySeverity).toBeDefined();
    });

    it('should return zero conflicts when no regulations exist', async () => {
      const result = await regulatoryIntelligenceFabricService.bulkConflictAnalysis(orgId, []);

      expect(result.totalConflicts).toBe(0);
    });

    it('should handle database error in bulk analysis', async () => {
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockRejectedValue(new Error('DB error'));

      await expect(
        regulatoryIntelligenceFabricService.bulkConflictAnalysis(orgId, ['reg-1'])
      ).rejects.toThrow();
    });
  });

  // ===================== getConflictHistory =====================
  describe('getConflictHistory', () => {
    it('should return conflict history from audit logs', async () => {
      (prismaMock.auditLog.findMany as jest.Mock<any>).mockResolvedValue([
        {
          id: 'log-1',
          details: JSON.stringify({
            conflicts: [
              { id: 'conflict-1', regulation1: 'A', regulation2: 'B', severity: 'high' },
            ],
          }),
        },
      ]);

      const result = await regulatoryIntelligenceFabricService.getConflictHistory(orgId);

      expect(result).toBeDefined();
      expect(result.length).toBeGreaterThanOrEqual(1);
    });

    it('should return empty array when no conflict history', async () => {
      (prismaMock.auditLog.findMany as jest.Mock<any>).mockResolvedValue([]);

      const result = await regulatoryIntelligenceFabricService.getConflictHistory(orgId);
      expect(result).toEqual([]);
    });

    it('should skip invalid logs gracefully', async () => {
      (prismaMock.auditLog.findMany as jest.Mock<any>).mockResolvedValue([
        { id: 'log-1', details: 'invalid-json{{{' },
        { id: 'log-2', details: JSON.stringify({ conflicts: [{ id: 'c1' }] }) },
      ]);

      const result = await regulatoryIntelligenceFabricService.getConflictHistory(orgId);
      expect(result.length).toBe(1);
    });

    it('should handle database error gracefully', async () => {
      (prismaMock.auditLog.findMany as jest.Mock<any>).mockRejectedValue(new Error('DB error'));

      const result = await regulatoryIntelligenceFabricService.getConflictHistory(orgId);
      expect(result).toEqual([]);
    });

    it('should respect limit parameter', async () => {
      (prismaMock.auditLog.findMany as jest.Mock<any>).mockResolvedValue([]);

      await regulatoryIntelligenceFabricService.getConflictHistory(orgId, 10);
      expect(prismaMock.auditLog.findMany).toHaveBeenCalled();
    });
  });

  // ===================== resolveConflict =====================
  describe('resolveConflict', () => {
    it('should resolve a conflict and create audit log', async () => {
      await regulatoryIntelligenceFabricService.resolveConflict(
        'conflict-1', orgId, 'Apply stricter standard', userId
      );

      expect(prismaMock.auditLog.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({
            action: 'rif.conflict_resolved',
            organizationId: orgId,
          }),
        })
      );
    });

    it('should handle database error during resolution', async () => {
      (prismaMock.auditLog.create as jest.Mock<any>).mockRejectedValueOnce(new Error('DB error'));

      await expect(
        regulatoryIntelligenceFabricService.resolveConflict('conflict-1', orgId, 'Resolution', userId)
      ).rejects.toThrow();
    });
  });

  // ===================== autoUpdateControls =====================
  describe('autoUpdateControls', () => {
    it('should throw when regulatory change not found', async () => {
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockResolvedValueOnce(null);

      await expect(
        regulatoryIntelligenceFabricService.autoUpdateControls('nonexistent', orgId, userId)
      ).rejects.toThrow('Regulatory change not found');
    });

    it('should return preview in dry-run mode', async () => {
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockResolvedValueOnce(mockRegChange);
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([mockFramework]);

      const result = await regulatoryIntelligenceFabricService.autoUpdateControls(
        'reg-1', orgId, userId, { dryRun: true }
      );

      expect(result).toBeDefined();
      expect(result.preview).toBeDefined();
    });

    it('should queue for approval when requireApproval is true', async () => {
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockResolvedValueOnce(mockRegChange);
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([mockFramework]);

      const result = await regulatoryIntelligenceFabricService.autoUpdateControls(
        'reg-1', orgId, userId, { requireApproval: true }
      );

      expect(result.requiresApproval).toBe(true);
      expect(result.approvalId).toBeDefined();
    });

    it('should create/update controls when not requiring approval', async () => {
      const regChange = {
        ...mockRegChange,
        autoGeneratedControls: [{ name: 'New Control', description: 'New control desc', category: 'Regulatory' }],
      };
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockResolvedValue(regChange);
      // createCheckpoint needs regulatory change and frameworks
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([
        { ...mockFramework, controls: [] },
      ]);

      const result = await regulatoryIntelligenceFabricService.autoUpdateControls(
        'reg-1', orgId, userId, { requireApproval: false }
      );

      expect(result).toBeDefined();
      expect(result.controlsCreated).toBeGreaterThanOrEqual(0);
    });

    it('should handle errors during auto-update and log them', async () => {
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockRejectedValueOnce(new Error('DB error'));

      await expect(
        regulatoryIntelligenceFabricService.autoUpdateControls('reg-1', orgId, userId, { requireApproval: false })
      ).rejects.toThrow();
    });

    it('should update existing controls when matching name found', async () => {
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockResolvedValue({
        ...mockRegChange,
        autoGeneratedControls: [{ name: 'Data Protection', description: 'Updated desc', category: 'Privacy' }],
      });
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([mockFramework]);

      const result = await regulatoryIntelligenceFabricService.autoUpdateControls(
        'reg-1', orgId, userId, { requireApproval: false }
      );

      expect(result).toBeDefined();
    });
  });

  // ===================== approveAutoUpdate =====================
  describe('approveAutoUpdate', () => {
    it('should throw when approval not found', async () => {
      (prismaMock.auditLog.findFirst as jest.Mock<any>).mockResolvedValueOnce(null);

      await expect(
        regulatoryIntelligenceFabricService.approveAutoUpdate('approval-1', orgId, userId)
      ).rejects.toThrow('Approval request not found');
    });

    it('should throw when approval is not pending', async () => {
      (prismaMock.auditLog.findFirst as jest.Mock<any>).mockResolvedValueOnce({
        details: JSON.stringify({ status: 'approved', regulatoryChangeId: 'reg-1' }),
      });

      await expect(
        regulatoryIntelligenceFabricService.approveAutoUpdate('approval-1', orgId, userId)
      ).rejects.toThrow('not pending');
    });

    it('should approve and execute auto-update', async () => {
      (prismaMock.auditLog.findFirst as jest.Mock<any>).mockResolvedValueOnce({
        details: JSON.stringify({
          status: 'pending_approval',
          regulatoryChangeId: 'reg-1',
        }),
      });
      // autoUpdateControls internals - need findFirst to persist for createCheckpoint too
      (prismaMock.regulatoryChange.findFirst as jest.Mock<any>).mockResolvedValue(mockRegChange);
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([
        { ...mockFramework, controls: [] },
      ]);

      const result = await regulatoryIntelligenceFabricService.approveAutoUpdate('approval-1', orgId, userId);

      expect(result).toBeDefined();
      expect(result.controlsCreated).toBeDefined();
    });
  });

  // ===================== rollbackAutoUpdate =====================
  describe('rollbackAutoUpdate', () => {
    it('should throw when checkpoint not found', async () => {
      (prismaMock.auditLog.findFirst as jest.Mock<any>).mockResolvedValueOnce(null);

      await expect(
        regulatoryIntelligenceFabricService.rollbackAutoUpdate('reg-1', 'checkpoint-1', orgId, userId)
      ).rejects.toThrow('Checkpoint not found');
    });

    it('should restore controls from checkpoint', async () => {
      (prismaMock.auditLog.findFirst as jest.Mock<any>).mockResolvedValueOnce({
        details: JSON.stringify({
          controls: [
            { id: 'c-1', name: 'Control 1', description: 'Desc 1', status: 'Implemented' },
          ],
        }),
      });

      const result = await regulatoryIntelligenceFabricService.rollbackAutoUpdate(
        'reg-1', 'checkpoint-1', orgId, userId
      );

      expect(result.success).toBe(true);
      expect(result.controlsRestored).toBeGreaterThanOrEqual(0);
    });
  });

  // ===================== getRegulatoryChanges =====================
  describe('getRegulatoryChanges', () => {
    it('should return regulations for organization', async () => {
      (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValue([mockRegChange]);

      const result = await regulatoryIntelligenceFabricService.getRegulatoryChanges(orgId);
      expect(result).toBeDefined();
      expect(Array.isArray(result)).toBe(true);
    });

    it('should filter by jurisdiction', async () => {
      (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValue([mockRegChange]);

      const result = await regulatoryIntelligenceFabricService.getRegulatoryChanges(orgId);
      expect(result).toBeDefined();
    });

    it('should filter by status', async () => {
      (prismaMock.regulatoryChange.findMany as jest.Mock<any>).mockResolvedValue([mockRegChange]);

      const result = await regulatoryIntelligenceFabricService.getRegulatoryChanges(orgId, 'analyzed');
      expect(result).toBeDefined();
    });
  });

  // ===================== extractRequirements (private via ingestRegulation) =====================
  describe('extractRequirements', () => {
    it('should extract requirements using AI when available', async () => {
      (prismaMock.complianceFramework.findMany as jest.Mock<any>).mockResolvedValue([]);

      const result = await regulatoryIntelligenceFabricService.ingestRegulation(
        orgId,
        { text: 'Organizations must encrypt personal data at rest and in transit.' },
        { name: 'Encryption Rule', jurisdiction: 'US', effectiveDate: new Date() },
        userId
      );

      expect(result).toBeDefined();
    });

    it('should handle AI failure and use fallback extraction', async () => {
      mockGenerateContent.mockRejectedValueOnce(new Error('AI unavailable'));

      const result = await regulatoryIntelligenceFabricService.ingestRegulation(
        orgId,
        { text: 'Organizations shall implement access controls. Organizations must maintain audit logs.' },
        { name: 'Access Rule', jurisdiction: 'US', effectiveDate: new Date() },
        userId
      );

      expect(result).toBeDefined();
    });
  });

  // ===================== Error paths =====================
  describe('error handling', () => {
    it('should handle PDF extraction error', async () => {
      mockPdfParse.mockRejectedValueOnce(new Error('Invalid PDF'));
      await expect(
        regulatoryIntelligenceFabricService.ingestRegulation(
          orgId,
          { pdfBuffer: Buffer.alloc(0) },
          { name: 'Test', jurisdiction: 'US', effectiveDate: new Date() },
          userId
        )
      ).rejects.toThrow();
    });
  });
});
