/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './**/*.{js,ts,jsx,tsx}',
    '!./node_modules/**',
    '!./server/**',
    '!./mobile/**',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['"Space Grotesk"', 'Inter', 'sans-serif'],
        plex: ['"IBM Plex Sans"', 'Inter', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        signal: {
          canvas: '#07090D',
          panel: '#0A0E15',
          panel2: '#0C1017',
          panel3: '#0C1420',
          green: '#38E8A6',
          blue: '#3AA0FF',
          violet: '#B98CFF',
          amber: '#E8B93A',
          good: '#34C88A',
          warn: '#E8B93A',
          bad: '#F87171',
          ink: '#E9EDF4',
          body: '#c7cedb',
          body2: '#b7bfcc',
          sub: '#9aa4b5',
          muted: '#5B6577',
        },
        brand: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          800: '#115e59',
          900: '#134e4a',
          950: '#042f2e',
        },
        accent: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
        },
        // Dark end (700-950) remapped to the Signal canvas/panel hues so the
        // app's existing dark: classes land on the Signal palette globally.
        surface: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#1A2130',
          800: '#0C1017',
          900: '#0A0E15',
          950: '#07090D',
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s ease-out',
        fadeInUp: 'fadeInUp 0.5s ease-out',
        fadeInDown: 'fadeInDown 0.4s ease-out',
        slideInLeft: 'slideInLeft 0.3s ease-out',
        slideInRight: 'slideInRight 0.3s ease-out',
        scaleIn: 'scaleIn 0.2s ease-out',
        'confetti-fall': 'confettiFall 3s ease-in forwards',
        'checkmark-draw': 'checkmarkDraw 0.6s ease-out 0.3s forwards',
        'onboarding-modal-in': 'onboardingModalIn 0.3s ease-out',
        'onboarding-slide-up': 'onboardingSlideUp 0.25s ease-out',
        'pulse-slow': 'pulse 4s ease-in-out infinite',
        'pulse-slow-delay': 'pulse 4s ease-in-out 2s infinite',
        shimmer: 'shimmer 2s linear infinite',
        float: 'float 6s ease-in-out infinite',
        glow: 'glow 2s ease-in-out infinite alternate',
        gradient: 'gradient 8s ease infinite',
        'spin-slow': 'spin 3s linear infinite',
        'count-up': 'countUp 1s ease-out',
        'pulse-ring': 'pulseRing 3.2s ease-out infinite',
        'pulse-ring-delay': 'pulseRing 3.2s ease-out 1.6s infinite',
        'blink-dot': 'blinkDot 1.6s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        confettiFall: {
          '0%': { transform: 'translateY(0) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(100vh) rotate(720deg)', opacity: '0' },
        },
        checkmarkDraw: {
          '0%': { strokeDashoffset: '24' },
          '100%': { strokeDashoffset: '0' },
        },
        onboardingModalIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        onboardingSlideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 20px rgba(13, 148, 136, 0.2)' },
          '100%': { boxShadow: '0 0 40px rgba(13, 148, 136, 0.4)' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        countUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseRing: {
          '0%': { transform: 'scale(0.55)', opacity: '0.8' },
          '100%': { transform: 'scale(2.3)', opacity: '0' },
        },
        blinkDot: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.25' },
        },
      },
      backgroundImage: {
        'signal-glow': 'radial-gradient(1000px 520px at 50% -10%, rgba(56,232,166,0.2), #07090D)',
        'signal-glow-tight': 'radial-gradient(760px 420px at 50% -10%, rgba(56,232,166,0.2), #07090D)',
      },
      backgroundSize: {
        '300%': '300%',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
};
