/**
 * Regulatory Intelligence Fabric (RIF) Service
 * 
 * Features:
 * - Real-time regulatory NLP ingestion
 * - Automatic control updates based on new regulations
 * - Jurisdiction conflict detection
 * - Regulatory change notifications
 * - Framework auto-adaptation
 */

import prisma from '../../config/database';
import logger from '../../config/logger';
import { GoogleGenerativeAI } from '@google/generative-ai';
import axios from 'axios';
import * as crypto from 'crypto';
import notificationService from '../notificationService';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export interface RegulatoryChange {
  id: string;
  regulationName: string;
  jurisdiction: string;
  effectiveDate: Date;
  changeType: 'new' | 'amendment' | 'repeal';
  affectedFrameworks: string[];
  extractedRequirements: string[];
  autoGeneratedControls?: any[];
  status: 'pending' | 'analyzed' | 'implemented' | 'conflict';
}

export interface JurisdictionConflict {
  id: string;
  regulation1: string;
  regulation2: string;
  conflictType: 'contradiction' | 'overlap' | 'requirement_mismatch' | 'implicit';
  description: string;
  resolution?: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  affectedFrameworks?: string[];
  resolved?: boolean;
  resolvedAt?: Date;
  resolvedBy?: string;
}

export interface RegulatoryFeed {
  id: string;
  name: string;
  url: string;
  feedType: 'rss' | 'api' | 'website';
  jurisdiction: string;
  pollingInterval: number; // minutes
  lastChecked?: Date;
  lastError?: string;
  status: 'active' | 'inactive' | 'error';
  authentication?: {
    type: 'api_key' | 'oauth' | 'basic';
    credentials?: any;
  };
  organizationId: string;
}

export interface RegulationSection {
  id: string;
  title: string;
  content: string;
  sectionNumber?: string;
  parentSectionId?: string;
}

export interface ChangeSummary {
  changeType: 'new' | 'amendment' | 'repeal';
  severity: 'critical' | 'high' | 'medium' | 'low';
  affectedControls: number;
  affectedFrameworks: number;
  implementationDeadline?: Date;
  summary: string;
  recommendations: string[];
}

class RegulatoryIntelligenceFabricService {
  /**
   * Ingest new regulatory document (enhanced with URL/PDF/text support)
   */
  async ingestRegulation(
    organizationId: string,
    input: {
      url?: string;
      pdfBuffer?: Buffer;
      text?: string;
    },
    metadata: {
      name: string;
      jurisdiction: string;
      effectiveDate: Date;
      source?: string;
      feedId?: string; // Link to RegulatoryFeed
    },
    userId: string
  ): Promise<RegulatoryChange> {
    try {
      let regulationText = '';
      let sourceUrl = metadata.source;

      // 1. Ingest from URL
      if (input.url) {
        try {
          // SECURITY: SSRF Protection - Validate URL before fetching
          const { isUrlSafe } = await import('../../utils/urlValidator');
          if (!isUrlSafe(input.url)) {
            throw new Error('URL is not allowed for security reasons (SSRF protection)');
          }

          const response = await axios.get(input.url, {
            timeout: 30000,
            headers: {
              'User-Agent': 'ComplyEasyAI-RIF/1.0',
            },
          });
          regulationText = response.data;
          sourceUrl = input.url;
        } catch (urlError: any) {
          logger.error('[RIF] Error fetching regulation from URL', urlError);
          throw new Error(`Failed to fetch regulation from URL: ${urlError.message}`);
        }
      }
      // 2. Ingest from PDF
      else if (input.pdfBuffer) {
        try {
          regulationText = await this.extractTextFromPDF(input.pdfBuffer);
        } catch (pdfError: any) {
          logger.error('[RIF] Error extracting text from PDF', pdfError);
          throw new Error(`Failed to extract text from PDF: ${pdfError.message}`);
        }
      }
      // 3. Ingest from text
      else if (input.text) {
        regulationText = input.text;
      } else {
        throw new Error('No input provided: url, pdfBuffer, or text required');
      }

      // Check for duplicates
      const duplicate = await this.detectDuplicate(regulationText, organizationId);
      if (duplicate) {
        logger.warn(`[RIF] Duplicate regulation detected: ${duplicate.id}`);
        throw new Error(`Duplicate regulation detected: ${duplicate.regulationName}`);
      }

      // Identify sections
      const sections = await this.identifySections(regulationText);

      // Extract requirements
      const extractedRequirements = await this.extractRequirements(regulationText);

      // Classify regulation type
      const regulationType = await this.classifyRegulationType(regulationText, metadata);

      // Detect version
      const version = await this.detectVersion(regulationText, metadata);

      // Map to existing frameworks
      const affectedFrameworks = await this.mapToFrameworks(
        extractedRequirements,
        organizationId
      );

      // Generate controls automatically
      const autoGeneratedControls = await this.generateControls(
        extractedRequirements,
        organizationId
      );

      // Check for jurisdiction conflicts
      const conflicts = await this.detectConflicts(
        metadata.jurisdiction,
        affectedFrameworks,
        organizationId
      );

      // Generate unique ID
      const regulatoryChangeId = crypto.randomUUID();

      // Store in database
      const dbChange = await prisma.regulatoryChange.create({
        data: {
          id: regulatoryChangeId,
          organizationId,
          regulationName: metadata.name,
          jurisdiction: metadata.jurisdiction,
          effectiveDate: metadata.effectiveDate,
          changeType: 'new',
          affectedFrameworks,
          extractedRequirements,
          autoGeneratedControls: autoGeneratedControls as any,
          status: conflicts.length > 0 ? 'conflict' : 'analyzed',
          regulationText,
          source: sourceUrl,
          feedId: metadata.feedId || null, // Link to feed if provided
          createdBy: userId,
        },
      });

      const regulatoryChange: RegulatoryChange = {
        id: dbChange.id,
        regulationName: dbChange.regulationName,
        jurisdiction: dbChange.jurisdiction,
        effectiveDate: dbChange.effectiveDate,
        changeType: dbChange.changeType as any,
        affectedFrameworks: dbChange.affectedFrameworks,
        extractedRequirements: dbChange.extractedRequirements,
        autoGeneratedControls: dbChange.autoGeneratedControls as any[],
        status: dbChange.status as any,
      };

      // Store regulatory change in audit log
      await prisma.auditLog.create({
        data: {
          action: 'rif.regulation_ingested',
          details: JSON.stringify({
            ...regulatoryChange,
            sections: sections.length,
            regulationType,
            version,
            duplicate: false,
          }),
          userId,
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Regulation ingested: ${regulatoryChange.id} (type: ${regulationType}, version: ${version})`);

      return regulatoryChange;
    } catch (error: any) {
      logger.error('[RIF] Error ingesting regulation', error);
      
      // Log error gracefully
      await prisma.auditLog.create({
        data: {
          action: 'rif.ingestion_error',
          details: JSON.stringify({
            error: error.message,
            metadata,
            timestamp: new Date(),
          }),
          userId: userId || 'system',
          organizationId,
          hash: require('crypto').randomBytes(16).toString('hex'),
        },
      }).catch(() => {
        // Ignore audit log errors
      });

      throw error;
    }
  }

  /**
   * Extract text from PDF buffer
   * Production-ready: Uses pdf-parse library for real PDF text extraction
   */
  private async extractTextFromPDF(pdfBuffer: Buffer): Promise<string> {
    try {
      // Use pdf-parse for real PDF text extraction
      const pdfParse = require('pdf-parse');
      const data = await pdfParse(pdfBuffer);
      
      if (!data || !data.text) {
        logger.warn('[RIF] PDF extraction returned no text');
        return '';
      }

      logger.debug(`[RIF] Extracted ${data.text.length} characters from PDF`);
      return data.text;
    } catch (error) {
      logger.error('[RIF] Error extracting PDF text', error);
      // Fallback: try to extract as plain text if PDF parsing fails
      try {
        const text = pdfBuffer.toString('utf-8', 0, Math.min(10000, pdfBuffer.length));
        if (text && text.trim().length > 0) {
          logger.warn('[RIF] Using fallback text extraction method');
          return text;
        }
      } catch (fallbackError) {
        logger.error('[RIF] Fallback text extraction also failed', fallbackError);
      }
      throw new Error(`PDF text extraction failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Detect duplicate regulations
   */
  private async detectDuplicate(
    regulationText: string,
    organizationId: string
  ): Promise<RegulatoryChange | null> {
    try {
      // Generate hash of regulation text
      const hash = crypto.createHash('sha256').update(regulationText).digest('hex');

      // Check existing regulations for matching hash
      const existingChanges = await prisma.regulatoryChange.findMany({
        where: { organizationId },
      });

      for (const change of existingChanges) {
        if (change.regulationText) {
          const existingHash = crypto.createHash('sha256').update(change.regulationText).digest('hex');
          if (existingHash === hash) {
            return {
              id: change.id,
              regulationName: change.regulationName,
              jurisdiction: change.jurisdiction,
              effectiveDate: change.effectiveDate,
              changeType: change.changeType as any,
              affectedFrameworks: change.affectedFrameworks,
              extractedRequirements: change.extractedRequirements,
              autoGeneratedControls: change.autoGeneratedControls as any[],
              status: change.status as any,
            };
          }
        }
      }

      return null;
    } catch (error) {
      logger.error('[RIF] Error detecting duplicate', error);
      return null;
    }
  }

  /**
   * Identify regulation sections
   */
  private async identifySections(regulationText: string): Promise<RegulationSection[]> {
    const sections: RegulationSection[] = [];

    // Simple section detection (in production, would use NLP)
    const sectionPatterns = [
      /(?:^|\n)\s*(\d+\.?\s+[A-Z][^\n]+)/g,
      /(?:^|\n)\s*([A-Z][A-Z\s]+)\s*\n/g,
      /(?:^|\n)\s*(Article\s+\d+[^\n]+)/gi,
      /(?:^|\n)\s*(Section\s+\d+[^\n]+)/gi,
    ];

    for (const pattern of sectionPatterns) {
      const matches = regulationText.matchAll(pattern);
      for (const match of matches) {
        if (match[1]) {
          sections.push({
            id: `section_${sections.length + 1}`,
            title: match[1].trim(),
            content: match[0].trim(),
          });
        }
      }
    }

    return sections.slice(0, 50); // Limit to 50 sections
  }

  /**
   * Classify regulation type (GDPR/SOC2/ISO/etc)
   */
  private async classifyRegulationType(
    regulationText: string,
    metadata: { name: string; jurisdiction: string }
  ): Promise<string> {
    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

      const prompt = `Classify the following regulation into one of these types: GDPR, SOC2, ISO27001, HIPAA, PCI-DSS, SOX, CCPA, NIST, or Other.
      
      Regulation Name: ${metadata.name}
      Jurisdiction: ${metadata.jurisdiction}
      Text Sample: ${regulationText.substring(0, 1000)}
      
      Return only the classification (e.g., "GDPR", "SOC2", etc.):`;

      const result = await model.generateContent(prompt);
      const response = result.response.text().trim();

      // Extract classification
      const classification = response.split('\n')[0].toUpperCase();
      return classification;
    } catch (error) {
      logger.error('[RIF] Error classifying regulation type', error);
      
      // Fallback classification
      const lowerText = (metadata.name + ' ' + regulationText).toLowerCase();
      if (lowerText.includes('gdpr')) return 'GDPR';
      if (lowerText.includes('soc') || lowerText.includes('soc2')) return 'SOC2';
      if (lowerText.includes('iso') || lowerText.includes('iso27001')) return 'ISO27001';
      if (lowerText.includes('hipaa')) return 'HIPAA';
      if (lowerText.includes('pci') || lowerText.includes('pci-dss')) return 'PCI-DSS';
      if (lowerText.includes('sox')) return 'SOX';
      if (lowerText.includes('ccpa')) return 'CCPA';
      if (lowerText.includes('nist')) return 'NIST';
      return 'Other';
    }
  }

  /**
   * Detect regulation version
   */
  private async detectVersion(
    regulationText: string,
    metadata: { name: string }
  ): Promise<string> {
    // Look for version patterns
    const versionPatterns = [
      /version\s+(\d+\.\d+)/i,
      /v\.?\s*(\d+\.\d+)/i,
      /(\d{4})\s+edition/i,
      /rev\.?\s*(\d+)/i,
    ];

    for (const pattern of versionPatterns) {
      const match = regulationText.match(pattern) || metadata.name.match(pattern);
      if (match && match[1]) {
        return match[1];
      }
    }

    // Default to current year if no version found
    return new Date().getFullYear().toString();
  }

  /**
   * Extract requirements from regulatory text using NLP
   */
  private async extractRequirements(regulationText: string): Promise<string[]> {
    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

      const prompt = `Extract compliance requirements from the following regulatory text.
      Return a JSON array of requirement strings, each describing a specific compliance obligation.

      Regulatory Text:
      ${regulationText.substring(0, 5000)} // Limit to avoid token limits

      Return format:
      ["Requirement 1", "Requirement 2", ...]`;

      const result = await model.generateContent(prompt);
      const response = result.response.text();

      // Parse JSON response
      try {
        const jsonMatch = response.match(/\[[\s\S]*\]/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]);
        }
      } catch (parseError) {
        logger.warn('[RIF] Failed to parse AI response as JSON', parseError);
      }

      // Fallback: simple extraction
      const requirements: string[] = [];
      const sentences = regulationText.split(/[.!?]+/);
      for (const sentence of sentences) {
        if (sentence.toLowerCase().includes('must') || 
            sentence.toLowerCase().includes('shall') ||
            sentence.toLowerCase().includes('required')) {
          requirements.push(sentence.trim());
        }
      }

      return requirements.slice(0, 20); // Limit to 20 requirements
    } catch (error) {
      logger.error('[RIF] Error extracting requirements', error);
      return [];
    }
  }

  /**
   * Map requirements to existing frameworks
   */
  private async mapToFrameworks(
    requirements: string[],
    organizationId: string
  ): Promise<string[]> {
    const frameworks = await prisma.complianceFramework.findMany({
      where: { organizationId },
      select: { id: true, name: true },
    });

    // Simple mapping logic (can be enhanced with ML)
    const affectedFrameworkIds: string[] = [];

    for (const requirement of requirements) {
      const lowerReq = requirement.toLowerCase();

      // Check for framework keywords
      for (const framework of frameworks) {
        const frameworkName = framework.name.toLowerCase();
        
        if (lowerReq.includes('soc') && frameworkName.includes('soc')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        } else if (lowerReq.includes('gdpr') && frameworkName.includes('gdpr')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        } else if (lowerReq.includes('hipaa') && frameworkName.includes('hipaa')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        }
      }
    }

    return affectedFrameworkIds;
  }

  /**
   * Generate controls from requirements
   */
  private async generateControls(
    requirements: string[],
    organizationId: string
  ): Promise<any[]> {
    const controls: any[] = [];

    for (const requirement of requirements.slice(0, 10)) { // Limit to 10 controls
      controls.push({
        name: `Control for: ${requirement.substring(0, 50)}...`,
        description: requirement,
        status: 'Pending',
        autoGenerated: true,
      });
    }

    return controls;
  }

  /**
   * Detect regulatory changes (new/amendment/repeal)
   */
  async detectRegulatoryChanges(
    organizationId: string,
    newRegulationText: string,
    metadata: {
      name: string;
      jurisdiction: string;
      effectiveDate: Date;
    }
  ): Promise<{
    changeType: 'new' | 'amendment' | 'repeal';
    severity: 'critical' | 'high' | 'medium' | 'low';
    affectedControls: string[];
    summary: ChangeSummary;
    timeline: {
      effectiveDate: Date;
      implementationDeadline?: Date;
      notificationDate: Date;
    };
  }> {
    try {
      // Get existing regulations
      const existingRegulations = await prisma.regulatoryChange.findMany({
        where: {
          organizationId,
          jurisdiction: metadata.jurisdiction,
          status: { in: ['pending', 'analyzed', 'implemented'] },
        },
      });

      let changeType: 'new' | 'amendment' | 'repeal' = 'new';
      let severity: 'critical' | 'high' | 'medium' | 'low' = 'medium';

      // Check if this is an amendment
      for (const existing of existingRegulations) {
        if (existing.regulationName.toLowerCase() === metadata.name.toLowerCase()) {
          changeType = 'amendment';
          // Calculate similarity to determine if major or minor amendment
          const similarity = this.calculateTextSimilarity(
            newRegulationText,
            existing.regulationText || ''
          );
          severity = similarity < 0.5 ? 'high' : 'medium';
          break;
        }
      }

      // Check if this is a repeal (look for repeal keywords)
      const repealKeywords = ['repeal', 'revoke', 'cancel', 'withdraw', 'abolish'];
      const isRepeal = repealKeywords.some(keyword => 
        newRegulationText.toLowerCase().includes(keyword)
      );
      if (isRepeal) {
        changeType = 'repeal';
        severity = 'high';
      }

      // Calculate change severity based on content
      if (changeType === 'new') {
        severity = this.calculateChangeSeverity(newRegulationText, metadata);
      }

      // Identify affected controls
      const affectedControls = await this.identifyAffectedControls(
        newRegulationText,
        organizationId
      );

      // Generate change summary
      const summary = await this.generateChangeSummary(
        changeType,
        severity,
        affectedControls.length,
        metadata
      );

      // Calculate implementation deadline (30 days from effective date by default)
      const implementationDeadline = new Date(metadata.effectiveDate);
      implementationDeadline.setDate(implementationDeadline.getDate() + 30);

      return {
        changeType,
        severity,
        affectedControls: affectedControls.map(c => c.id),
        summary,
        timeline: {
          effectiveDate: metadata.effectiveDate,
          implementationDeadline,
          notificationDate: new Date(),
        },
      };
    } catch (error) {
      logger.error('[RIF] Error detecting regulatory changes', error);
      throw error;
    }
  }

  /**
   * Calculate change severity (Enhanced Implementation)
   */
  private calculateChangeSeverity(
    regulationText: string,
    metadata: { jurisdiction: string; effectiveDate?: Date; name?: string }
  ): 'critical' | 'high' | 'medium' | 'low' {
    const lowerText = regulationText.toLowerCase();
    
    // Enhanced keyword detection with scoring
    const criticalKeywords = ['breach', 'penalty', 'fine', 'criminal', 'prison', 'mandatory', 'illegal', 'prosecution'];
    const highKeywords = ['required', 'must', 'shall', 'prohibited', 'violation', 'enforcement', 'sanction', 'non-compliance'];
    const mediumKeywords = ['recommended', 'should', 'guidance', 'best practice', 'advisory', 'consider'];
    const lowKeywords = ['optional', 'may', 'suggested', 'voluntary'];
    
    // Count keyword occurrences
    const criticalCount = criticalKeywords.filter(kw => lowerText.includes(kw)).length;
    const highCount = highKeywords.filter(kw => lowerText.includes(kw)).length;
    const mediumCount = mediumKeywords.filter(kw => lowerText.includes(kw)).length;
    const lowCount = lowKeywords.filter(kw => lowerText.includes(kw)).length;
    
    // Calculate severity score
    let severityScore = criticalCount * 10 + highCount * 5 + mediumCount * 2 - lowCount * 3;
    
    // Adjust based on effective date proximity (if provided)
    if (metadata.effectiveDate) {
      const daysUntilEffective = Math.floor((metadata.effectiveDate.getTime() - Date.now()) / (1000 * 60 * 60 * 24));
      if (daysUntilEffective < 30) {
        severityScore += 5; // Very soon = more critical
      } else if (daysUntilEffective < 90) {
        severityScore += 2;
      }
    }
    
    // Adjust based on jurisdiction importance
    const majorJurisdictions = ['US', 'EU', 'UK', 'CA', 'AU', 'Global'];
    if (majorJurisdictions.includes(metadata.jurisdiction)) {
      severityScore += 3;
    }
    
    // Determine severity level
    if (severityScore >= 15 || criticalCount > 2) return 'critical';
    if (severityScore >= 8 || (criticalCount > 0 || highCount > 2)) return 'high';
    if (severityScore >= 3 || (highCount > 0 || mediumCount > 2)) return 'medium';
    return 'low';
  }

  /**
   * Identify affected controls (Enhanced with AI-powered semantic matching)
   */
  private async identifyAffectedControls(
    regulationText: string,
    organizationId: string
  ): Promise<Array<{ id: string; name: string; matchConfidence?: number; reason?: string }>> {
    try {
      const frameworks = await prisma.complianceFramework.findMany({
        where: { organizationId },
        include: { controls: true },
      });

      if (frameworks.length === 0 || frameworks.every(f => f.controls.length === 0)) {
        return [];
      }

      // Use AI for semantic matching if available
      try {
        const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
        const prompt = `Analyze the following regulation text and identify which compliance controls are affected.

Regulation Text:
${regulationText.substring(0, 4000)}

Available Controls:
${frameworks.flatMap(f => f.controls.map((c, idx) => 
  `${idx + 1}. [${f.name}] ${c.name}\n   Description: ${c.description || 'N/A'}`
)).join('\n\n')}

For each affected control, provide:
- Control number (from list above)
- Match confidence (0-1)
- Brief reason for match

Return JSON array format:
[{"controlNumber": 1, "confidence": 0.85, "reason": "Control directly addresses requirement X"}]

Only include controls with confidence > 0.5.`;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();
        
        // Parse AI response
        const jsonMatch = text.match(/\[[\s\S]*\]/);
        if (jsonMatch) {
          const allControls = frameworks.flatMap(f => f.controls);
          const matches = JSON.parse(jsonMatch[0]);
          const affectedControls: Array<{ id: string; name: string; matchConfidence: number; reason: string }> = [];
          
          for (const match of matches) {
            if (match.controlNumber && match.controlNumber > 0 && match.controlNumber <= allControls.length) {
              const control = allControls[match.controlNumber - 1];
              if (match.confidence > 0.5) {
                affectedControls.push({
                  id: control.id,
                  name: control.name,
                  matchConfidence: match.confidence,
                  reason: match.reason || 'AI-identified semantic match',
                });
              }
            }
          }
          
          if (affectedControls.length > 0) {
            logger.info(`[RIF] AI identified ${affectedControls.length} affected controls`);
            return affectedControls;
          }
        }
      } catch (aiError: any) {
        logger.warn('[RIF] AI-based control identification failed, using keyword matching', aiError);
      }

      // Fallback to enhanced keyword matching
      const affectedControls: Array<{ id: string; name: string; matchConfidence: number; reason: string }> = [];
      const lowerText = regulationText.toLowerCase();
      
      // Extract meaningful keywords (longer words, exclude common words)
      const commonWords = new Set(['the', 'and', 'or', 'but', 'for', 'with', 'from', 'that', 'this', 'are', 'was', 'were']);
      const keywords = regulationText
        .split(/\s+/)
        .filter(w => w.length > 4 && !commonWords.has(w.toLowerCase()))
        .slice(0, 30)
        .map(w => w.toLowerCase().replace(/[^a-z0-9]/g, ''))
        .filter(w => w.length > 0);

      for (const framework of frameworks) {
        for (const control of framework.controls) {
          const controlText = `${control.name} ${control.description || ''}`.toLowerCase();
          const matchingKeywords = keywords.filter(kw => controlText.includes(kw));
          
          if (matchingKeywords.length > 0) {
            const confidence = Math.min(0.9, matchingKeywords.length / keywords.length * 2);
            affectedControls.push({
              id: control.id,
              name: control.name,
              matchConfidence: confidence,
              reason: `Matched ${matchingKeywords.length} keywords: ${matchingKeywords.slice(0, 3).join(', ')}`,
            });
          }
        }
      }

      // Sort by confidence (highest first)
      affectedControls.sort((a, b) => (b.matchConfidence || 0) - (a.matchConfidence || 0));

      return affectedControls;
    } catch (error) {
      logger.error('[RIF] Error identifying affected controls', error);
      return [];
    }
  }

  /**
   * Generate change summary
   */
  private async generateChangeSummary(
    changeType: 'new' | 'amendment' | 'repeal',
    severity: 'critical' | 'high' | 'medium' | 'low',
    affectedControlsCount: number,
    metadata: { name: string; jurisdiction: string }
  ): Promise<ChangeSummary> {
    const summary: ChangeSummary = {
      changeType,
      severity,
      affectedControls: affectedControlsCount,
      affectedFrameworks: 0, // Will be calculated later
      summary: `${changeType === 'new' ? 'New' : changeType === 'amendment' ? 'Amendment to' : 'Repeal of'} regulation ${metadata.name} in ${metadata.jurisdiction}`,
      recommendations: [],
    };

    if (changeType === 'new') {
      summary.recommendations.push('Review new requirements and assess impact on existing controls');
      summary.recommendations.push('Update affected frameworks and controls');
    } else if (changeType === 'amendment') {
      summary.recommendations.push('Review changes and update affected controls');
      summary.recommendations.push('Verify existing controls still meet requirements');
    } else {
      summary.recommendations.push('Remove or deprecate controls related to repealed regulation');
      summary.recommendations.push('Update compliance documentation');
    }

    if (severity === 'critical' || severity === 'high') {
      summary.recommendations.push('Prioritize implementation and notify stakeholders');
    }

    return summary;
  }

  /**
   * Calculate text similarity (simple Jaccard similarity)
   */
  private calculateTextSimilarity(text1: string, text2: string): number {
    const words1 = new Set(text1.toLowerCase().split(/\s+/));
    const words2 = new Set(text2.toLowerCase().split(/\s+/));
    
    const intersection = new Set([...words1].filter(w => words2.has(w)));
    const union = new Set([...words1, ...words2]);
    
    return intersection.size / union.size;
  }

  /**
   * Detect jurisdiction conflicts (enhanced)
   */
  async detectConflicts(
    jurisdiction: string,
    affectedFrameworks: string[],
    organizationId: string,
    regulationText?: string
  ): Promise<JurisdictionConflict[]> {
    try {
      const conflicts: JurisdictionConflict[] = [];

      // Get existing regulatory changes for the organization
      const existingChanges = await prisma.regulatoryChange.findMany({
        where: {
          organizationId,
          status: { in: ['pending', 'analyzed', 'implemented'] },
        },
      });

      // Define common conflict patterns
      const conflictPatterns: Record<string, Record<string, string>> = {
        'gdpr': {
          'ccpa': 'Data deletion requirements may conflict with retention policies',
          'hipaa': 'Consent requirements may differ from healthcare regulations',
        },
        'hipaa': {
          'gdpr': 'PHI protection may conflict with right to access',
          'sox': 'Audit requirements may overlap with financial controls',
        },
        'pci-dss': {
          'gdpr': 'Data minimization may conflict with fraud detection needs',
        },
        'sox': {
          'gdpr': 'Financial record retention may conflict with data minimization',
        },
      };

      // Check for conflicts with existing regulations
      for (const existingChange of existingChanges) {
        const existingJurisdiction = existingChange.jurisdiction.toLowerCase();
        const newJurisdiction = jurisdiction.toLowerCase();

        // Check direct jurisdiction conflicts
        if (existingJurisdiction !== newJurisdiction) {
          // Check if there are known conflict patterns
          const patterns = conflictPatterns[newJurisdiction];
          if (patterns && patterns[existingJurisdiction]) {
            const conflictId = crypto.randomUUID();
            // Generate AI-powered resolution suggestion
            const resolution = await this.generateConflictResolution(
              jurisdiction,
              existingChange.jurisdiction,
              'requirement_mismatch',
              patterns[existingJurisdiction]
            );
            
            conflicts.push({
              id: conflictId,
              regulation1: jurisdiction,
              regulation2: existingChange.jurisdiction,
              conflictType: 'requirement_mismatch',
              description: patterns[existingJurisdiction],
              resolution: resolution || 'Review both requirements and implement the stricter control. Consider implementing controls that satisfy both regulations where possible.',
              severity: 'high',
              affectedFrameworks: affectedFrameworks,
            });
          }

          // Check for framework overlap (cross-framework conflicts)
          const overlappingFrameworks = existingChange.affectedFrameworks.filter(
            (f: string) => affectedFrameworks.includes(f)
          );

          if (overlappingFrameworks.length > 0) {
            const conflictId = crypto.randomUUID();
            // Generate cross-framework conflict resolution
            const resolution = await this.generateConflictResolution(
              jurisdiction,
              existingChange.jurisdiction,
              'overlap',
              `Both regulations affect frameworks: ${overlappingFrameworks.join(', ')}`
            );
            
            conflicts.push({
              id: conflictId,
              regulation1: jurisdiction,
              regulation2: existingChange.jurisdiction,
              conflictType: 'overlap',
              description: `Both regulations affect frameworks: ${overlappingFrameworks.join(', ')}`,
              resolution: resolution || `Harmonize controls across overlapping frameworks (${overlappingFrameworks.join(', ')}). Create unified controls that satisfy both regulations.`,
              severity: 'medium',
              affectedFrameworks: overlappingFrameworks,
            });
          }
        }

        // Check for contradicting requirements (direct conflicts)
        if (existingChange.extractedRequirements.length > 0) {
          const contradictions = await this.findContradictions(
            existingChange.extractedRequirements,
            affectedFrameworks,
            organizationId
          );

          for (const contradiction of contradictions) {
            const conflictId = crypto.randomUUID();
            // Generate contradiction resolution
            const resolution = await this.generateConflictResolution(
              jurisdiction,
              existingChange.jurisdiction,
              'contradiction',
              contradiction
            );
            
            conflicts.push({
              id: conflictId,
              regulation1: jurisdiction,
              regulation2: existingChange.jurisdiction,
              conflictType: 'contradiction',
              description: contradiction,
              resolution: resolution || 'Seek legal guidance on conflicting requirements. Consider implementing controls for both regulations with clear documentation of the conflict and decision rationale.',
              severity: 'critical',
              affectedFrameworks: affectedFrameworks,
            });
          }
        }

        // Check for implicit conflicts (inferred from context)
        if (regulationText && existingChange.regulationText) {
          const implicitConflicts = await this.detectImplicitConflicts(
            regulationText,
            existingChange.regulationText,
            jurisdiction,
            existingChange.jurisdiction
          );

          for (const implicit of implicitConflicts) {
            const conflictId = crypto.randomUUID();
            conflicts.push({
              id: conflictId,
              regulation1: jurisdiction,
              regulation2: existingChange.jurisdiction,
              conflictType: 'implicit',
              description: implicit.description,
              resolution: implicit.resolution,
              severity: implicit.severity,
              affectedFrameworks: affectedFrameworks,
            });
          }
        }
      }

      // Score conflicts by severity
      conflicts.sort((a, b) => {
        const severityOrder = { critical: 4, high: 3, medium: 2, low: 1 };
        return severityOrder[b.severity] - severityOrder[a.severity];
      });

      // Store conflicts if any found
      if (conflicts.length > 0) {
        // Store conflicts in database (would need a Conflict table in production)
        await prisma.auditLog.create({
          data: {
            action: 'rif.conflicts_detected',
            details: JSON.stringify({
              jurisdiction,
              conflictCount: conflicts.length,
              conflicts,
              timestamp: new Date(),
            }),
            userId: 'system',
            organizationId,
            hash: crypto.randomBytes(16).toString('hex'),
          },
        });

        // Notify stakeholders (in production, would send emails/notifications)
        await this.notifyConflictStakeholders(conflicts, organizationId);

        logger.warn(`[RIF] ${conflicts.length} jurisdiction conflicts detected for ${jurisdiction}`);
      }

      return conflicts;
    } catch (error) {
      logger.error('[RIF] Error detecting conflicts', error);
      return [];
    }
  }

  /**
   * Detect implicit conflicts (inferred from context)
   */
  private async detectImplicitConflicts(
    text1: string,
    text2: string,
    jurisdiction1: string,
    jurisdiction2: string
  ): Promise<Array<{ description: string; resolution: string; severity: 'critical' | 'high' | 'medium' | 'low' }>> {
    const conflicts: Array<{ description: string; resolution: string; severity: 'critical' | 'high' | 'medium' | 'low' }> = [];

    try {
      // Use AI to detect implicit conflicts
      const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

      const prompt = `Analyze these two regulations for implicit conflicts (not explicitly stated but inferred from context):
      
      Regulation 1 (${jurisdiction1}):
      ${text1.substring(0, 2000)}
      
      Regulation 2 (${jurisdiction2}):
      ${text2.substring(0, 2000)}
      
      Return JSON array of conflicts with format:
      [{"description": "...", "resolution": "...", "severity": "critical|high|medium|low"}]`;

      const result = await model.generateContent(prompt);
      const response = result.response.text();

      try {
        const jsonMatch = response.match(/\[[\s\S]*\]/);
        if (jsonMatch) {
          const parsed = JSON.parse(jsonMatch[0]);
          return parsed;
        }
      } catch (parseError) {
        logger.warn('[RIF] Failed to parse implicit conflict detection', parseError);
      }
    } catch (error) {
      logger.error('[RIF] Error detecting implicit conflicts', error);
    }

    return conflicts;
  }

  /**
   * Generate conflict resolution suggestions (AI-powered)
   */
  private async generateConflictResolution(
    regulation1: string,
    regulation2: string,
    conflictType: string,
    description: string
  ): Promise<string> {
    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
      const prompt = `You are a compliance expert. Provide a specific, actionable resolution suggestion for this regulatory conflict:

Regulation 1: ${regulation1}
Regulation 2: ${regulation2}
Conflict Type: ${conflictType}
Description: ${description}

Provide a concise, actionable resolution suggestion (2-3 sentences) that:
1. Addresses the specific conflict
2. Provides concrete steps to resolve it
3. Considers compliance with both regulations where possible

Return only the resolution text, no JSON or formatting.`;

      const result = await model.generateContent(prompt);
      const response = await result.response;
      return response.text().trim();
    } catch (error) {
      logger.warn('[RIF] AI conflict resolution generation failed, using default', error);
      return '';
    }
  }

  /**
   * Notify stakeholders of conflicts
   */
  private async notifyConflictStakeholders(
    conflicts: JurisdictionConflict[],
    organizationId: string
  ): Promise<void> {
    try {
      // Get organization admins
      const admins = await prisma.user.findMany({
        where: {
          organizationId,
          role: 'admin',
        },
      });

      // Send notifications
      for (const admin of admins) {
        try {
          await notificationService.sendNotification(
            admin.id,
            organizationId,
            {
              type: conflicts.some(c => c.severity === 'critical') ? 'critical' : 'warning',
              category: 'rif_conflict',
              title: `Regulatory Conflict Detected: ${conflicts.length} conflict(s)`,
              message: `${conflicts.length} regulatory conflict(s) detected:\n\n${conflicts.slice(0, 3).map(c => 
                `• ${c.severity.toUpperCase()}: ${c.description}\n  Resolution: ${c.resolution}`
              ).join('\n\n')}`,
              link: `/settings/regulatory?conflicts=true`,
              channels: ['email', 'websocket'],
            }
          );
        } catch (error: any) {
          logger.warn(`[RIF] Failed to send conflict notification to ${admin.id}`, error);
        }
      }

      // Log to audit
      await prisma.auditLog.create({
        data: {
          action: 'rif.conflict_notification',
          details: JSON.stringify({
            conflictCount: conflicts.length,
            criticalConflicts: conflicts.filter(c => c.severity === 'critical').length,
            timestamp: new Date(),
          }),
          userId: 'system',
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });
    } catch (error) {
      logger.error('[RIF] Error notifying stakeholders', error);
    }
  }

  /**
   * Bulk conflict analysis
   */
  async bulkConflictAnalysis(
    organizationId: string,
    regulationIds: string[]
  ): Promise<{
    totalConflicts: number;
    conflictsBySeverity: Record<string, number>;
    conflicts: JurisdictionConflict[];
  }> {
    try {
      const allConflicts: JurisdictionConflict[] = [];

      for (const regId of regulationIds) {
        const regulation = await prisma.regulatoryChange.findFirst({
          where: { id: regId, organizationId },
        });

        if (regulation) {
          // Get regulation text from details if available
          let regulationText: string | undefined = (regulation as any).regulationText;
          try {
            // Regulation model has regulationText field directly
            if (!regulationText) {
              regulationText = undefined;
            }
          } catch (parseError) {
            // If details parsing fails, regulationText remains undefined
            logger.warn('[RIF] Could not parse regulation details', parseError);
          }

          const conflicts = await this.detectConflicts(
            regulation.jurisdiction,
            regulation.affectedFrameworks || [],
            organizationId,
            regulationText
          );
          allConflicts.push(...conflicts);
        }
      }

      const conflictsBySeverity = {
        critical: allConflicts.filter(c => c.severity === 'critical').length,
        high: allConflicts.filter(c => c.severity === 'high').length,
        medium: allConflicts.filter(c => c.severity === 'medium').length,
        low: allConflicts.filter(c => c.severity === 'low').length,
      };

      return {
        totalConflicts: allConflicts.length,
        conflictsBySeverity,
        conflicts: allConflicts,
      };
    } catch (error) {
      logger.error('[RIF] Error in bulk conflict analysis', error);
      throw error;
    }
  }

  /**
   * Get conflict history
   */
  async getConflictHistory(
    organizationId: string,
    limit: number = 50
  ): Promise<JurisdictionConflict[]> {
    try {
      const conflictLogs = await prisma.auditLog.findMany({
        where: {
          organizationId,
          action: 'rif.conflicts_detected',
        },
        orderBy: { timestamp: 'desc' },
        take: limit,
      });

      const conflicts: JurisdictionConflict[] = [];
      for (const log of conflictLogs) {
        try {
          const details = JSON.parse(log.details || '{}');
          if (details.conflicts && Array.isArray(details.conflicts)) {
            conflicts.push(...details.conflicts);
          }
        } catch (e) {
          // Skip invalid logs
        }
      }

      return conflicts;
    } catch (error) {
      logger.error('[RIF] Error getting conflict history', error);
      return [];
    }
  }

  /**
   * Resolve conflict
   */
  async resolveConflict(
    conflictId: string,
    organizationId: string,
    resolution: string,
    userId: string
  ): Promise<void> {
    try {
      // In production, would update Conflict table
      // For now, log resolution
      await prisma.auditLog.create({
        data: {
          action: 'rif.conflict_resolved',
          details: JSON.stringify({
            conflictId,
            resolution,
            resolvedAt: new Date(),
            resolvedBy: userId,
          }),
          userId,
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });
    } catch (error) {
      logger.error('[RIF] Error resolving conflict', error);
      throw error;
    }
  }

  /**
   * Find contradicting requirements
   */
  private async findContradictions(
    existingRequirements: string[],
    affectedFrameworks: string[],
    organizationId: string
  ): Promise<string[]> {
    const contradictions: string[] = [];

    // Define contradiction keywords
    const contradictionPairs = [
      { require: 'must retain', conflict: 'must delete' },
      { require: 'shall encrypt', conflict: 'plain text allowed' },
      { require: 'consent required', conflict: 'implied consent' },
      { require: 'minimum retention', conflict: 'maximum retention' },
      { require: 'must notify within 24', conflict: 'notify within 72' },
    ];

    for (const requirement of existingRequirements) {
      const lowerReq = requirement.toLowerCase();

      for (const pair of contradictionPairs) {
        if (lowerReq.includes(pair.require.split(' ')[0]) ||
            lowerReq.includes(pair.conflict.split(' ')[0])) {
          // Check if affected frameworks have conflicting controls
          const frameworks = await prisma.complianceFramework.findMany({
            where: {
              id: { in: affectedFrameworks },
            },
            include: { controls: true },
          });

          for (const framework of frameworks) {
            for (const control of framework.controls) {
              const controlDesc = (control.description || '').toLowerCase();
              if ((lowerReq.includes(pair.require) && controlDesc.includes(pair.conflict)) ||
                  (lowerReq.includes(pair.conflict) && controlDesc.includes(pair.require))) {
                contradictions.push(
                  `Requirement "${requirement.substring(0, 50)}..." contradicts control "${control.name}"`
                );
              }
            }
          }
        }
      }
    }

    return contradictions;
  }

  /**
   * Auto-update controls based on regulatory change (enhanced with approval, rollback, preview)
   */
  async autoUpdateControls(
    regulatoryChangeId: string,
    organizationId: string,
    userId: string,
    options?: {
      requireApproval?: boolean;
      dryRun?: boolean; // Preview mode
      batch?: boolean;
    }
  ): Promise<{
    controlsCreated: number;
    controlsUpdated: number;
    controlsDeprecated: number;
    frameworksAffected: number;
    preview?: any; // For dry-run
    requiresApproval?: boolean;
    approvalId?: string;
    errors?: Array<{ controlId: string; error: string }>;
  }> {
    try {
      // Get regulatory change from database
      const regulatoryChange = await prisma.regulatoryChange.findFirst({
        where: {
          id: regulatoryChangeId,
          organizationId,
        },
      });

      if (!regulatoryChange) {
        throw new Error('Regulatory change not found');
      }

      // DRY-RUN MODE: Generate preview without making changes
      if (options?.dryRun) {
        const preview = await this.generateAutoUpdatePreview(regulatoryChange, organizationId);
        return {
          controlsCreated: preview.controlsToCreate.length,
          controlsUpdated: preview.controlsToUpdate.length,
          controlsDeprecated: preview.controlsToDeprecate.length,
          frameworksAffected: preview.frameworksAffected.length,
          preview,
          requiresApproval: options?.requireApproval !== false,
        };
      }

      // APPROVAL WORKFLOW: Queue for approval if required
      if (options?.requireApproval !== false) {
        const approvalId = await this.queueForApproval(
          regulatoryChangeId,
          organizationId,
          userId,
          regulatoryChange
        );
        return {
          controlsCreated: 0,
          controlsUpdated: 0,
          controlsDeprecated: 0,
          frameworksAffected: 0,
          requiresApproval: true,
          approvalId,
        };
      }

      let controlsCreated = 0;
      let controlsUpdated = 0;
      let controlsDeprecated = 0;
      const affectedFrameworkIds = new Set<string>();
      const errors: Array<{ controlId: string; error: string }> = [];
      const checkpointId = crypto.randomBytes(16).toString('hex');

      // Create checkpoint for rollback
      await this.createCheckpoint(regulatoryChangeId, organizationId, userId);

      // Process auto-generated controls
      const autoControls = regulatoryChange.autoGeneratedControls as any[] || [];

      for (const controlData of autoControls) {
        // Find matching frameworks
        const frameworks = await prisma.complianceFramework.findMany({
          where: {
            organizationId,
            id: { in: regulatoryChange.affectedFrameworks },
          },
          include: { controls: true },
        });

        for (const framework of frameworks) {
          affectedFrameworkIds.add(framework.id);

          // Check if similar control already exists
          const existingControl = framework.controls.find((c: any) =>
            c.name.toLowerCase().includes(controlData.name.toLowerCase().split(':')[0]) ||
            (c.description && c.description.toLowerCase().includes(controlData.description.toLowerCase().substring(0, 50)))
          );

          try {
            if (existingControl) {
              // Update existing control
              await prisma.frameworkControl.update({
                where: { id: existingControl.id },
                data: {
                  description: `${existingControl.description || ''}\n\n[Auto-updated from ${regulatoryChange.regulationName} on ${new Date().toISOString()}]: ${controlData.description}`,
                  updatedAt: new Date(),
                },
              });
              controlsUpdated++;
            } else {
              // Create new control
              await prisma.frameworkControl.create({
                data: {
                  frameworkId: framework.id,
                  name: controlData.name,
                  description: `[Auto-generated from ${regulatoryChange.regulationName} on ${new Date().toISOString()}]: ${controlData.description}`,
                  status: 'Pending',
                  category: controlData.category || 'Regulatory',
                },
              });
              controlsCreated++;
            }
          } catch (controlError: any) {
            errors.push({
              controlId: existingControl?.id || 'new',
              error: controlError.message || 'Failed to create/update control',
            });
            logger.error(`[RIF] Error processing control ${controlData.name}`, controlError);
          }
        }
      }

      // Update regulatory change status
      await prisma.regulatoryChange.update({
        where: { id: regulatoryChangeId },
        data: {
          status: 'implemented',
          updatedAt: new Date(),
        },
      });

      // Store auto-update result with checkpoint
      await prisma.auditLog.create({
        data: {
          action: 'rif.controls_auto_updated',
          details: JSON.stringify({
            regulatoryChangeId,
            regulationName: regulatoryChange.regulationName,
            controlsCreated,
            controlsUpdated,
            controlsDeprecated,
            frameworksAffected: affectedFrameworkIds.size,
            checkpointId,
            errors: errors.length > 0 ? errors : undefined,
            timestamp: new Date(),
          }),
          userId,
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });

      // Notify stakeholders
      await this.notifyAutoUpdateStakeholders(
        organizationId,
        {
          controlsCreated,
          controlsUpdated,
          controlsDeprecated,
          frameworksAffected: affectedFrameworkIds.size,
          regulationName: regulatoryChange.regulationName,
        }
      );

      logger.info(`[RIF] Controls auto-updated for regulation ${regulatoryChangeId}: ${controlsCreated} created, ${controlsUpdated} updated, ${controlsDeprecated} deprecated`);

      return {
        controlsCreated,
        controlsUpdated,
        controlsDeprecated,
        frameworksAffected: affectedFrameworkIds.size,
        errors: errors.length > 0 ? errors : undefined,
      };
    } catch (error: any) {
      logger.error('[RIF] Error auto-updating controls', error);
      
      // Log error with partial success info
      await prisma.auditLog.create({
        data: {
          action: 'rif.auto_update_error',
          details: JSON.stringify({
            regulatoryChangeId,
            error: error.message,
            timestamp: new Date(),
          }),
          userId: userId || 'system',
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      }).catch(() => {
        // Ignore audit log errors
      });

      throw error;
    }
  }

  /**
   * Identify obsolete controls (for repeal/amendment)
   */
  private async identifyObsoleteControls(
    regulatoryChange: any,
    organizationId: string
  ): Promise<Array<{ id: string; name: string; description: string }>> {
    try {
      const frameworks = await prisma.complianceFramework.findMany({
        where: {
          organizationId,
          id: { in: regulatoryChange.affectedFrameworks },
        },
        include: { controls: true },
      });

      const obsolete: Array<{ id: string; name: string; description: string }> = [];

      for (const framework of frameworks) {
        for (const control of framework.controls) {
          // Check if control is related to the repealed/amended regulation
          const controlText = (control.name + ' ' + (control.description || '')).toLowerCase();
          const regulationName = regulatoryChange.regulationName.toLowerCase();
          
          if (controlText.includes(regulationName) || 
              control.description?.includes(regulatoryChange.regulationName)) {
            obsolete.push({
              id: control.id,
              name: control.name,
              description: control.description || '',
            });
          }
        }
      }

      return obsolete;
    } catch (error) {
      logger.error('[RIF] Error identifying obsolete controls', error);
      return [];
    }
  }

  /**
   * Create checkpoint for rollback
   */
  private async createCheckpoint(
    regulatoryChangeId: string,
    organizationId: string,
    userId: string
  ): Promise<string> {
    try {
      // Get current state of affected controls
      const regulatoryChange = await prisma.regulatoryChange.findFirst({
        where: { id: regulatoryChangeId, organizationId },
      });

      if (!regulatoryChange) {
        throw new Error('Regulatory change not found');
      }

      const frameworks = await prisma.complianceFramework.findMany({
        where: {
          organizationId,
          id: { in: regulatoryChange.affectedFrameworks },
        },
        include: { controls: true },
      });

      const checkpoint = {
        regulatoryChangeId,
        timestamp: new Date(),
        controls: frameworks.flatMap(f => f.controls.map(c => ({
          id: c.id,
          name: c.name,
          description: c.description,
          status: c.status,
        }))),
      };

      const checkpointId = crypto.randomUUID();

      // Store checkpoint in audit log
      await prisma.auditLog.create({
        data: {
          action: 'rif.checkpoint_created',
          details: JSON.stringify(checkpoint),
          userId,
          organizationId,
          hash: checkpointId,
        },
      });

      return checkpointId;
    } catch (error) {
      logger.error('[RIF] Error creating checkpoint', error);
      throw error;
    }
  }

  /**
   * Generate preview of auto-update (dry-run)
   */
  private async generateAutoUpdatePreview(
    regulatoryChange: any,
    organizationId: string
  ): Promise<{
    controlsToCreate: Array<{ name: string; description: string; frameworkId: string; frameworkName: string }>;
    controlsToUpdate: Array<{ id: string; name: string; currentDescription: string; newDescription: string }>;
    controlsToDeprecate: Array<{ id: string; name: string; reason: string }>;
    frameworksAffected: Array<{ id: string; name: string }>;
  }> {
    const controlsToCreate: Array<{ name: string; description: string; frameworkId: string; frameworkName: string }> = [];
    const controlsToUpdate: Array<{ id: string; name: string; currentDescription: string; newDescription: string }> = [];
    const controlsToDeprecate: Array<{ id: string; name: string; reason: string }> = [];
    const frameworksAffected: Array<{ id: string; name: string }> = [];

    const frameworks = await prisma.complianceFramework.findMany({
      where: {
        organizationId,
        id: { in: regulatoryChange.affectedFrameworks || [] },
      },
      include: { controls: true },
    });

    for (const framework of frameworks) {
      frameworksAffected.push({ id: framework.id, name: framework.name });

      const autoControls = regulatoryChange.autoGeneratedControls as any[] || [];
      for (const controlData of autoControls) {
        const existingControl = framework.controls.find((c: any) =>
          c.name.toLowerCase().includes(controlData.name.toLowerCase().split(':')[0]) ||
          (c.description && c.description.toLowerCase().includes(controlData.description.toLowerCase().substring(0, 50)))
        );

        if (existingControl) {
          controlsToUpdate.push({
            id: existingControl.id,
            name: existingControl.name,
            currentDescription: existingControl.description || '',
            newDescription: `${existingControl.description || ''}\n\n[Auto-updated from ${regulatoryChange.regulationName}]: ${controlData.description}`,
          });
        } else {
          controlsToCreate.push({
            name: controlData.name,
            description: controlData.description,
            frameworkId: framework.id,
            frameworkName: framework.name,
          });
        }
      }
    }

    // Identify obsolete controls
    const obsolete = await this.identifyObsoleteControls(regulatoryChange, organizationId);
    for (const control of obsolete) {
      controlsToDeprecate.push({
        id: control.id,
        name: control.name,
        reason: `Control is related to repealed/amended regulation: ${regulatoryChange.regulationName}`,
      });
    }

    return {
      controlsToCreate,
      controlsToUpdate,
      controlsToDeprecate,
      frameworksAffected,
    };
  }

  /**
   * Queue for approval
   */
  private async queueForApproval(
    regulatoryChangeId: string,
    organizationId: string,
    userId: string,
    regulatoryChange: any
  ): Promise<string> {
    try {
      const approvalId = crypto.randomUUID();
      
      // Generate preview for approval
      const preview = await this.generateAutoUpdatePreview(regulatoryChange, organizationId);

      await prisma.auditLog.create({
        data: {
          action: 'rif.auto_update_queued',
          details: JSON.stringify({
            approvalId,
            regulatoryChangeId,
            regulationName: regulatoryChange.regulationName,
            preview,
            requestedBy: userId,
            timestamp: new Date(),
            status: 'pending_approval',
          }),
          userId,
          organizationId,
          hash: approvalId,
        },
      });

      // Notify admins for approval
      const admins = await prisma.user.findMany({
        where: { organizationId, role: 'admin' },
      });

      for (const admin of admins) {
        try {
          await notificationService.sendNotification(
            admin.id,
            organizationId,
            {
              type: 'warning',
              category: 'rif_approval',
              title: `Auto-Update Approval Required: ${regulatoryChange.regulationName}`,
              message: `Auto-update for ${regulatoryChange.regulationName} requires approval:\n\n` +
                `• ${preview.controlsToCreate.length} controls to create\n` +
                `• ${preview.controlsToUpdate.length} controls to update\n` +
                `• ${preview.controlsToDeprecate.length} controls to deprecate\n` +
                `• ${preview.frameworksAffected.length} frameworks affected`,
              link: `/settings/regulatory?approvalId=${approvalId}`,
              channels: ['email', 'websocket'],
            }
          );
        } catch (error: any) {
          logger.warn(`[RIF] Failed to send approval notification to ${admin.id}`, error);
        }
      }

      return approvalId;
    } catch (error) {
      logger.error('[RIF] Error queueing for approval', error);
      throw error;
    }
  }

  /**
   * Approve auto-update
   */
  async approveAutoUpdate(
    approvalId: string,
    organizationId: string,
    userId: string
  ): Promise<{
    controlsCreated: number;
    controlsUpdated: number;
    controlsDeprecated: number;
    frameworksAffected: number;
  }> {
    try {
      const approvalLog = await prisma.auditLog.findFirst({
        where: {
          organizationId,
          hash: approvalId,
          action: 'rif.auto_update_queued',
        },
      });

      if (!approvalLog) {
        throw new Error('Approval request not found');
      }

      const approvalDetails = JSON.parse(approvalLog.details || '{}');
      if (approvalDetails.status !== 'pending_approval') {
        throw new Error('Approval request is not pending');
      }

      // Execute the auto-update without requiring approval
      const result = await this.autoUpdateControls(
        approvalDetails.regulatoryChangeId,
        organizationId,
        userId,
        { requireApproval: false, dryRun: false }
      );

      // Update approval status
      await prisma.auditLog.create({
        data: {
          action: 'rif.auto_update_approved',
          details: JSON.stringify({
            approvalId,
            regulatoryChangeId: approvalDetails.regulatoryChangeId,
            approvedBy: userId,
            approvedAt: new Date(),
            result,
          }),
          userId,
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });

      return {
        controlsCreated: result.controlsCreated,
        controlsUpdated: result.controlsUpdated,
        controlsDeprecated: result.controlsDeprecated || 0,
        frameworksAffected: result.frameworksAffected,
      };
    } catch (error) {
      logger.error('[RIF] Error approving auto-update', error);
      throw error;
    }
  }

  /**
   * Rollback auto-update
   */
  async rollbackAutoUpdate(
    regulatoryChangeId: string,
    checkpointId: string,
    organizationId: string,
    userId: string
  ): Promise<{ success: boolean; controlsRestored: number }> {
    try {
      // Get checkpoint
      const checkpointLog = await prisma.auditLog.findFirst({
        where: {
          organizationId,
          hash: checkpointId,
          action: 'rif.checkpoint_created',
        },
      });

      if (!checkpointLog) {
        throw new Error('Checkpoint not found');
      }

      const checkpoint = JSON.parse(checkpointLog.details || '{}');
      let controlsRestored = 0;

      // Restore controls to checkpoint state
      for (const control of checkpoint.controls || []) {
        try {
          await prisma.frameworkControl.update({
            where: { id: control.id },
            data: {
              name: control.name,
              description: control.description,
              status: control.status,
              updatedAt: new Date(),
            },
          });
          controlsRestored++;
        } catch (error: any) {
          logger.warn(`[RIF] Error restoring control ${control.id}: ${error.message}`);
        }
      }

      // Log rollback
      await prisma.auditLog.create({
        data: {
          action: 'rif.auto_update_rolled_back',
          details: JSON.stringify({
            regulatoryChangeId,
            checkpointId,
            controlsRestored,
            timestamp: new Date(),
          }),
          userId,
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Auto-update rolled back for regulation ${regulatoryChangeId}: ${controlsRestored} controls restored`);

      return { success: true, controlsRestored };
    } catch (error) {
      logger.error('[RIF] Error rolling back auto-update', error);
      throw error;
    }
  }

  /**
   * Batch auto-update
   */
  async batchAutoUpdate(
    regulatoryChangeIds: string[],
    organizationId: string,
    userId: string,
    options?: { requireApproval?: boolean; dryRun?: boolean }
  ): Promise<Array<{
    regulatoryChangeId: string;
    success: boolean;
    controlsCreated: number;
    controlsUpdated: number;
    controlsDeprecated: number;
    error?: string;
  }>> {
    try {
      const results: Array<{
        regulatoryChangeId: string;
        success: boolean;
        controlsCreated: number;
        controlsUpdated: number;
        controlsDeprecated: number;
        error?: string;
      }> = [];

      for (const regId of regulatoryChangeIds) {
        try {
          const result = await this.autoUpdateControls(regId, organizationId, userId, options);
          results.push({
            regulatoryChangeId: regId,
            success: true,
            controlsCreated: result.controlsCreated,
            controlsUpdated: result.controlsUpdated,
            controlsDeprecated: result.controlsDeprecated || 0,
          });
        } catch (error: any) {
          results.push({
            regulatoryChangeId: regId,
            success: false,
            controlsCreated: 0,
            controlsUpdated: 0,
            controlsDeprecated: 0,
            error: error.message,
          });
        }
      }

      return results;
    } catch (error) {
      logger.error('[RIF] Error in batch auto-update', error);
      throw error;
    }
  }

  /**
   * Notify stakeholders of auto-update
   */
  private async notifyAutoUpdateStakeholders(
    organizationId: string,
    summary: {
      controlsCreated: number;
      controlsUpdated: number;
      controlsDeprecated: number;
      frameworksAffected: number;
      regulationName: string;
    }
  ): Promise<void> {
    try {
      // In production, would send emails/notifications
      await prisma.auditLog.create({
        data: {
          action: 'rif.auto_update_notification',
          details: JSON.stringify({
            ...summary,
            timestamp: new Date(),
          }),
          userId: 'system',
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });
    } catch (error) {
      logger.error('[RIF] Error notifying stakeholders', error);
    }
  }

  /**
   * Monitor regulatory feeds (enhanced with RSS/API/website monitoring)
   */
  async monitorRegulatoryFeeds(
    organizationId: string,
    feedIds?: string[]
  ): Promise<RegulatoryChange[]> {
    try {
      const changes: RegulatoryChange[] = [];

      // Get registered feeds for organization from database
      let feedsToMonitor: RegulatoryFeed[] = [];
      
      if (feedIds && feedIds.length > 0) {
        // Get specific feeds by ID
        const dbFeeds = await prisma.regulatoryFeed.findMany({
          where: {
            organizationId,
            id: { in: feedIds },
            status: 'active',
          },
        });
        feedsToMonitor = dbFeeds.map((f): RegulatoryFeed => ({
          id: f.id,
          name: f.name,
          url: f.url,
          feedType: f.feedType as 'rss' | 'api' | 'website',
          jurisdiction: f.jurisdiction,
          pollingInterval: f.pollingInterval,
          organizationId: f.organizationId,
          status: f.status as 'active' | 'inactive' | 'error',
        }));
      } else {
        // Get all active feeds for organization
        const dbFeeds = await prisma.regulatoryFeed.findMany({
          where: {
            organizationId,
            status: 'active',
          },
        });
        feedsToMonitor = dbFeeds.map((f): RegulatoryFeed => ({
          id: f.id,
          name: f.name,
          url: f.url,
          feedType: f.feedType as 'rss' | 'api' | 'website',
          jurisdiction: f.jurisdiction,
          pollingInterval: f.pollingInterval,
          organizationId: f.organizationId,
          status: f.status as 'active' | 'inactive' | 'error',
        }));
      }

      // If no custom feeds, use default feeds (for backward compatibility)
      if (feedsToMonitor.length === 0) {
        logger.info(`[RIF] No custom feeds found for organization ${organizationId}, using defaults`);
        const defaultFeeds: RegulatoryFeed[] = [
          { id: 'feed_1', name: 'SEC', url: 'https://www.sec.gov/rss/divisions/corpfin/cfnew.xml', feedType: 'rss', jurisdiction: 'US', pollingInterval: 60, organizationId, status: 'active' },
          { id: 'feed_2', name: 'GDPR', url: 'https://ec.europa.eu/newsroom/just/rss', feedType: 'rss', jurisdiction: 'EU', pollingInterval: 120, organizationId, status: 'active' },
          { id: 'feed_3', name: 'NIST', url: 'https://csrc.nist.gov/CSRC/media/rss-feeds/publications-feed', feedType: 'rss', jurisdiction: 'US', pollingInterval: 180, organizationId, status: 'active' },
          { id: 'feed_4', name: 'ISO', url: 'https://www.iso.org/rss/standards.xml', feedType: 'rss', jurisdiction: 'Global', pollingInterval: 240, organizationId, status: 'active' },
        ];
        feedsToMonitor = defaultFeeds;
      }

      const processedItems = new Set<string>(); // For deduplication

      // Monitor each feed
      for (const feed of feedsToMonitor) {
        try {
          let feedItems: any[] = [];

          if (feed.feedType === 'rss') {
            feedItems = await this.parseRSSFeed(feed, organizationId);
          } else if (feed.feedType === 'api') {
            feedItems = await this.monitorAPIEndpoint(feed, organizationId);
          } else if (feed.feedType === 'website') {
            feedItems = await this.monitorWebsiteChanges(feed, organizationId);
          }

          // Deduplicate items
          for (const item of feedItems) {
            const itemHash = crypto.createHash('sha256').update(item.url || item.title || '').digest('hex');
            if (!processedItems.has(itemHash)) {
              processedItems.add(itemHash);

              // Check if this is a new regulation
              const regulation = await this.processFeedItem(item, feed, organizationId);
              if (regulation) {
                changes.push(regulation);
              }
            }
          }

          // Update feed status
          await this.updateFeedStatus(feed.id, organizationId, 'active', null);
        } catch (error: any) {
          logger.error(`[RIF] Error monitoring feed ${feed.name}`, error);
          await this.updateFeedStatus(feed.id, organizationId, 'error', error.message);
          
          // Retry logic (in production, would implement exponential backoff)
          if (feed.lastError && feed.lastError.includes('timeout')) {
            // Retry after delay
            setTimeout(() => {
              this.monitorRegulatoryFeeds(organizationId, [feed.id]).catch(() => {});
            }, feed.pollingInterval * 60 * 1000);
          }
        }
      }

      // Log monitoring activity
      await prisma.auditLog.create({
        data: {
          action: 'rif.feeds_monitored',
          details: JSON.stringify({
            feedsChecked: feedsToMonitor.length,
            changesFound: changes.length,
            timestamp: new Date(),
          }),
          userId: 'system',
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Regulatory feeds monitored: ${changes.length} changes found from ${feedsToMonitor.length} feeds`);

      return changes;
    } catch (error) {
      logger.error('[RIF] Error monitoring regulatory feeds', error);
      return [];
    }
  }

  /**
   * Parse RSS feed
   */
  private async parseRSSFeed(
    feed: RegulatoryFeed,
    organizationId: string
  ): Promise<Array<{ title: string; url: string; description: string; published: Date }>> {
    try {
      // SECURITY: SSRF Protection - Validate URL before fetching
      const { isUrlSafe } = await import('../../utils/urlValidator');
      if (!isUrlSafe(feed.url)) {
        throw new Error('Feed URL is not allowed for security reasons (SSRF protection)');
      }

      const response = await axios.get(feed.url, {
        timeout: 30000,
        headers: {
          'User-Agent': 'ComplyEasyAI-RIF/1.0',
          ...(feed.authentication?.type === 'api_key' && feed.authentication.credentials?.apiKey
            ? { 'Authorization': `Bearer ${feed.authentication.credentials.apiKey}` }
            : {}),
        },
      });

      // Simple RSS parsing (in production, would use rss-parser library)
      const xml = response.data;
      const items: Array<{ title: string; url: string; description: string; published: Date }> = [];

      // Extract items from RSS XML
      const itemMatches = xml.matchAll(/<item>([\s\S]*?)<\/item>/gi);
      for (const match of itemMatches) {
        const itemXml = match[1];
        const titleMatch = itemXml.match(/<title>(.*?)<\/title>/i);
        const linkMatch = itemXml.match(/<link>(.*?)<\/link>/i);
        const descMatch = itemXml.match(/<description>(.*?)<\/description>/i);
        const pubMatch = itemXml.match(/<pubDate>(.*?)<\/pubDate>/i);

        if (titleMatch && linkMatch) {
          items.push({
            title: titleMatch[1].trim(),
            url: linkMatch[1].trim(),
            description: descMatch ? descMatch[1].trim() : '',
            published: pubMatch ? new Date(pubMatch[1]) : new Date(),
          });
        }
      }

      return items.slice(0, 20); // Limit to 20 items per feed
    } catch (error: any) {
      logger.error(`[RIF] Error parsing RSS feed ${feed.name}`, error);
      throw error;
    }
  }

  /**
   * Monitor API endpoint
   */
  private async monitorAPIEndpoint(
    feed: RegulatoryFeed,
    organizationId: string
  ): Promise<Array<{ title: string; url: string; description: string; published: Date }>> {
    try {
      // SECURITY: SSRF Protection - Validate URL before fetching
      const { isUrlSafe } = await import('../../utils/urlValidator');
      if (!isUrlSafe(feed.url)) {
        throw new Error('Feed URL is not allowed for security reasons (SSRF protection)');
      }

      const headers: any = {
        'User-Agent': 'ComplyEasyAI-RIF/1.0',
      };

      // Handle authentication
      if (feed.authentication) {
        if (feed.authentication.type === 'api_key') {
          headers['X-API-Key'] = feed.authentication.credentials?.apiKey;
        } else if (feed.authentication.type === 'oauth') {
          headers['Authorization'] = `Bearer ${feed.authentication.credentials?.accessToken}`;
        } else if (feed.authentication.type === 'basic') {
          const auth = Buffer.from(`${feed.authentication.credentials?.username}:${feed.authentication.credentials?.password}`).toString('base64');
          headers['Authorization'] = `Basic ${auth}`;
        }
      }

      const response = await axios.get(feed.url, {
        timeout: 30000,
        headers,
      });

      // Parse API response (assumes JSON array of items)
      const items = Array.isArray(response.data) ? response.data : (response.data.items || []);
      
      return items.map((item: any) => ({
        title: item.title || item.name || 'Untitled',
        url: item.url || item.link || feed.url,
        description: item.description || item.summary || '',
        published: item.published ? new Date(item.published) : new Date(),
      })).slice(0, 20);
    } catch (error: any) {
      logger.error(`[RIF] Error monitoring API endpoint ${feed.name}`, error);
      throw error;
    }
  }

  /**
   * Monitor website changes
   */
  private async monitorWebsiteChanges(
    feed: RegulatoryFeed,
    organizationId: string
  ): Promise<Array<{ title: string; url: string; description: string; published: Date }>> {
    try {
      // SECURITY: SSRF Protection - Validate URL before fetching
      const { isUrlSafe } = await import('../../utils/urlValidator');
      if (!isUrlSafe(feed.url)) {
        throw new Error('Feed URL is not allowed for security reasons (SSRF protection)');
      }

      const response = await axios.get(feed.url, {
        timeout: 30000,
        headers: {
          'User-Agent': 'ComplyEasyAI-RIF/1.0',
        },
      });

      // Calculate content hash to detect changes
      const contentHash = crypto.createHash('sha256').update(response.data).digest('hex');

      // Get last known hash (in production, would be from Feed table)
      const lastHash = feed.lastError || ''; // Reusing lastError field for last hash

      if (contentHash === lastHash) {
        return []; // No changes
      }

      // Extract text from HTML (simple extraction)
      const html = response.data;
      const titleMatch = html.match(/<title>(.*?)<\/title>/i);
      const textContent = html.replace(/<[^>]*>/g, ' ').substring(0, 1000);

      return [{
        title: titleMatch ? titleMatch[1] : 'Website Updated',
        url: feed.url,
        description: textContent,
        published: new Date(),
      }];
    } catch (error: any) {
      logger.error(`[RIF] Error monitoring website ${feed.name}`, error);
      throw error;
    }
  }

  /**
   * Process feed item into regulation
   */
  private async processFeedItem(
    item: { title: string; url: string; description: string; published: Date },
    feed: RegulatoryFeed,
    organizationId: string
  ): Promise<RegulatoryChange | null> {
    try {
      // Check if this looks like a regulation
      const isRegulation = this.isRegulatoryContent(item.title, item.description);
      if (!isRegulation) {
        return null;
      }

      // Fetch full content if URL provided
      let fullText = item.description;
      if (item.url) {
        try {
          // SECURITY: SSRF Protection - Validate URL before fetching
          const { isUrlSafe } = await import('../../utils/urlValidator');
          if (!isUrlSafe(item.url)) {
            logger.warn(`[RIF] Blocked SSRF attempt: ${item.url}`);
            // Use description if URL is not safe
            return null;
          }

          const response = await axios.get(item.url, { timeout: 30000 });
          fullText = response.data;
        } catch (e) {
          // Use description if URL fetch fails
        }
      }

      // Ingest as regulation and link to feed
      const regulation = await this.ingestRegulation(
        organizationId,
        { text: fullText },
        {
          name: item.title,
          jurisdiction: feed.jurisdiction,
          effectiveDate: item.published,
          source: item.url || feed.url,
          feedId: feed.id, // Link to feed
        },
        'system'
      );

      return regulation;
    } catch (error) {
      logger.error('[RIF] Error processing feed item', error);
      return null;
    }
  }

  /**
   * Check if content is regulatory
   */
  private isRegulatoryContent(title: string, description: string): boolean {
    const text = (title + ' ' + description).toLowerCase();
    const regulatoryKeywords = [
      'regulation', 'compliance', 'requirement', 'standard', 'guideline',
      'policy', 'law', 'act', 'directive', 'framework', 'control',
    ];
    return regulatoryKeywords.some(keyword => text.includes(keyword));
  }

  /**
   * Update feed status
   */
  private async updateFeedStatus(
    feedId: string,
    organizationId: string,
    status: 'active' | 'paused' | 'error',
    lastError: string | null
  ): Promise<void> {
    try {
      // Update Feed table in database
      await prisma.regulatoryFeed.updateMany({
        where: {
          id: feedId,
          organizationId,
        },
        data: {
          status,
          lastPolledAt: new Date(),
          lastError: lastError || undefined,
          errorCount: lastError ? { increment: 1 } : undefined,
          updatedAt: new Date(),
        },
      });

      // Also log to audit log
      await prisma.auditLog.create({
        data: {
          action: 'rif.feed_status_updated',
          details: JSON.stringify({
            feedId,
            status,
            lastError,
            lastChecked: new Date(),
          }),
          userId: 'system',
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });
    } catch (error) {
      logger.error('[RIF] Error updating feed status', error);
    }
  }

  /**
   * Add new feed (Production-ready: stores in database)
   */
  async addFeed(
    organizationId: string,
    feed: {
      name: string;
      url: string;
      feedType: 'rss' | 'api' | 'website';
      jurisdiction: string;
      pollingInterval: number;
      authentication?: {
        type: 'api_key' | 'oauth' | 'basic';
        credentials?: any;
      };
    },
    userId: string
  ): Promise<RegulatoryFeed> {
    try {
      // Store in database
      const dbFeed = await prisma.regulatoryFeed.create({
        data: {
          organizationId,
          name: feed.name,
          url: feed.url,
          feedType: feed.feedType,
          jurisdiction: feed.jurisdiction,
          pollingInterval: feed.pollingInterval,
          status: 'active',
          metadata: feed.authentication ? { authentication: feed.authentication } : undefined,
        },
      });

      const newFeed: RegulatoryFeed = {
        id: dbFeed.id,
        name: dbFeed.name,
        url: dbFeed.url,
        feedType: dbFeed.feedType as 'rss' | 'api' | 'website',
        jurisdiction: dbFeed.jurisdiction,
        pollingInterval: dbFeed.pollingInterval,
        organizationId: dbFeed.organizationId,
        status: dbFeed.status as 'active' | 'inactive' | 'error',
      };

      // Log to audit log
      await prisma.auditLog.create({
        data: {
          action: 'rif.feed_added',
          details: JSON.stringify(newFeed),
          userId,
          organizationId,
          hash: dbFeed.id,
        },
      });

      logger.info(`[RIF] Feed added: ${feed.name} (${feed.feedType})`);

      return newFeed;
    } catch (error) {
      logger.error('[RIF] Error adding feed', error);
      throw error;
    }
  }

  /**
   * Remove feed (Production-ready: deletes from database)
   */
  async removeFeed(
    feedId: string,
    organizationId: string,
    userId: string
  ): Promise<void> {
    try {
      // Delete from database
      await prisma.regulatoryFeed.deleteMany({
        where: {
          id: feedId,
          organizationId,
        },
      });

      // Log to audit log
      await prisma.auditLog.create({
        data: {
          action: 'rif.feed_removed',
          details: JSON.stringify({ feedId }),
          userId,
          organizationId,
          hash: crypto.randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Feed removed: ${feedId}`);
    } catch (error) {
      logger.error('[RIF] Error removing feed', error);
      throw error;
    }
  }

  /**
   * Get all feeds for organization (Production-ready: queries database)
   */
  async getFeeds(organizationId: string): Promise<RegulatoryFeed[]> {
    try {
      const dbFeeds = await prisma.regulatoryFeed.findMany({
        where: { organizationId },
        orderBy: { createdAt: 'desc' },
      });

      return dbFeeds.map((f): RegulatoryFeed => ({
        id: f.id,
        name: f.name,
        url: f.url,
        feedType: f.feedType as 'rss' | 'api' | 'website',
        jurisdiction: f.jurisdiction,
        pollingInterval: f.pollingInterval,
        organizationId: f.organizationId,
        status: f.status as 'active' | 'inactive' | 'error',
      }));
    } catch (error) {
      logger.error('[RIF] Error getting feeds', error);
      throw error;
    }
  }

  /**
   * Update feed (Production-ready: updates database)
   */
  async updateFeed(
    feedId: string,
    organizationId: string,
    updates: {
      name?: string;
      url?: string;
      feedType?: 'rss' | 'api' | 'website';
      jurisdiction?: string;
      pollingInterval?: number;
      status?: 'active' | 'paused' | 'error';
    },
    userId: string
  ): Promise<RegulatoryFeed> {
    try {
      const dbFeed = await prisma.regulatoryFeed.updateMany({
        where: {
          id: feedId,
          organizationId,
        },
        data: {
          ...updates,
          updatedAt: new Date(),
        },
      });

      if (dbFeed.count === 0) {
        throw new Error('Feed not found');
      }

      const updatedFeed = await prisma.regulatoryFeed.findFirst({
        where: { id: feedId, organizationId },
      });

      if (!updatedFeed) {
        throw new Error('Feed not found after update');
      }

      // Log to audit log
      await prisma.auditLog.create({
        data: {
          action: 'rif.feed_updated',
          details: JSON.stringify({ feedId, updates }),
          userId,
          organizationId,
          hash: feedId,
        },
      });

      logger.info(`[RIF] Feed updated: ${feedId}`);

      return {
        id: updatedFeed.id,
        name: updatedFeed.name,
        url: updatedFeed.url,
        feedType: updatedFeed.feedType as 'rss' | 'api' | 'website',
        jurisdiction: updatedFeed.jurisdiction,
        pollingInterval: updatedFeed.pollingInterval,
        organizationId: updatedFeed.organizationId,
        status: updatedFeed.status as 'active' | 'inactive' | 'error',
      };
    } catch (error) {
      logger.error('[RIF] Error updating feed', error);
      throw error;
    }
  }

  /**
   * Get feed status dashboard
   */
  async getFeedStatusDashboard(organizationId: string): Promise<{
    totalFeeds: number;
    activeFeeds: number;
    errorFeeds: number;
    lastChecked: Date;
    feeds: Array<{
      id: string;
      name: string;
      status: string;
      lastChecked?: Date;
      lastError?: string;
    }>;
  }> {
    try {
      // In production, would query Feed table
      const feedLogs = await prisma.auditLog.findMany({
        where: {
          organizationId,
          action: { in: ['rif.feed_added', 'rif.feed_status_updated'] },
        },
        orderBy: { timestamp: 'desc' },
        take: 100,
      });

      const feeds: Map<string, any> = new Map();
      for (const log of feedLogs) {
        try {
          const details = JSON.parse(log.details || '{}');
          if (details.id) {
            feeds.set(details.id, {
              ...details,
              lastChecked: log.timestamp,
            });
          }
        } catch (e) {
          // Skip invalid logs
        }
      }

      const feedArray = Array.from(feeds.values());
      const activeFeeds = feedArray.filter(f => f.status === 'active').length;
      const errorFeeds = feedArray.filter(f => f.status === 'error').length;

      return {
        totalFeeds: feedArray.length,
        activeFeeds,
        errorFeeds,
        lastChecked: new Date(),
        feeds: feedArray,
      };
    } catch (error) {
      logger.error('[RIF] Error getting feed status dashboard', error);
      return {
        totalFeeds: 0,
        activeFeeds: 0,
        errorFeeds: 0,
        lastChecked: new Date(),
        feeds: [],
      };
    }
  }

  /**
   * Get regulatory changes for organization
   */
  async getRegulatoryChanges(
    organizationId: string,
    status?: string
  ): Promise<RegulatoryChange[]> {
    try {
      const changes = await prisma.regulatoryChange.findMany({
        where: {
          organizationId,
          ...(status && { status }),
        },
        orderBy: { createdAt: 'desc' },
      });

      return changes.map((c: any) => ({
        id: c.id,
        regulationName: c.regulationName,
        jurisdiction: c.jurisdiction,
        effectiveDate: c.effectiveDate,
        changeType: c.changeType,
        affectedFrameworks: c.affectedFrameworks,
        extractedRequirements: c.extractedRequirements,
        autoGeneratedControls: c.autoGeneratedControls,
        status: c.status,
      }));
    } catch (error) {
      logger.error('[RIF] Error getting regulatory changes', error);
      return [];
    }
  }
}

export default new RegulatoryIntelligenceFabricService();

