/**
 * Regulatory Intelligence Fabric (RIF) Service
 * 
 * Features:
 * - Real-time regulatory NLP ingestion
 * - Automatic control updates based on new regulations
 * - Jurisdiction conflict detection
 * - Regulatory change notifications
 * - Framework auto-adaptation
 */

import prisma from '../../config/database';
import logger from '../../config/logger';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export interface RegulatoryChange {
  id: string;
  regulationName: string;
  jurisdiction: string;
  effectiveDate: Date;
  changeType: 'new' | 'amendment' | 'repeal';
  affectedFrameworks: string[];
  extractedRequirements: string[];
  autoGeneratedControls?: any[];
  status: 'pending' | 'analyzed' | 'implemented' | 'conflict';
}

export interface JurisdictionConflict {
  id: string;
  regulation1: string;
  regulation2: string;
  conflictType: 'contradiction' | 'overlap' | 'requirement_mismatch';
  description: string;
  resolution?: string;
}

class RegulatoryIntelligenceFabricService {
  /**
   * Ingest new regulatory document
   */
  async ingestRegulation(
    organizationId: string,
    regulationText: string,
    metadata: {
      name: string;
      jurisdiction: string;
      effectiveDate: Date;
      source?: string;
    },
    userId: string
  ): Promise<RegulatoryChange> {
    try {
      // Use AI to extract requirements
      const extractedRequirements = await this.extractRequirements(regulationText);

      // Map to existing frameworks
      const affectedFrameworks = await this.mapToFrameworks(
        extractedRequirements,
        organizationId
      );

      // Generate controls automatically
      const autoGeneratedControls = await this.generateControls(
        extractedRequirements,
        organizationId
      );

      // Check for jurisdiction conflicts
      const conflicts = await this.detectConflicts(
        metadata.jurisdiction,
        affectedFrameworks,
        organizationId
      );

      const regulatoryChange: RegulatoryChange = {
        id: `reg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        regulationName: metadata.name,
        jurisdiction: metadata.jurisdiction,
        effectiveDate: metadata.effectiveDate,
        changeType: 'new',
        affectedFrameworks,
        extractedRequirements,
        autoGeneratedControls,
        status: conflicts.length > 0 ? 'conflict' : 'analyzed',
      };

      // Store regulatory change
      await prisma.auditLog.create({
        data: {
          action: 'rif.regulation_ingested',
          details: JSON.stringify(regulatoryChange),
          userId,
          organizationId,
          hash: require('crypto').randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Regulation ingested: ${regulatoryChange.id}`);

      return regulatoryChange;
    } catch (error) {
      logger.error('[RIF] Error ingesting regulation', error);
      throw error;
    }
  }

  /**
   * Extract requirements from regulatory text using NLP
   */
  private async extractRequirements(regulationText: string): Promise<string[]> {
    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

      const prompt = `Extract compliance requirements from the following regulatory text.
      Return a JSON array of requirement strings, each describing a specific compliance obligation.

      Regulatory Text:
      ${regulationText.substring(0, 5000)} // Limit to avoid token limits

      Return format:
      ["Requirement 1", "Requirement 2", ...]`;

      const result = await model.generateContent(prompt);
      const response = result.response.text();

      // Parse JSON response
      try {
        const jsonMatch = response.match(/\[[\s\S]*\]/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]);
        }
      } catch (parseError) {
        logger.warn('[RIF] Failed to parse AI response as JSON', parseError);
      }

      // Fallback: simple extraction
      const requirements: string[] = [];
      const sentences = regulationText.split(/[.!?]+/);
      for (const sentence of sentences) {
        if (sentence.toLowerCase().includes('must') || 
            sentence.toLowerCase().includes('shall') ||
            sentence.toLowerCase().includes('required')) {
          requirements.push(sentence.trim());
        }
      }

      return requirements.slice(0, 20); // Limit to 20 requirements
    } catch (error) {
      logger.error('[RIF] Error extracting requirements', error);
      return [];
    }
  }

  /**
   * Map requirements to existing frameworks
   */
  private async mapToFrameworks(
    requirements: string[],
    organizationId: string
  ): Promise<string[]> {
    const frameworks = await prisma.complianceFramework.findMany({
      where: { organizationId },
      select: { id: true, name: true },
    });

    // Simple mapping logic (can be enhanced with ML)
    const affectedFrameworkIds: string[] = [];

    for (const requirement of requirements) {
      const lowerReq = requirement.toLowerCase();

      // Check for framework keywords
      for (const framework of frameworks) {
        const frameworkName = framework.name.toLowerCase();
        
        if (lowerReq.includes('soc') && frameworkName.includes('soc')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        } else if (lowerReq.includes('gdpr') && frameworkName.includes('gdpr')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        } else if (lowerReq.includes('hipaa') && frameworkName.includes('hipaa')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        }
      }
    }

    return affectedFrameworkIds;
  }

  /**
   * Generate controls from requirements
   */
  private async generateControls(
    requirements: string[],
    organizationId: string
  ): Promise<any[]> {
    const controls: any[] = [];

    for (const requirement of requirements.slice(0, 10)) { // Limit to 10 controls
      controls.push({
        name: `Control for: ${requirement.substring(0, 50)}...`,
        description: requirement,
        status: 'Pending',
        autoGenerated: true,
      });
    }

    return controls;
  }

  /**
   * Detect jurisdiction conflicts
   */
  async detectConflicts(
    jurisdiction: string,
    affectedFrameworks: string[],
    organizationId: string
  ): Promise<JurisdictionConflict[]> {
    const conflicts: JurisdictionConflict[] = [];

    // Get existing regulations for the organization
    // In production, this would query a regulations table
    // For now, return empty array

    return conflicts;
  }

  /**
   * Auto-update controls based on regulatory change
   */
  async autoUpdateControls(
    regulatoryChangeId: string,
    organizationId: string,
    userId: string
  ): Promise<{
    controlsCreated: number;
    controlsUpdated: number;
    frameworksAffected: number;
  }> {
    try {
      // Get regulatory change
      // In production, query from dedicated table
      // For now, simulate

      const controlsCreated = 0;
      const controlsUpdated = 0;
      const frameworksAffected = 0;

      await prisma.auditLog.create({
        data: {
          action: 'rif.controls_auto_updated',
          details: JSON.stringify({
            regulatoryChangeId,
            controlsCreated,
            controlsUpdated,
            frameworksAffected,
          }),
          userId,
          organizationId,
          hash: require('crypto').randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Controls auto-updated for regulation ${regulatoryChangeId}`);

      return {
        controlsCreated,
        controlsUpdated,
        frameworksAffected,
      };
    } catch (error) {
      logger.error('[RIF] Error auto-updating controls', error);
      throw error;
    }
  }

  /**
   * Monitor regulatory feeds (can be called periodically)
   */
  async monitorRegulatoryFeeds(organizationId: string): Promise<RegulatoryChange[]> {
    // In production, this would:
    // 1. Connect to regulatory RSS feeds
    // 2. Monitor government websites
    // 3. Use web scraping or APIs
    // 4. Ingest new regulations automatically

    // For now, return empty array
    return [];
  }
}

export default new RegulatoryIntelligenceFabricService();

