/**
 * Regulatory Intelligence Fabric (RIF) Service
 * 
 * Features:
 * - Real-time regulatory NLP ingestion
 * - Automatic control updates based on new regulations
 * - Jurisdiction conflict detection
 * - Regulatory change notifications
 * - Framework auto-adaptation
 */

import prisma from '../../config/database';
import logger from '../../config/logger';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export interface RegulatoryChange {
  id: string;
  regulationName: string;
  jurisdiction: string;
  effectiveDate: Date;
  changeType: 'new' | 'amendment' | 'repeal';
  affectedFrameworks: string[];
  extractedRequirements: string[];
  autoGeneratedControls?: any[];
  status: 'pending' | 'analyzed' | 'implemented' | 'conflict';
}

export interface JurisdictionConflict {
  id: string;
  regulation1: string;
  regulation2: string;
  conflictType: 'contradiction' | 'overlap' | 'requirement_mismatch';
  description: string;
  resolution?: string;
}

class RegulatoryIntelligenceFabricService {
  /**
   * Ingest new regulatory document
   */
  async ingestRegulation(
    organizationId: string,
    regulationText: string,
    metadata: {
      name: string;
      jurisdiction: string;
      effectiveDate: Date;
      source?: string;
    },
    userId: string
  ): Promise<RegulatoryChange> {
    try {
      // Use AI to extract requirements
      const extractedRequirements = await this.extractRequirements(regulationText);

      // Map to existing frameworks
      const affectedFrameworks = await this.mapToFrameworks(
        extractedRequirements,
        organizationId
      );

      // Generate controls automatically
      const autoGeneratedControls = await this.generateControls(
        extractedRequirements,
        organizationId
      );

      // Check for jurisdiction conflicts
      const conflicts = await this.detectConflicts(
        metadata.jurisdiction,
        affectedFrameworks,
        organizationId
      );

      const regulatoryChange: RegulatoryChange = {
        id: `reg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        regulationName: metadata.name,
        jurisdiction: metadata.jurisdiction,
        effectiveDate: metadata.effectiveDate,
        changeType: 'new',
        affectedFrameworks,
        extractedRequirements,
        autoGeneratedControls,
        status: conflicts.length > 0 ? 'conflict' : 'analyzed',
      };

      // Store regulatory change
      await prisma.auditLog.create({
        data: {
          action: 'rif.regulation_ingested',
          details: JSON.stringify(regulatoryChange),
          userId,
          organizationId,
          hash: require('crypto').randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Regulation ingested: ${regulatoryChange.id}`);

      return regulatoryChange;
    } catch (error) {
      logger.error('[RIF] Error ingesting regulation', error);
      throw error;
    }
  }

  /**
   * Extract requirements from regulatory text using NLP
   */
  private async extractRequirements(regulationText: string): Promise<string[]> {
    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

      const prompt = `Extract compliance requirements from the following regulatory text.
      Return a JSON array of requirement strings, each describing a specific compliance obligation.

      Regulatory Text:
      ${regulationText.substring(0, 5000)} // Limit to avoid token limits

      Return format:
      ["Requirement 1", "Requirement 2", ...]`;

      const result = await model.generateContent(prompt);
      const response = result.response.text();

      // Parse JSON response
      try {
        const jsonMatch = response.match(/\[[\s\S]*\]/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]);
        }
      } catch (parseError) {
        logger.warn('[RIF] Failed to parse AI response as JSON', parseError);
      }

      // Fallback: simple extraction
      const requirements: string[] = [];
      const sentences = regulationText.split(/[.!?]+/);
      for (const sentence of sentences) {
        if (sentence.toLowerCase().includes('must') || 
            sentence.toLowerCase().includes('shall') ||
            sentence.toLowerCase().includes('required')) {
          requirements.push(sentence.trim());
        }
      }

      return requirements.slice(0, 20); // Limit to 20 requirements
    } catch (error) {
      logger.error('[RIF] Error extracting requirements', error);
      return [];
    }
  }

  /**
   * Map requirements to existing frameworks
   */
  private async mapToFrameworks(
    requirements: string[],
    organizationId: string
  ): Promise<string[]> {
    const frameworks = await prisma.complianceFramework.findMany({
      where: { organizationId },
      select: { id: true, name: true },
    });

    // Simple mapping logic (can be enhanced with ML)
    const affectedFrameworkIds: string[] = [];

    for (const requirement of requirements) {
      const lowerReq = requirement.toLowerCase();

      // Check for framework keywords
      for (const framework of frameworks) {
        const frameworkName = framework.name.toLowerCase();
        
        if (lowerReq.includes('soc') && frameworkName.includes('soc')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        } else if (lowerReq.includes('gdpr') && frameworkName.includes('gdpr')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        } else if (lowerReq.includes('hipaa') && frameworkName.includes('hipaa')) {
          if (!affectedFrameworkIds.includes(framework.id)) {
            affectedFrameworkIds.push(framework.id);
          }
        }
      }
    }

    return affectedFrameworkIds;
  }

  /**
   * Generate controls from requirements
   */
  private async generateControls(
    requirements: string[],
    organizationId: string
  ): Promise<any[]> {
    const controls: any[] = [];

    for (const requirement of requirements.slice(0, 10)) { // Limit to 10 controls
      controls.push({
        name: `Control for: ${requirement.substring(0, 50)}...`,
        description: requirement,
        status: 'Pending',
        autoGenerated: true,
      });
    }

    return controls;
  }

  /**
   * Detect jurisdiction conflicts
   */
  async detectConflicts(
    jurisdiction: string,
    affectedFrameworks: string[],
    organizationId: string
  ): Promise<JurisdictionConflict[]> {
    try {
      const conflicts: JurisdictionConflict[] = [];

      // Get existing regulatory changes for the organization
      const existingChanges = await prisma.regulatoryChange.findMany({
        where: {
          organizationId,
          status: { in: ['pending', 'analyzed', 'implemented'] },
        },
      });

      // Define common conflict patterns
      const conflictPatterns: Record<string, Record<string, string>> = {
        'gdpr': {
          'ccpa': 'Data deletion requirements may conflict with retention policies',
          'hipaa': 'Consent requirements may differ from healthcare regulations',
        },
        'hipaa': {
          'gdpr': 'PHI protection may conflict with right to access',
          'sox': 'Audit requirements may overlap with financial controls',
        },
        'pci-dss': {
          'gdpr': 'Data minimization may conflict with fraud detection needs',
        },
        'sox': {
          'gdpr': 'Financial record retention may conflict with data minimization',
        },
      };

      // Check for conflicts with existing regulations
      for (const existingChange of existingChanges) {
        const existingJurisdiction = existingChange.jurisdiction.toLowerCase();
        const newJurisdiction = jurisdiction.toLowerCase();

        // Check direct jurisdiction conflicts
        if (existingJurisdiction !== newJurisdiction) {
          // Check if there are known conflict patterns
          const patterns = conflictPatterns[newJurisdiction];
          if (patterns && patterns[existingJurisdiction]) {
            conflicts.push({
              id: `conflict_${Date.now()}_${require('crypto').randomBytes(4).toString('hex')}`,
              regulation1: jurisdiction,
              regulation2: existingChange.jurisdiction,
              conflictType: 'requirement_mismatch',
              description: patterns[existingJurisdiction],
              resolution: 'Review both requirements and implement the stricter control',
            });
          }

          // Check for framework overlap
          const overlappingFrameworks = existingChange.affectedFrameworks.filter(
            (f: string) => affectedFrameworks.includes(f)
          );

          if (overlappingFrameworks.length > 0) {
            conflicts.push({
              id: `conflict_${Date.now()}_${require('crypto').randomBytes(4).toString('hex')}`,
              regulation1: jurisdiction,
              regulation2: existingChange.jurisdiction,
              conflictType: 'overlap',
              description: `Both regulations affect frameworks: ${overlappingFrameworks.join(', ')}`,
              resolution: 'Harmonize controls across overlapping frameworks',
            });
          }
        }

        // Check for contradicting requirements based on extracted requirements
        if (existingChange.extractedRequirements.length > 0) {
          const contradictions = await this.findContradictions(
            existingChange.extractedRequirements,
            affectedFrameworks,
            organizationId
          );

          for (const contradiction of contradictions) {
            conflicts.push({
              id: `conflict_${Date.now()}_${require('crypto').randomBytes(4).toString('hex')}`,
              regulation1: jurisdiction,
              regulation2: existingChange.jurisdiction,
              conflictType: 'contradiction',
              description: contradiction,
              resolution: 'Seek legal guidance on conflicting requirements',
            });
          }
        }
      }

      // Store conflicts if any found
      if (conflicts.length > 0) {
        await prisma.auditLog.create({
          data: {
            action: 'rif.conflicts_detected',
            details: JSON.stringify({
              jurisdiction,
              conflictCount: conflicts.length,
              conflicts,
            }),
            userId: 'system',
            organizationId,
            hash: require('crypto').randomBytes(16).toString('hex'),
          },
        });

        logger.warn(`[RIF] ${conflicts.length} jurisdiction conflicts detected for ${jurisdiction}`);
      }

      return conflicts;
    } catch (error) {
      logger.error('[RIF] Error detecting conflicts', error);
      return [];
    }
  }

  /**
   * Find contradicting requirements
   */
  private async findContradictions(
    existingRequirements: string[],
    affectedFrameworks: string[],
    organizationId: string
  ): Promise<string[]> {
    const contradictions: string[] = [];

    // Define contradiction keywords
    const contradictionPairs = [
      { require: 'must retain', conflict: 'must delete' },
      { require: 'shall encrypt', conflict: 'plain text allowed' },
      { require: 'consent required', conflict: 'implied consent' },
      { require: 'minimum retention', conflict: 'maximum retention' },
      { require: 'must notify within 24', conflict: 'notify within 72' },
    ];

    for (const requirement of existingRequirements) {
      const lowerReq = requirement.toLowerCase();

      for (const pair of contradictionPairs) {
        if (lowerReq.includes(pair.require.split(' ')[0]) ||
            lowerReq.includes(pair.conflict.split(' ')[0])) {
          // Check if affected frameworks have conflicting controls
          const frameworks = await prisma.complianceFramework.findMany({
            where: {
              id: { in: affectedFrameworks },
            },
            include: { controls: true },
          });

          for (const framework of frameworks) {
            for (const control of framework.controls) {
              const controlDesc = (control.description || '').toLowerCase();
              if ((lowerReq.includes(pair.require) && controlDesc.includes(pair.conflict)) ||
                  (lowerReq.includes(pair.conflict) && controlDesc.includes(pair.require))) {
                contradictions.push(
                  `Requirement "${requirement.substring(0, 50)}..." contradicts control "${control.name}"`
                );
              }
            }
          }
        }
      }
    }

    return contradictions;
  }

  /**
   * Auto-update controls based on regulatory change
   */
  async autoUpdateControls(
    regulatoryChangeId: string,
    organizationId: string,
    userId: string
  ): Promise<{
    controlsCreated: number;
    controlsUpdated: number;
    frameworksAffected: number;
  }> {
    try {
      // Get regulatory change from database
      const regulatoryChange = await prisma.regulatoryChange.findFirst({
        where: {
          id: regulatoryChangeId,
          organizationId,
        },
      });

      if (!regulatoryChange) {
        throw new Error('Regulatory change not found');
      }

      let controlsCreated = 0;
      let controlsUpdated = 0;
      const affectedFrameworkIds = new Set<string>();

      // Process auto-generated controls
      const autoControls = regulatoryChange.autoGeneratedControls as any[] || [];

      for (const controlData of autoControls) {
        // Find matching frameworks
        const frameworks = await prisma.complianceFramework.findMany({
          where: {
            organizationId,
            id: { in: regulatoryChange.affectedFrameworks },
          },
          include: { controls: true },
        });

        for (const framework of frameworks) {
          affectedFrameworkIds.add(framework.id);

          // Check if similar control already exists
          const existingControl = framework.controls.find((c: any) =>
            c.name.toLowerCase().includes(controlData.name.toLowerCase().split(':')[0]) ||
            (c.description && c.description.toLowerCase().includes(controlData.description.toLowerCase().substring(0, 50)))
          );

          if (existingControl) {
            // Update existing control
            await prisma.frameworkControl.update({
              where: { id: existingControl.id },
              data: {
                description: `${existingControl.description || ''}\n\n[Auto-updated from ${regulatoryChange.regulationName}]: ${controlData.description}`,
                updatedAt: new Date(),
              },
            });
            controlsUpdated++;
          } else {
            // Create new control
            await prisma.frameworkControl.create({
              data: {
                frameworkId: framework.id,
                name: controlData.name,
                description: `[Auto-generated from ${regulatoryChange.regulationName}]: ${controlData.description}`,
                status: 'Pending',
              },
            });
            controlsCreated++;
          }
        }
      }

      // Update regulatory change status
      await prisma.regulatoryChange.update({
        where: { id: regulatoryChangeId },
        data: {
          status: 'implemented',
          updatedAt: new Date(),
        },
      });

      // Store auto-update result
      await prisma.auditLog.create({
        data: {
          action: 'rif.controls_auto_updated',
          details: JSON.stringify({
            regulatoryChangeId,
            regulationName: regulatoryChange.regulationName,
            controlsCreated,
            controlsUpdated,
            frameworksAffected: affectedFrameworkIds.size,
          }),
          userId,
          organizationId,
          hash: require('crypto').randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Controls auto-updated for regulation ${regulatoryChangeId}: ${controlsCreated} created, ${controlsUpdated} updated`);

      return {
        controlsCreated,
        controlsUpdated,
        frameworksAffected: affectedFrameworkIds.size,
      };
    } catch (error) {
      logger.error('[RIF] Error auto-updating controls', error);
      throw error;
    }
  }

  /**
   * Monitor regulatory feeds (can be called periodically)
   */
  async monitorRegulatoryFeeds(organizationId: string): Promise<RegulatoryChange[]> {
    try {
      const changes: RegulatoryChange[] = [];

      // Define regulatory feed sources
      const feedSources = [
        { name: 'SEC', jurisdiction: 'US', url: 'https://www.sec.gov/rss/divisions/corpfin/cfnew.xml' },
        { name: 'GDPR', jurisdiction: 'EU', url: 'https://ec.europa.eu/newsroom/just/rss' },
        { name: 'NIST', jurisdiction: 'US', url: 'https://csrc.nist.gov/CSRC/media/rss-feeds/publications-feed' },
        { name: 'ISO', jurisdiction: 'Global', url: 'https://www.iso.org/rss/standards.xml' },
      ];

      // Check for recent regulatory changes (simulated feed processing)
      // In production, would actually fetch and parse RSS/Atom feeds

      // Get frameworks for the organization to determine relevant feeds
      const frameworks = await prisma.complianceFramework.findMany({
        where: { organizationId },
        select: { name: true, id: true },
      });

      const frameworkNames = frameworks.map(f => f.name.toLowerCase());

      // Simulate feed monitoring results based on framework relevance
      for (const source of feedSources) {
        // Check if any frameworks are related to this source
        const isRelevant = frameworkNames.some(name =>
          name.includes(source.name.toLowerCase()) ||
          name.includes(source.jurisdiction.toLowerCase())
        );

        if (isRelevant) {
          // In production, would fetch actual feed content here
          // For now, check if there are recent pending changes
          const pendingChanges = await prisma.regulatoryChange.findMany({
            where: {
              organizationId,
              jurisdiction: source.jurisdiction,
              status: 'pending',
              createdAt: {
                gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // Last 7 days
              },
            },
          });

          for (const change of pendingChanges) {
            changes.push({
              id: change.id,
              regulationName: change.regulationName,
              jurisdiction: change.jurisdiction,
              effectiveDate: change.effectiveDate,
              changeType: change.changeType as any,
              affectedFrameworks: change.affectedFrameworks,
              extractedRequirements: change.extractedRequirements,
              autoGeneratedControls: change.autoGeneratedControls as any[],
              status: change.status as any,
            });
          }
        }
      }

      // Log monitoring activity
      await prisma.auditLog.create({
        data: {
          action: 'rif.feeds_monitored',
          details: JSON.stringify({
            sourcesChecked: feedSources.length,
            changesFound: changes.length,
            timestamp: new Date(),
          }),
          userId: 'system',
          organizationId,
          hash: require('crypto').randomBytes(16).toString('hex'),
        },
      });

      logger.info(`[RIF] Regulatory feeds monitored: ${changes.length} changes found`);

      return changes;
    } catch (error) {
      logger.error('[RIF] Error monitoring regulatory feeds', error);
      return [];
    }
  }

  /**
   * Get regulatory changes for organization
   */
  async getRegulatoryChanges(
    organizationId: string,
    status?: string
  ): Promise<RegulatoryChange[]> {
    try {
      const changes = await prisma.regulatoryChange.findMany({
        where: {
          organizationId,
          ...(status && { status }),
        },
        orderBy: { createdAt: 'desc' },
      });

      return changes.map((c: any) => ({
        id: c.id,
        regulationName: c.regulationName,
        jurisdiction: c.jurisdiction,
        effectiveDate: c.effectiveDate,
        changeType: c.changeType,
        affectedFrameworks: c.affectedFrameworks,
        extractedRequirements: c.extractedRequirements,
        autoGeneratedControls: c.autoGeneratedControls,
        status: c.status,
      }));
    } catch (error) {
      logger.error('[RIF] Error getting regulatory changes', error);
      return [];
    }
  }
}

export default new RegulatoryIntelligenceFabricService();

