/**
 * Identity / SSO Provider Integrations (25 providers)
 * Real API implementations for all identity, SSO, and access management providers.
 */
import { createProviders, ProviderDescriptor } from './providerFactory';

const descriptors: ProviderDescriptor[] = [
  {
    id: 'okta', name: 'Okta', category: 'Identity',
    apiBaseUrl: 'https://{domain}.okta.com/api/v1', apiDocsUrl: 'https://developer.okta.com/docs/reference/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'SSWS',
    testEndpoint: '/users/me',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Okta Users', description: 'All provisioned users in the Okta directory', path: '/users', method: 'GET' },
      { type: 'access_control', title: 'Okta Groups', description: 'Groups and role assignments for access review', path: '/groups', method: 'GET' },
      { type: 'audit_log', title: 'Okta System Log', description: 'System log events for audit trail', path: '/logs', method: 'GET' },
      { type: 'policy_config', title: 'Okta Sign-On Policies', description: 'Global sign-on policy configurations', path: '/policies?type=OKTA_SIGN_ON', method: 'GET' },
      { type: 'configuration', title: 'Okta Authorization Servers', description: 'OAuth authorization server configurations', path: '/authorizationServers', method: 'GET' },
    ],
  },
  {
    id: 'azure-ad', name: 'Microsoft Entra ID (Azure AD)', category: 'Identity',
    apiBaseUrl: 'https://graph.microsoft.com/v1.0', apiDocsUrl: 'https://learn.microsoft.com/en-us/graph/api/overview',
    authMethods: ['oauth', 'service-account'], authPrefix: 'Bearer',
    testEndpoint: '/me',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Entra ID Users', description: 'All users in the Azure AD tenant', path: '/users', method: 'GET' },
      { type: 'access_control', title: 'Entra ID Directory Roles', description: 'Active directory role assignments', path: '/directoryRoles', method: 'GET' },
      { type: 'audit_log', title: 'Entra ID Sign-In Logs', description: 'User sign-in activity audit logs', path: '/auditLogs/signIns', method: 'GET' },
      { type: 'policy_config', title: 'Conditional Access Policies', description: 'Conditional Access policies for sign-in controls', path: '/identity/conditionalAccess/policies', method: 'GET' },
      { type: 'configuration', title: 'Entra ID Applications', description: 'Registered application configurations', path: '/applications', method: 'GET' },
    ],
  },
  {
    id: 'google-workspace', name: 'Google Workspace', category: 'Identity',
    apiBaseUrl: 'https://admin.googleapis.com', apiDocsUrl: 'https://developers.google.com/admin-sdk/directory/reference/rest',
    authMethods: ['oauth', 'service-account'], authPrefix: 'Bearer',
    testEndpoint: '/admin/directory/v1/users?domain={domain}&maxResults=1',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Google Workspace Users', description: 'All users in the Google Workspace domain', path: '/admin/directory/v1/users?domain={domain}', method: 'GET' },
      { type: 'access_control', title: 'Google Workspace Roles', description: 'Admin role assignments for access review', path: '/admin/directory/v1/customer/{account}/roles', method: 'GET' },
      { type: 'audit_log', title: 'Google Workspace Admin Activity', description: 'Admin console activity audit events', path: '/admin/reports/v1/activity/users/all/applications/admin', method: 'GET' },
      { type: 'policy_config', title: 'Google Workspace Org Units', description: 'Organizational unit policy structure', path: '/admin/directory/v1/customer/{account}/orgunits?type=all', method: 'GET' },
      { type: 'configuration', title: 'Google Workspace Domains', description: 'Domain configuration and verification status', path: '/admin/directory/v1/customer/{account}/domains', method: 'GET' },
    ],
  },
  {
    id: 'onelogin', name: 'OneLogin', category: 'Identity',
    apiBaseUrl: 'https://{domain}.onelogin.com/api/2', apiDocsUrl: 'https://developers.onelogin.com/api-docs/2/getting-started/dev-overview',
    authMethods: ['oauth', 'api-key'], authPrefix: 'Bearer',
    testEndpoint: '/api/2/users?limit=1',
    evidenceEndpoints: [
      { type: 'user_list', title: 'OneLogin Users', description: 'All provisioned users', path: '/users', method: 'GET' },
      { type: 'access_control', title: 'OneLogin Roles', description: 'Role definitions and user-role mappings', path: '/roles', method: 'GET' },
      { type: 'audit_log', title: 'OneLogin Events', description: 'Security event log entries', path: '/events', method: 'GET' },
      { type: 'policy_config', title: 'OneLogin Policies', description: 'User security policy configurations', path: '/policies', method: 'GET' },
      { type: 'configuration', title: 'OneLogin Apps', description: 'Configured SSO application connectors', path: '/apps', method: 'GET' },
    ],
  },
  {
    id: 'jumpcloud', name: 'JumpCloud', category: 'Identity',
    apiBaseUrl: 'https://console.jumpcloud.com/api', apiDocsUrl: 'https://docs.jumpcloud.com/api/',
    authMethods: ['api-key'], authHeader: 'x-api-key', authPrefix: '',
    testEndpoint: '/systemusers?limit=1',
    evidenceEndpoints: [
      { type: 'user_list', title: 'JumpCloud Users', description: 'All system users in the directory', path: '/systemusers', method: 'GET' },
      { type: 'access_control', title: 'JumpCloud User Groups', description: 'User group memberships for access review', path: '/v2/usergroups', method: 'GET' },
      { type: 'audit_log', title: 'JumpCloud Directory Events', description: 'Directory insight audit events', path: 'https://events.jumpcloud.com/events', method: 'POST', params: { service: ['all'], start_time: '2024-01-01T00:00:00Z' } },
      { type: 'policy_config', title: 'JumpCloud Policies', description: 'System and device policy configurations', path: '/v2/policies', method: 'GET' },
      { type: 'configuration', title: 'JumpCloud Applications', description: 'SSO application configurations', path: '/v2/applications', method: 'GET' },
    ],
  },
  {
    id: 'ping-identity', name: 'Ping Identity (PingOne)', category: 'Identity',
    apiBaseUrl: 'https://api.pingone.com/v1/environments/{tenant}', apiDocsUrl: 'https://apidocs.pingidentity.com/pingone/platform/v1/api/',
    authMethods: ['oauth'], authPrefix: 'Bearer',
    testEndpoint: '/users?limit=1',
    evidenceEndpoints: [
      { type: 'user_list', title: 'PingOne Users', description: 'All users in the PingOne environment', path: '/users', method: 'GET' },
      { type: 'access_control', title: 'PingOne Roles', description: 'Role assignments for access governance', path: '/roles', method: 'GET' },
      { type: 'audit_log', title: 'PingOne Audit Activities', description: 'Audit activity events for compliance', path: '/activities', method: 'GET' },
      { type: 'policy_config', title: 'PingOne Sign-On Policies', description: 'Sign-on policy configurations', path: '/signOnPolicies', method: 'GET' },
      { type: 'configuration', title: 'PingOne Applications', description: 'Application connection configurations', path: '/applications', method: 'GET' },
    ],
  },
  {
    id: 'auth0', name: 'Auth0', category: 'Identity',
    apiBaseUrl: 'https://{domain}.auth0.com/api/v2', apiDocsUrl: 'https://auth0.com/docs/api/management/v2',
    authMethods: ['oauth', 'api-key'], authPrefix: 'Bearer',
    testEndpoint: '/users?per_page=1',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Auth0 Users', description: 'All users in the Auth0 tenant', path: '/users', method: 'GET' },
      { type: 'access_control', title: 'Auth0 Roles', description: 'Role definitions and permissions', path: '/roles', method: 'GET' },
      { type: 'audit_log', title: 'Auth0 Logs', description: 'Tenant log events for audit trail', path: '/logs', method: 'GET' },
      { type: 'policy_config', title: 'Auth0 Rules', description: 'Authentication pipeline rules and actions', path: '/rules', method: 'GET' },
      { type: 'configuration', title: 'Auth0 Connections', description: 'Identity provider connection configurations', path: '/connections', method: 'GET' },
    ],
  },
  {
    id: 'cyberark', name: 'CyberArk Identity', category: 'Identity',
    apiBaseUrl: 'https://{domain}.id.cyberark.cloud', apiDocsUrl: 'https://identity-developer.cyberark.com/docs',
    authMethods: ['oauth', 'api-key'], authPrefix: 'Bearer',
    testEndpoint: '/CDirectoryService/GetUser',
    evidenceEndpoints: [
      { type: 'user_list', title: 'CyberArk Users', description: 'All directory service users', path: '/CDirectoryService/GetUsers', method: 'POST', params: { PageSize: 500, SortBy: 'Username' } },
      { type: 'access_control', title: 'CyberArk Roles', description: 'Role definitions and privilege assignments', path: '/Roles/GetRoles', method: 'POST' },
      { type: 'audit_log', title: 'CyberArk Audit Events', description: 'Redrock query for audit trail events', path: '/Redrock/Query', method: 'POST', params: { Script: "SELECT * FROM Event ORDER BY WhenOccurred DESC LIMIT 500" } },
      { type: 'policy_config', title: 'CyberArk Policies', description: 'Authentication and MFA policy configurations', path: '/Policy/GetPolicySummary', method: 'POST' },
      { type: 'configuration', title: 'CyberArk Applications', description: 'Registered web application configurations', path: '/SaasManage/GetApps', method: 'POST' },
    ],
  },
  {
    id: 'forgerock', name: 'ForgeRock', category: 'Identity',
    apiBaseUrl: 'https://{domain}.forgeblocks.com', apiDocsUrl: 'https://backstage.forgerock.com/docs/idcloud/latest/api/',
    authMethods: ['oauth', 'api-key'], authPrefix: 'Bearer',
    testEndpoint: '/openidm/info/ping',
    evidenceEndpoints: [
      { type: 'user_list', title: 'ForgeRock Managed Users', description: 'All managed user identities', path: '/openidm/managed/alpha_user?_queryFilter=true', method: 'GET' },
      { type: 'access_control', title: 'ForgeRock Roles', description: 'Managed roles and assignments', path: '/openidm/managed/alpha_role?_queryFilter=true', method: 'GET' },
      { type: 'audit_log', title: 'ForgeRock Audit Activity', description: 'Audit log activity events', path: '/openidm/audit/activity?_queryFilter=true', method: 'GET' },
      { type: 'policy_config', title: 'ForgeRock Auth Trees', description: 'Authentication tree (journey) configurations', path: '/am/json/realms/root/realms/alpha/realm-config/authentication/authenticationtrees/trees?_queryFilter=true', method: 'GET' },
      { type: 'configuration', title: 'ForgeRock OAuth2 Clients', description: 'OAuth2 client application configurations', path: '/am/json/realms/root/realms/alpha/realm-config/agents/OAuth2Client?_queryFilter=true', method: 'GET' },
    ],
  },
  {
    id: 'duo-security', name: 'Duo Security', category: 'Identity',
    apiBaseUrl: 'https://{domain}.duosecurity.com', apiDocsUrl: 'https://duo.com/docs/adminapi',
    authMethods: ['api-key-secret'], authHeader: 'Authorization', authPrefix: 'Basic',
    testEndpoint: '/admin/v1/info/summary',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Duo Users', description: 'All enrolled Duo users', path: '/admin/v1/users', method: 'GET' },
      { type: 'access_control', title: 'Duo Groups', description: 'User groups for access control review', path: '/admin/v1/groups', method: 'GET' },
      { type: 'audit_log', title: 'Duo Authentication Logs', description: 'Authentication attempt log entries', path: '/admin/v2/logs/authentication', method: 'GET' },
      { type: 'policy_config', title: 'Duo Policies', description: 'Authentication and device policy settings', path: '/admin/v2/policies', method: 'GET' },
      { type: 'configuration', title: 'Duo Integrations', description: 'Application integration configurations', path: '/admin/v1/integrations', method: 'GET' },
    ],
  },
  {
    id: 'lastpass-business', name: 'LastPass Business', category: 'Identity',
    apiBaseUrl: 'https://lastpass.com/enterpriseapi.php', apiDocsUrl: 'https://support.lastpass.com/s/document-item?bundleId=lastpass&topicId=LastPass/api_reference_overview.html',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '',
    evidenceEndpoints: [
      { type: 'user_list', title: 'LastPass Users', description: 'All enrolled enterprise users', path: '', method: 'POST', params: { cid: '{account}', cmd: 'getuserdata' } },
      { type: 'access_control', title: 'LastPass Groups', description: 'Group-based access assignments', path: '', method: 'POST', params: { cid: '{account}', cmd: 'getgroupdata' } },
      { type: 'audit_log', title: 'LastPass Event Reports', description: 'Enterprise event reporting data', path: '', method: 'POST', params: { cid: '{account}', cmd: 'reporting', data: { from: '2024-01-01', to: '2025-12-31' } } },
      { type: 'policy_config', title: 'LastPass Policies', description: 'Enterprise security policy settings', path: '', method: 'POST', params: { cid: '{account}', cmd: 'getpolicies' } },
      { type: 'configuration', title: 'LastPass Shared Folders', description: 'Shared folder configuration and permissions', path: '', method: 'POST', params: { cid: '{account}', cmd: 'getsfdata' } },
    ],
  },
  {
    id: '1password-business', name: '1Password Business', category: 'Identity',
    apiBaseUrl: 'https://{domain}.1password.com/api/v1', apiDocsUrl: 'https://developer.1password.com/docs/events-api/',
    authMethods: ['api-key'], authPrefix: 'Bearer',
    testEndpoint: 'https://events.1password.com/api/v1/auditevents?limit=1',
    evidenceEndpoints: [
      { type: 'user_list', title: '1Password Users', description: 'All team member accounts via SCIM', path: 'https://{domain}.1password.com/api/v2/Users', method: 'GET' },
      { type: 'access_control', title: '1Password Groups', description: 'Team groups for access governance', path: 'https://{domain}.1password.com/api/v2/Groups', method: 'GET' },
      { type: 'audit_log', title: '1Password Audit Events', description: 'Business audit event stream', path: 'https://events.1password.com/api/v1/auditevents', method: 'POST', params: { limit: 100 } },
      { type: 'policy_config', title: '1Password Sign-In Events', description: 'Sign-in attempts for policy enforcement review', path: 'https://events.1password.com/api/v1/signinattempts', method: 'POST', params: { limit: 100 } },
      { type: 'configuration', title: '1Password Vaults', description: 'Vault configurations and sharing settings', path: 'https://{domain}.1password.com/api/v2/ServiceProviderConfig', method: 'GET' },
    ],
  },
  {
    id: 'dashlane-business', name: 'Dashlane Business', category: 'Identity',
    apiBaseUrl: 'https://{domain}.dashlane.com/api/v1', apiDocsUrl: 'https://www.dashlane.com/business/api',
    authMethods: ['api-key'], authPrefix: 'Bearer',
    testEndpoint: 'https://{domain}.dashlane.com/api/v2/Users?count=1',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Dashlane Users', description: 'All business plan user accounts via SCIM', path: 'https://{domain}.dashlane.com/api/v2/Users', method: 'GET' },
      { type: 'access_control', title: 'Dashlane Groups', description: 'Sharing group configurations', path: 'https://{domain}.dashlane.com/api/v2/Groups', method: 'GET' },
      { type: 'audit_log', title: 'Dashlane Audit Logs', description: 'Team audit log events', path: '/auditlogs', method: 'GET' },
      { type: 'policy_config', title: 'Dashlane Team Settings', description: 'Team security policy settings', path: '/team/settings', method: 'GET' },
      { type: 'configuration', title: 'Dashlane Team Members', description: 'Team member roles and status details', path: '/team/members', method: 'GET' },
    ],
  },
  {
    id: 'keeper', name: 'Keeper Security', category: 'Identity',
    apiBaseUrl: 'https://{domain}.keepersecurity.com/api/rest', apiDocsUrl: 'https://docs.keeper.io/enterprise-guide/keeper-admin-apis',
    authMethods: ['api-key'], authPrefix: 'Bearer',
    testEndpoint: '/enterprise/info',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Keeper Users', description: 'All enterprise vault users', path: '/enterprise/user', method: 'GET' },
      { type: 'access_control', title: 'Keeper Teams', description: 'Team structures and memberships', path: '/enterprise/team', method: 'GET' },
      { type: 'audit_log', title: 'Keeper Audit Events', description: 'Enterprise audit event log', path: '/enterprise/audit', method: 'POST', params: { command: 'get_audit_event_reports', report_type: 'raw' } },
      { type: 'policy_config', title: 'Keeper Enforcements', description: 'Enterprise role enforcement policies', path: '/enterprise/role_enforcement', method: 'GET' },
      { type: 'configuration', title: 'Keeper Nodes', description: 'Enterprise organizational node configuration', path: '/enterprise/node', method: 'GET' },
    ],
  },
  {
    id: 'beyondtrust', name: 'BeyondTrust', category: 'Identity',
    apiBaseUrl: 'https://{domain}.beyondtrustcloud.com/BeyondTrust/api/public/v3', apiDocsUrl: 'https://www.beyondtrust.com/docs/privilege-management/api/',
    authMethods: ['api-key', 'oauth'], authPrefix: 'Bearer',
    testEndpoint: '/Status',
    evidenceEndpoints: [
      { type: 'user_list', title: 'BeyondTrust Users', description: 'Privileged session users', path: '/Users', method: 'GET' },
      { type: 'access_control', title: 'BeyondTrust Session Policies', description: 'Session access policies and permissions', path: '/SessionPolicies', method: 'GET' },
      { type: 'audit_log', title: 'BeyondTrust Access Sessions', description: 'Privileged access session recordings', path: '/Sessions', method: 'GET' },
      { type: 'policy_config', title: 'BeyondTrust Group Policies', description: 'Group policy configurations', path: '/GroupPolicies', method: 'GET' },
      { type: 'configuration', title: 'BeyondTrust Jump Items', description: 'Managed jump item endpoint configurations', path: '/JumpItems', method: 'GET' },
    ],
  },
  {
    id: 'sailpoint', name: 'SailPoint IdentityNow', category: 'Identity',
    apiBaseUrl: 'https://{tenant}.api.identitynow.com', apiDocsUrl: 'https://developer.sailpoint.com/docs/api/v3/',
    authMethods: ['oauth', 'api-key'], authPrefix: 'Bearer',
    testEndpoint: '/v3/public-identities?limit=1',
    evidenceEndpoints: [
      { type: 'user_list', title: 'SailPoint Identities', description: 'All governed identities', path: '/v3/public-identities', method: 'GET' },
      { type: 'access_control', title: 'SailPoint Access Profiles', description: 'Access profile entitlement bundles', path: '/v3/access-profiles', method: 'GET' },
      { type: 'audit_log', title: 'SailPoint Audit Events', description: 'Search audit events for compliance', path: '/v3/search', method: 'POST', params: { indices: ['events'], query: { query: '*' }, sort: ['-created'] } },
      { type: 'policy_config', title: 'SailPoint Governance Policies', description: 'SOD and governance policy rules', path: '/v3/sod-policies', method: 'GET' },
      { type: 'configuration', title: 'SailPoint Sources', description: 'Identity source system configurations', path: '/v3/sources', method: 'GET' },
    ],
  },
  {
    id: 'saviynt', name: 'Saviynt', category: 'Identity',
    apiBaseUrl: 'https://{domain}.saviyntcloud.com', apiDocsUrl: 'https://saviynt.com/integrations/',
    authMethods: ['oauth', 'username-password'], authPrefix: 'Bearer',
    testEndpoint: '/ECM/api/v5/getUser',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Saviynt Users', description: 'All managed user accounts', path: '/ECM/api/v5/getUser', method: 'POST', params: { max: 500 } },
      { type: 'access_control', title: 'Saviynt Entitlements', description: 'Entitlement assignments for access review', path: '/ECM/api/v5/getEntitlements', method: 'POST', params: { max: 500 } },
      { type: 'audit_log', title: 'Saviynt Audit Trail', description: 'Runtime audit controls log', path: '/ECM/api/v5/getAuditTrail', method: 'POST', params: { max: 500 } },
      { type: 'policy_config', title: 'Saviynt SOD Policies', description: 'Segregation of duties policy configurations', path: '/ECM/api/v5/getSoDPolicies', method: 'POST' },
      { type: 'configuration', title: 'Saviynt Connections', description: 'Enterprise connection and endpoint configurations', path: '/ECM/api/v5/getConnectionDetails', method: 'POST' },
    ],
  },
  {
    id: 'ibm-verify', name: 'IBM Security Verify', category: 'Identity',
    apiBaseUrl: 'https://{tenant}.verify.ibm.com', apiDocsUrl: 'https://docs.verify.ibm.com/verify/reference',
    authMethods: ['oauth', 'api-key'], authPrefix: 'Bearer',
    testEndpoint: '/v1.0/Me',
    evidenceEndpoints: [
      { type: 'user_list', title: 'IBM Verify Users', description: 'All directory user identities', path: '/v2.0/Users', method: 'GET' },
      { type: 'access_control', title: 'IBM Verify Groups', description: 'Group definitions and memberships', path: '/v2.0/Groups', method: 'GET' },
      { type: 'audit_log', title: 'IBM Verify Audit Events', description: 'Security event audit trail', path: '/v1.0/reports/audit_events', method: 'GET' },
      { type: 'policy_config', title: 'IBM Verify Access Policies', description: 'Access and authentication policy definitions', path: '/v1.0/accessPolicies', method: 'GET' },
      { type: 'configuration', title: 'IBM Verify Applications', description: 'Application SSO configurations', path: '/v1.0/applications', method: 'GET' },
    ],
  },
  {
    id: 'thales-gemalto', name: 'Thales SafeNet Trusted Access', category: 'Identity',
    apiBaseUrl: 'https://api.{region}.safenetid.com', apiDocsUrl: 'https://thalesdocs.com/sta/operator/api/',
    authMethods: ['api-key', 'oauth'], authPrefix: 'Bearer',
    testEndpoint: '/api/v1/tenants/current',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Thales STA Users', description: 'All SafeNet Trusted Access users', path: '/api/v1/users', method: 'GET' },
      { type: 'access_control', title: 'Thales STA Groups', description: 'Group-based access control assignments', path: '/api/v1/groups', method: 'GET' },
      { type: 'audit_log', title: 'Thales STA Audit Logs', description: 'Authentication and admin audit events', path: '/api/v1/logs/audit', method: 'GET' },
      { type: 'policy_config', title: 'Thales STA Policies', description: 'Access and authentication policy definitions', path: '/api/v1/policies', method: 'GET' },
      { type: 'configuration', title: 'Thales STA Applications', description: 'Application integration configurations', path: '/api/v1/applications', method: 'GET' },
    ],
  },
  {
    id: 'rsa-securid', name: 'RSA SecurID', category: 'Identity',
    apiBaseUrl: 'https://{domain}/mfa/v1_1', apiDocsUrl: 'https://community.rsa.com/docs/DOC-75741',
    authMethods: ['api-key'], authPrefix: 'Bearer',
    testEndpoint: '/tenants/current',
    evidenceEndpoints: [
      { type: 'user_list', title: 'RSA SecurID Users', description: 'All registered MFA users', path: '/users', method: 'GET' },
      { type: 'access_control', title: 'RSA SecurID User Groups', description: 'User group assignments for access review', path: '/user-groups', method: 'GET' },
      { type: 'audit_log', title: 'RSA SecurID Auth Activity', description: 'Authentication activity audit logs', path: '/auth-activity', method: 'GET' },
      { type: 'policy_config', title: 'RSA SecurID Policies', description: 'Authentication and access policy configurations', path: '/policies', method: 'GET' },
      { type: 'configuration', title: 'RSA SecurID RADIUS Clients', description: 'RADIUS client integration configurations', path: '/radius-clients', method: 'GET' },
    ],
  },
  {
    id: 'centrify', name: 'Delinea (Centrify) Platform', category: 'Identity',
    apiBaseUrl: 'https://{tenant}.my.centrify.net', apiDocsUrl: 'https://developer.centrify.com/reference',
    authMethods: ['oauth', 'api-key'], authPrefix: 'Bearer',
    testEndpoint: '/CDirectoryService/GetUser',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Centrify Users', description: 'All Cloud Directory users', path: '/CDirectoryService/GetUsers', method: 'POST', params: { PageSize: 500 } },
      { type: 'access_control', title: 'Centrify Roles', description: 'Platform roles and privilege assignments', path: '/Roles/GetRoles', method: 'POST' },
      { type: 'audit_log', title: 'Centrify Audit Events', description: 'Redrock query for audit trail', path: '/Redrock/Query', method: 'POST', params: { Script: "SELECT * FROM Event ORDER BY WhenOccurred DESC LIMIT 500" } },
      { type: 'policy_config', title: 'Centrify Policy Sets', description: 'Authentication and MFA policy sets', path: '/Policy/GetPolicyBlock', method: 'POST', params: { name: '/' } },
      { type: 'configuration', title: 'Centrify Applications', description: 'Registered web application configurations', path: '/SaasManage/GetApps', method: 'POST' },
    ],
  },
  {
    id: 'aws-iam', name: 'AWS IAM', category: 'Identity',
    apiBaseUrl: 'https://iam.amazonaws.com', apiDocsUrl: 'https://docs.aws.amazon.com/IAM/latest/APIReference/',
    authMethods: ['iam'], testEndpoint: '/?Action=GetUser&Version=2010-05-08',
    evidenceEndpoints: [
      { type: 'user_list', title: 'IAM Users', description: 'All IAM users in the AWS account', path: '/?Action=ListUsers&Version=2010-05-08', method: 'GET' },
      { type: 'access_control', title: 'IAM Policies', description: 'Managed IAM policies for access review', path: '/?Action=ListPolicies&Scope=Local&Version=2010-05-08', method: 'GET' },
      { type: 'audit_log', title: 'IAM Credential Report', description: 'Credential usage report for all IAM users', path: '/?Action=GetCredentialReport&Version=2010-05-08', method: 'GET' },
      { type: 'policy_config', title: 'IAM Password Policy', description: 'Account password policy configuration', path: '/?Action=GetAccountPasswordPolicy&Version=2010-05-08', method: 'GET' },
      { type: 'configuration', title: 'IAM Roles', description: 'IAM role configurations and trust policies', path: '/?Action=ListRoles&Version=2010-05-08', method: 'GET' },
    ],
  },
  {
    id: 'hashicorp-vault', name: 'HashiCorp Vault', category: 'Identity',
    apiBaseUrl: 'https://{domain}:8200/v1', apiDocsUrl: 'https://developer.hashicorp.com/vault/api-docs',
    authMethods: ['api-key'], authHeader: 'X-Vault-Token', authPrefix: '',
    testEndpoint: '/sys/health',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Vault Auth Methods Users', description: 'Users from userpass auth method', path: '/auth/userpass/users', method: 'GET' },
      { type: 'access_control', title: 'Vault Policies', description: 'ACL policy definitions for access governance', path: '/sys/policies/acl', method: 'GET' },
      { type: 'audit_log', title: 'Vault Audit Devices', description: 'Configured audit logging devices and status', path: '/sys/audit', method: 'GET' },
      { type: 'policy_config', title: 'Vault Auth Methods', description: 'Enabled authentication method configurations', path: '/sys/auth', method: 'GET' },
      { type: 'configuration', title: 'Vault Secrets Engines', description: 'Mounted secrets engine configurations', path: '/sys/mounts', method: 'GET' },
    ],
  },
  {
    id: 'delinea', name: 'Delinea Secret Server', category: 'Identity',
    apiBaseUrl: 'https://{domain}/SecretServer/api/v1', apiDocsUrl: 'https://docs.delinea.com/online-help/secret-server/api-scripting/rest-api-reference/',
    authMethods: ['oauth', 'username-password'], authPrefix: 'Bearer',
    testEndpoint: '/version',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Secret Server Users', description: 'All local and domain user accounts', path: '/users', method: 'GET' },
      { type: 'access_control', title: 'Secret Server Roles', description: 'Role definitions and permission assignments', path: '/roles', method: 'GET' },
      { type: 'audit_log', title: 'Secret Server Audit', description: 'Secret access and admin audit trail', path: '/secrets/lookup?filter.includeRecentActivity=true', method: 'GET' },
      { type: 'policy_config', title: 'Secret Server Policies', description: 'Secret and security policy template configurations', path: '/secret-policy', method: 'GET' },
      { type: 'configuration', title: 'Secret Server Folders', description: 'Folder structure and permission inheritance settings', path: '/folders', method: 'GET' },
    ],
  },
  {
    id: 'aws-cognito', name: 'AWS Cognito', category: 'Identity',
    apiBaseUrl: 'https://cognito-idp.{region}.amazonaws.com', apiDocsUrl: 'https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/',
    authMethods: ['iam'], testEndpoint: '/',
    evidenceEndpoints: [
      { type: 'user_list', title: 'Cognito User Pools Users', description: 'Users in the specified Cognito User Pool', path: '/', method: 'POST', params: { UserPoolId: '{account}', Limit: 60 } },
      { type: 'access_control', title: 'Cognito User Pool Groups', description: 'Groups and role mappings in the User Pool', path: '/', method: 'POST', params: { UserPoolId: '{account}', Limit: 60 } },
      { type: 'audit_log', title: 'Cognito User Pool Audit', description: 'User pool admin event history via CloudTrail', path: 'https://cloudtrail.{region}.amazonaws.com/?Action=LookupEvents&LookupAttributes.member.1.AttributeKey=EventSource&LookupAttributes.member.1.AttributeValue=cognito-idp.amazonaws.com', method: 'GET' },
      { type: 'policy_config', title: 'Cognito User Pool Config', description: 'User Pool password and MFA policy settings', path: '/', method: 'POST', params: { UserPoolId: '{account}' } },
      { type: 'configuration', title: 'Cognito App Clients', description: 'User Pool app client configurations', path: '/', method: 'POST', params: { UserPoolId: '{account}', MaxResults: 60 } },
    ],
  },
];

export default createProviders(descriptors);
