/**
 * Monitoring / SIEM / MDM Provider Integrations (50 providers)
 * Real API implementations for monitoring, SIEM, and MDM providers.
 */
import { createProviders, ProviderDescriptor } from './providerFactory';

const descriptors: ProviderDescriptor[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // Monitoring (25 providers)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'datadog', name: 'Datadog', category: 'Monitoring',
    apiBaseUrl: 'https://api.datadoghq.com/api/v1', apiDocsUrl: 'https://docs.datadoghq.com/api/',
    authMethods: ['api-key'], authHeader: 'DD-API-KEY', authPrefix: '',
    testEndpoint: '/validate',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Datadog Monitor Config', description: 'All configured monitors and their settings', path: '/monitor', method: 'GET' },
      { type: 'audit_log', title: 'Datadog Audit Logs', description: 'Organization audit trail events', path: 'https://api.datadoghq.com/api/v2/audit/events', method: 'GET' },
      { type: 'incident_report', title: 'Datadog Incidents', description: 'Active and resolved incidents', path: 'https://api.datadoghq.com/api/v2/incidents', method: 'GET' },
      { type: 'compliance_status', title: 'Datadog SLOs', description: 'Service level objective compliance status', path: '/slo', method: 'GET' },
    ],
  },
  {
    id: 'new-relic', name: 'New Relic', category: 'Monitoring',
    apiBaseUrl: 'https://api.newrelic.com/v2', apiDocsUrl: 'https://docs.newrelic.com/docs/apis/',
    authMethods: ['api-key'], authHeader: 'Api-Key', authPrefix: '',
    testEndpoint: 'https://api.newrelic.com/graphql', rateLimitPerMinute: 100,
    evidenceEndpoints: [
      { type: 'configuration', title: 'New Relic Alert Policies', description: 'Alert policy configurations', path: '/alerts_policies.json', method: 'GET' },
      { type: 'audit_log', title: 'New Relic Audit Events', description: 'NerdGraph audit events', path: 'https://api.newrelic.com/graphql', method: 'POST', params: { query: '{ actor { account(id: 0) { nrql(query: "SELECT * FROM NrAuditEvent SINCE 30 DAYS AGO LIMIT 200") { results } } } }' } },
      { type: 'incident_report', title: 'New Relic Incidents', description: 'Alert incidents and violations', path: '/alerts_incidents.json', method: 'GET' },
      { type: 'compliance_status', title: 'New Relic SLA Reports', description: 'Application SLA compliance data', path: '/applications.json', method: 'GET' },
    ],
  },
  {
    id: 'splunk', name: 'Splunk Observability', category: 'Monitoring',
    apiBaseUrl: 'https://api.{region}.signalfx.com/v2', apiDocsUrl: 'https://dev.splunk.com/observability/docs/',
    authMethods: ['api-key'], authHeader: 'X-SF-TOKEN', authPrefix: '',
    testEndpoint: '/organization',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Splunk Detectors', description: 'Alerting detector configurations', path: '/detector', method: 'GET' },
      { type: 'audit_log', title: 'Splunk Org Audit', description: 'Organization membership and access events', path: '/organization/member', method: 'GET' },
      { type: 'incident_report', title: 'Splunk Active Incidents', description: 'Currently active alert incidents', path: '/incident', method: 'GET' },
      { type: 'compliance_status', title: 'Splunk SLO Status', description: 'Service level objective compliance', path: '/slo', method: 'GET' },
    ],
  },
  {
    id: 'dynatrace', name: 'Dynatrace', category: 'Monitoring',
    apiBaseUrl: 'https://{instance}.live.dynatrace.com/api/v2', apiDocsUrl: 'https://docs.dynatrace.com/docs/dynatrace-api',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Api-Token',
    testEndpoint: '/apiTokens/lookup', rateLimitPerMinute: 50,
    evidenceEndpoints: [
      { type: 'configuration', title: 'Dynatrace Settings', description: 'Environment monitoring settings', path: '/settings/objects', method: 'GET', params: { schemaIds: 'builtin:alerting.profile', pageSize: 100 } },
      { type: 'audit_log', title: 'Dynatrace Audit Log', description: 'Environment audit log entries', path: '/auditlogs', method: 'GET' },
      { type: 'incident_report', title: 'Dynatrace Problems', description: 'Detected problems and root cause analysis', path: '/problems', method: 'GET' },
      { type: 'compliance_status', title: 'Dynatrace SLOs', description: 'SLO evaluation and compliance', path: '/slo', method: 'GET' },
    ],
  },
  {
    id: 'grafana-cloud', name: 'Grafana Cloud', category: 'Monitoring',
    apiBaseUrl: 'https://grafana.com/api', apiDocsUrl: 'https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/',
    authMethods: ['api-key', 'pat'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/instances',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Grafana Instances', description: 'Grafana Cloud stack configurations', path: '/instances', method: 'GET' },
      { type: 'audit_log', title: 'Grafana Access Policies', description: 'API access policies and token usage', path: '/v1/accesspolicies', method: 'GET' },
      { type: 'incident_report', title: 'Grafana Alert Rules', description: 'Alert rule definitions and firing state', path: 'https://{instance}.grafana.net/api/v1/provisioning/alert-rules', method: 'GET' },
      { type: 'compliance_status', title: 'Grafana Dashboards', description: 'Dashboard provisioning and configuration status', path: 'https://{instance}.grafana.net/api/search?type=dash-db', method: 'GET' },
    ],
  },
  {
    id: 'prometheus', name: 'Prometheus', category: 'Monitoring',
    apiBaseUrl: 'https://{instance}/api/v1', apiDocsUrl: 'https://prometheus.io/docs/prometheus/latest/querying/api/',
    authMethods: ['api-key', 'username-password'], testEndpoint: '/status/buildinfo',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Prometheus Targets', description: 'Active monitoring target configurations', path: '/targets', method: 'GET' },
      { type: 'audit_log', title: 'Prometheus TSDB Status', description: 'Time-series database status and retention', path: '/status/tsdb', method: 'GET' },
      { type: 'incident_report', title: 'Prometheus Active Alerts', description: 'Currently firing alerts', path: '/alerts', method: 'GET' },
      { type: 'compliance_status', title: 'Prometheus Alert Rules', description: 'Alerting and recording rule configurations', path: '/rules', method: 'GET' },
    ],
  },
  {
    id: 'pagerduty', name: 'PagerDuty', category: 'Monitoring',
    apiBaseUrl: 'https://api.pagerduty.com', apiDocsUrl: 'https://developer.pagerduty.com/api-reference/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Token token=',
    testEndpoint: '/users/me', rateLimitPerMinute: 900,
    evidenceEndpoints: [
      { type: 'configuration', title: 'PagerDuty Services', description: 'Service configurations and escalation policies', path: '/services', method: 'GET' },
      { type: 'audit_log', title: 'PagerDuty Audit Records', description: 'Account audit trail records', path: '/audit/records', method: 'GET' },
      { type: 'incident_report', title: 'PagerDuty Incidents', description: 'Incident history and response data', path: '/incidents', method: 'GET' },
      { type: 'compliance_status', title: 'PagerDuty Analytics', description: 'Incident response analytics and SLA metrics', path: '/analytics/metrics/incidents/all', method: 'POST', params: { filters: { created_at_start: '2024-01-01T00:00:00Z' } } },
    ],
  },
  {
    id: 'opsgenie', name: 'Opsgenie', category: 'Monitoring',
    apiBaseUrl: 'https://api.opsgenie.com/v2', apiDocsUrl: 'https://docs.opsgenie.com/docs/api-overview',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'GenieKey',
    testEndpoint: '/account',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Opsgenie Policies', description: 'Alert and notification policy configurations', path: '/policies/alert', method: 'GET' },
      { type: 'audit_log', title: 'Opsgenie Logs', description: 'Account activity logs', path: '/logs', method: 'GET' },
      { type: 'incident_report', title: 'Opsgenie Incidents', description: 'Incident records and timelines', path: '/incidents', method: 'GET' },
      { type: 'compliance_status', title: 'Opsgenie Teams', description: 'Team on-call and routing configurations', path: '/teams', method: 'GET' },
    ],
  },
  {
    id: 'victorops', name: 'VictorOps (Splunk On-Call)', category: 'Monitoring',
    apiBaseUrl: 'https://api.victorops.com/api-public/v1', apiDocsUrl: 'https://portal.victorops.com/public/api-docs.html',
    authMethods: ['api-key'], authHeader: 'X-VO-Api-Key', authPrefix: '',
    testEndpoint: '/user',
    evidenceEndpoints: [
      { type: 'configuration', title: 'VictorOps Routing Keys', description: 'Alert routing key configurations', path: '/org/routing-keys', method: 'GET' },
      { type: 'audit_log', title: 'VictorOps Teams', description: 'Team membership and access data', path: '/team', method: 'GET' },
      { type: 'incident_report', title: 'VictorOps Incidents', description: 'Incident timeline and resolution data', path: '/incidents', method: 'GET' },
      { type: 'compliance_status', title: 'VictorOps On-Call', description: 'On-call schedule and coverage compliance', path: '/oncall/current', method: 'GET' },
    ],
  },
  {
    id: 'sumo-logic', name: 'Sumo Logic', category: 'Monitoring',
    apiBaseUrl: 'https://api.{region}.sumologic.com/api/v1', apiDocsUrl: 'https://help.sumologic.com/docs/api/',
    authMethods: ['api-key-secret'], testEndpoint: '/account/contract',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Sumo Logic Collectors', description: 'Data collector configurations', path: '/collectors', method: 'GET' },
      { type: 'audit_log', title: 'Sumo Logic Audit Events', description: 'Account audit event index', path: '/search/jobs', method: 'POST', params: { query: '_index=sumologic_audit', from: '2024-01-01T00:00:00', to: '2025-01-01T00:00:00', timeZone: 'UTC' } },
      { type: 'incident_report', title: 'Sumo Logic Monitors', description: 'Active monitor alerts and status', path: '/monitors', method: 'GET' },
      { type: 'compliance_status', title: 'Sumo Logic Health Events', description: 'Account health and compliance status', path: '/healthEvents', method: 'GET' },
    ],
  },
  {
    id: 'elastic-elk', name: 'Elastic (ELK Stack)', category: 'Monitoring',
    apiBaseUrl: 'https://{instance}.es.{region}.aws.found.io', apiDocsUrl: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html',
    authMethods: ['api-key', 'username-password'], testEndpoint: '/',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Elastic Cluster Settings', description: 'Cluster configuration and settings', path: '/_cluster/settings?include_defaults=true', method: 'GET' },
      { type: 'audit_log', title: 'Elastic Security Log', description: 'Security audit log index', path: '/.security-audit-log*/_search?size=100', method: 'GET' },
      { type: 'incident_report', title: 'Elastic Alerts', description: 'Kibana alerting rule status and executions', path: '/_watcher/_query/watches', method: 'POST', params: { size: 100 } },
      { type: 'compliance_status', title: 'Elastic Index Lifecycle', description: 'Index lifecycle management policy compliance', path: '/_ilm/policy', method: 'GET' },
    ],
  },
  {
    id: 'honeycomb', name: 'Honeycomb', category: 'Monitoring',
    apiBaseUrl: 'https://api.honeycomb.io/1', apiDocsUrl: 'https://docs.honeycomb.io/api/',
    authMethods: ['api-key'], authHeader: 'X-Honeycomb-Team', authPrefix: '',
    testEndpoint: '/auth',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Honeycomb Datasets', description: 'Dataset configurations and columns', path: '/datasets', method: 'GET' },
      { type: 'audit_log', title: 'Honeycomb Team Members', description: 'Team membership and access data', path: 'https://api.honeycomb.io/1/team_members', method: 'GET' },
      { type: 'incident_report', title: 'Honeycomb Triggers', description: 'Alert trigger definitions and states', path: '/triggers/{account}', method: 'GET' },
      { type: 'compliance_status', title: 'Honeycomb SLOs', description: 'SLO definitions and burn rate status', path: '/slos/{account}', method: 'GET' },
    ],
  },
  {
    id: 'lightstep', name: 'Lightstep (ServiceNow Cloud Observability)', category: 'Monitoring',
    apiBaseUrl: 'https://api.lightstep.com/public/v0.2/{org}', apiDocsUrl: 'https://docs.lightstep.com/docs/api-reference',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/projects',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Lightstep Projects', description: 'Observability project configurations', path: '/projects', method: 'GET' },
      { type: 'audit_log', title: 'Lightstep Streams', description: 'Data stream and pipeline configurations', path: '/projects/{account}/streams', method: 'GET' },
      { type: 'incident_report', title: 'Lightstep Alerts', description: 'Alert conditions and notification settings', path: '/projects/{account}/alerting/conditions', method: 'GET' },
      { type: 'compliance_status', title: 'Lightstep SLO Status', description: 'Service level objective compliance status', path: '/projects/{account}/slos', method: 'GET' },
    ],
  },
  {
    id: 'appdynamics', name: 'AppDynamics', category: 'Monitoring',
    apiBaseUrl: 'https://{instance}.saas.appdynamics.com/controller/rest', apiDocsUrl: 'https://docs.appdynamics.com/appd/latest/en/extend-appdynamics/appdynamics-apis',
    authMethods: ['api-key', 'oauth'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/applications?output=JSON',
    evidenceEndpoints: [
      { type: 'configuration', title: 'AppDynamics Applications', description: 'Monitored application configurations', path: '/applications?output=JSON', method: 'GET' },
      { type: 'audit_log', title: 'AppDynamics Audit Log', description: 'Controller audit log entries', path: '/configuration?output=JSON', method: 'GET' },
      { type: 'incident_report', title: 'AppDynamics Health Violations', description: 'Health rule violation events', path: '/applications/{account}/problems/healthrule-violations?output=JSON&time-range-type=BEFORE_NOW&duration-in-mins=1440', method: 'GET' },
      { type: 'compliance_status', title: 'AppDynamics Health Rules', description: 'Health rule policy definitions', path: '/alerting/rest/v1/applications/{account}/health-rules', method: 'GET' },
    ],
  },
  {
    id: 'logicmonitor', name: 'LogicMonitor', category: 'Monitoring',
    apiBaseUrl: 'https://{instance}.logicmonitor.com/santaba/rest', apiDocsUrl: 'https://www.logicmonitor.com/support/rest-api-developers-guide',
    authMethods: ['api-key-secret'], testEndpoint: '/setting/companySetting',
    evidenceEndpoints: [
      { type: 'configuration', title: 'LogicMonitor Devices', description: 'Monitored device inventory and properties', path: '/device/devices', method: 'GET' },
      { type: 'audit_log', title: 'LogicMonitor Audit Logs', description: 'Account activity and change audit logs', path: '/setting/accesslogs', method: 'GET' },
      { type: 'incident_report', title: 'LogicMonitor Alerts', description: 'Active alert instances', path: '/alert/alerts', method: 'GET' },
      { type: 'compliance_status', title: 'LogicMonitor Alert Rules', description: 'Alert rule and escalation chain config', path: '/setting/alert/rules', method: 'GET' },
    ],
  },
  {
    id: 'site24x7', name: 'Site24x7', category: 'Monitoring',
    apiBaseUrl: 'https://www.site24x7.com/api', apiDocsUrl: 'https://www.site24x7.com/help/api/',
    authMethods: ['oauth'], authHeader: 'Authorization', authPrefix: 'Zoho-oauthtoken',
    testEndpoint: '/current_status',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Site24x7 Monitors', description: 'Monitor configurations and check intervals', path: '/monitors', method: 'GET' },
      { type: 'audit_log', title: 'Site24x7 Activity Log', description: 'User activity and change log', path: '/activity_log', method: 'GET' },
      { type: 'incident_report', title: 'Site24x7 Alerts', description: 'Current alert and outage data', path: '/alerts', method: 'GET' },
      { type: 'compliance_status', title: 'Site24x7 SLA Report', description: 'Uptime SLA compliance report', path: '/reports/sla_reports', method: 'GET' },
    ],
  },
  {
    id: 'catchpoint', name: 'Catchpoint', category: 'Monitoring',
    apiBaseUrl: 'https://io.catchpoint.com/ui/api/v1', apiDocsUrl: 'https://docs.catchpoint.com/api/',
    authMethods: ['api-key', 'oauth'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/nodes',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Catchpoint Tests', description: 'Synthetic monitoring test configurations', path: '/tests', method: 'GET' },
      { type: 'audit_log', title: 'Catchpoint Audit Trail', description: 'Account activity audit trail', path: '/auditTrail', method: 'GET' },
      { type: 'incident_report', title: 'Catchpoint Alerts', description: 'Active alerting events and notifications', path: '/alerts', method: 'GET' },
      { type: 'compliance_status', title: 'Catchpoint SLA Metrics', description: 'Performance and availability SLA compliance', path: '/performance/raw', method: 'GET' },
    ],
  },
  {
    id: 'thousandeyes', name: 'ThousandEyes', category: 'Monitoring',
    apiBaseUrl: 'https://api.thousandeyes.com/v7', apiDocsUrl: 'https://developer.thousandeyes.com/v7/',
    authMethods: ['api-key', 'oauth'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/status',
    evidenceEndpoints: [
      { type: 'configuration', title: 'ThousandEyes Tests', description: 'Network and application test configurations', path: '/tests', method: 'GET' },
      { type: 'audit_log', title: 'ThousandEyes Audit Events', description: 'Account audit event log', path: '/audit-user-events', method: 'GET' },
      { type: 'incident_report', title: 'ThousandEyes Alerts', description: 'Active alert details and rule triggers', path: '/alerts', method: 'GET' },
      { type: 'compliance_status', title: 'ThousandEyes Agents', description: 'Agent deployment and health status', path: '/agents', method: 'GET' },
    ],
  },
  {
    id: 'instana', name: 'Instana', category: 'Monitoring',
    apiBaseUrl: 'https://{instance}.instana.io/api', apiDocsUrl: 'https://instana.github.io/openapi/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'apiToken',
    testEndpoint: '/instana/health',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Instana Application Config', description: 'Application perspective configurations', path: '/application-monitoring/settings/application', method: 'GET' },
      { type: 'audit_log', title: 'Instana Audit Log', description: 'Configuration change audit log', path: '/settings/auditlog', method: 'GET' },
      { type: 'incident_report', title: 'Instana Events', description: 'Triggered events and incidents', path: '/events', method: 'GET', params: { windowSize: 86400000 } },
      { type: 'compliance_status', title: 'Instana Alert Config', description: 'Alert channel and rule configurations', path: '/events/settings/alert-configs', method: 'GET' },
    ],
  },
  {
    id: 'signalfx', name: 'SignalFx', category: 'Monitoring',
    apiBaseUrl: 'https://api.{region}.signalfx.com/v2', apiDocsUrl: 'https://dev.splunk.com/observability/reference/',
    authMethods: ['api-key'], authHeader: 'X-SF-TOKEN', authPrefix: '',
    testEndpoint: '/organization',
    evidenceEndpoints: [
      { type: 'configuration', title: 'SignalFx Detectors', description: 'Alerting detector configurations', path: '/detector', method: 'GET' },
      { type: 'audit_log', title: 'SignalFx Org Members', description: 'Organization member access records', path: '/organization/member', method: 'GET' },
      { type: 'incident_report', title: 'SignalFx Active Incidents', description: 'Currently firing alert incidents', path: '/incident', method: 'GET' },
      { type: 'compliance_status', title: 'SignalFx Dashboard Groups', description: 'Dashboard group configurations for observability', path: '/dashboardgroup', method: 'GET' },
    ],
  },
  {
    id: 'sentry', name: 'Sentry', category: 'Monitoring',
    apiBaseUrl: 'https://sentry.io/api/0', apiDocsUrl: 'https://docs.sentry.io/api/',
    authMethods: ['api-key', 'pat'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Sentry Projects', description: 'Project configurations and DSN settings', path: '/organizations/{org}/projects/', method: 'GET' },
      { type: 'audit_log', title: 'Sentry Audit Log', description: 'Organization audit log entries', path: '/organizations/{org}/audit-logs/', method: 'GET' },
      { type: 'incident_report', title: 'Sentry Issues', description: 'Unresolved error issues and events', path: '/organizations/{org}/issues/', method: 'GET' },
      { type: 'compliance_status', title: 'Sentry Alert Rules', description: 'Project alert rule configurations', path: '/organizations/{org}/combined-rules/', method: 'GET' },
    ],
  },
  {
    id: 'rollbar', name: 'Rollbar', category: 'Monitoring',
    apiBaseUrl: 'https://api.rollbar.com/api/1', apiDocsUrl: 'https://docs.rollbar.com/reference/',
    authMethods: ['api-key'], authHeader: 'X-Rollbar-Access-Token', authPrefix: '',
    testEndpoint: '/status/api',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Rollbar Projects', description: 'Project configurations and access tokens', path: '/projects', method: 'GET' },
      { type: 'audit_log', title: 'Rollbar Project Access Tokens', description: 'Project access token list for access review', path: '/project/{account}/access_tokens', method: 'GET' },
      { type: 'incident_report', title: 'Rollbar Items', description: 'Active error items and occurrences', path: '/items', method: 'GET' },
      { type: 'compliance_status', title: 'Rollbar Rate Limits', description: 'Rate limit settings and usage compliance', path: '/reports/top_active_items?hours=24', method: 'GET' },
    ],
  },
  {
    id: 'bugsnag', name: 'Bugsnag', category: 'Monitoring',
    apiBaseUrl: 'https://api.bugsnag.com', apiDocsUrl: 'https://bugsnagapiv2.docs.apiary.io/',
    authMethods: ['api-key', 'pat'], authHeader: 'Authorization', authPrefix: 'token',
    testEndpoint: '/user/organizations',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Bugsnag Projects', description: 'Organization project configurations', path: '/user/organizations/{org}/projects', method: 'GET' },
      { type: 'audit_log', title: 'Bugsnag Collaborators', description: 'Organization collaborator access list', path: '/organizations/{org}/collaborators', method: 'GET' },
      { type: 'incident_report', title: 'Bugsnag Errors', description: 'Tracked errors and stability scores', path: '/projects/{account}/errors', method: 'GET' },
      { type: 'compliance_status', title: 'Bugsnag Stability', description: 'Project stability score and release health', path: '/projects/{account}/stability_trend', method: 'GET' },
    ],
  },
  {
    id: 'airbrake', name: 'Airbrake', category: 'Monitoring',
    apiBaseUrl: 'https://api.airbrake.io/api/v4', apiDocsUrl: 'https://airbrake.io/docs/api/',
    authMethods: ['api-key'], testEndpoint: '/projects?key={token}',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Airbrake Projects', description: 'Monitored project configurations', path: '/projects?key={token}', method: 'GET' },
      { type: 'audit_log', title: 'Airbrake Deploys', description: 'Deployment tracking records', path: '/projects/{account}/deploys?key={token}', method: 'GET' },
      { type: 'incident_report', title: 'Airbrake Groups', description: 'Error groups and occurrences', path: '/projects/{account}/groups?key={token}', method: 'GET' },
      { type: 'compliance_status', title: 'Airbrake Project Stats', description: 'Error volume and trend data', path: '/projects/{account}/stats?key={token}', method: 'GET' },
    ],
  },
  {
    id: 'statuspage', name: 'Atlassian Statuspage', category: 'Monitoring',
    apiBaseUrl: 'https://api.statuspage.io/v1', apiDocsUrl: 'https://developer.statuspage.io/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'OAuth',
    testEndpoint: '/pages',
    evidenceEndpoints: [
      { type: 'configuration', title: 'Statuspage Pages', description: 'Status page configurations and components', path: '/pages', method: 'GET' },
      { type: 'audit_log', title: 'Statuspage Subscribers', description: 'Notification subscriber list', path: '/pages/{account}/subscribers', method: 'GET' },
      { type: 'incident_report', title: 'Statuspage Incidents', description: 'Incident history and updates', path: '/pages/{account}/incidents', method: 'GET' },
      { type: 'compliance_status', title: 'Statuspage Components', description: 'Component status and uptime metrics', path: '/pages/{account}/components', method: 'GET' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SIEM (10 providers)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'splunk-siem', name: 'Splunk Enterprise Security', category: 'SIEM',
    apiBaseUrl: 'https://{instance}:8089/services', apiDocsUrl: 'https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTprolog',
    authMethods: ['api-key', 'username-password'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/authentication/current-context?output_mode=json',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'Splunk SIEM Notable Events', description: 'Security notable event results from ES', path: '/search/jobs/export', method: 'POST', params: { search: 'search index=notable | head 200', output_mode: 'json' } },
      { type: 'security_finding', title: 'Splunk Correlation Searches', description: 'ES correlation search configurations', path: '/saved/searches?output_mode=json&search=action.notable=1', method: 'GET' },
      { type: 'audit_log', title: 'Splunk Audit Index', description: 'Internal audit trail events', path: '/search/jobs/export', method: 'POST', params: { search: 'search index=_audit | head 200', output_mode: 'json' } },
      { type: 'configuration', title: 'Splunk ES Configuration', description: 'Enterprise Security app configurations', path: '/configs/conf-es_ui_settings?output_mode=json', method: 'GET' },
    ],
  },
  {
    id: 'ibm-qradar', name: 'IBM QRadar', category: 'SIEM',
    apiBaseUrl: 'https://{instance}/api', apiDocsUrl: 'https://www.ibm.com/docs/en/qradar-common?topic=api-restful-overview',
    authMethods: ['api-key'], authHeader: 'SEC', authPrefix: '',
    testEndpoint: '/system/about',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'QRadar Offenses', description: 'Active and recent security offenses', path: '/siem/offenses', method: 'GET' },
      { type: 'security_finding', title: 'QRadar Rules', description: 'Custom rule engine configurations', path: '/analytics/rules', method: 'GET' },
      { type: 'audit_log', title: 'QRadar Audit Log', description: 'System audit log events', path: '/system/authorization/password_policies', method: 'GET' },
      { type: 'configuration', title: 'QRadar Log Sources', description: 'Configured log source types and status', path: '/config/event_sources/log_source_management/log_sources', method: 'GET' },
    ],
  },
  {
    id: 'microsoft-sentinel', name: 'Microsoft Sentinel', category: 'SIEM',
    apiBaseUrl: 'https://management.azure.com/subscriptions/{account}/resourceGroups/{tenant}/providers/Microsoft.OperationalInsights/workspaces/{instance}/providers/Microsoft.SecurityInsights', apiDocsUrl: 'https://learn.microsoft.com/en-us/rest/api/securityinsights/',
    authMethods: ['oauth', 'service-account'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/incidents?api-version=2023-11-01',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'Sentinel Incidents', description: 'Security incidents and correlated alerts', path: '/incidents?api-version=2023-11-01', method: 'GET' },
      { type: 'security_finding', title: 'Sentinel Alert Rules', description: 'Analytics rule configurations', path: '/alertRules?api-version=2023-11-01', method: 'GET' },
      { type: 'audit_log', title: 'Sentinel Data Connectors', description: 'Connected data source configurations', path: '/dataConnectors?api-version=2023-11-01', method: 'GET' },
      { type: 'configuration', title: 'Sentinel Automation Rules', description: 'Automated response rule configurations', path: '/automationRules?api-version=2023-11-01', method: 'GET' },
    ],
  },
  {
    id: 'google-chronicle', name: 'Google Chronicle', category: 'SIEM',
    apiBaseUrl: 'https://{instance}-chronicle.googleapis.com/v1alpha', apiDocsUrl: 'https://cloud.google.com/chronicle/docs/reference/rest',
    authMethods: ['service-account', 'oauth'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/projects/{account}/locations/{region}/instances/{instance}',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'Chronicle Alerts', description: 'Curated detection alerts', path: '/projects/{account}/locations/{region}/instances/{instance}/legacy:legacySearchAlerts', method: 'POST', params: { timeRange: { startTime: '2024-01-01T00:00:00Z' }, pageSize: 100 } },
      { type: 'security_finding', title: 'Chronicle Detection Rules', description: 'YARA-L detection rule configurations', path: '/projects/{account}/locations/{region}/instances/{instance}/rules', method: 'GET' },
      { type: 'audit_log', title: 'Chronicle Data Feeds', description: 'Configured data ingestion feeds', path: '/projects/{account}/locations/{region}/instances/{instance}/feeds', method: 'GET' },
      { type: 'configuration', title: 'Chronicle Reference Lists', description: 'Reference list configurations for detections', path: '/projects/{account}/locations/{region}/instances/{instance}/referenceLists', method: 'GET' },
    ],
  },
  {
    id: 'exabeam', name: 'Exabeam', category: 'SIEM',
    apiBaseUrl: 'https://{instance}.exabeam.com/api', apiDocsUrl: 'https://docs.exabeam.com/en/cloud-delivered-advanced-analytics/all/api/',
    authMethods: ['api-key', 'oauth'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/auth/check',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'Exabeam Notable Events', description: 'Notable security events from Advanced Analytics', path: '/entities/notableEvents', method: 'POST', params: { startTime: '2024-01-01T00:00:00Z', pageSize: 100 } },
      { type: 'security_finding', title: 'Exabeam Threat Indicators', description: 'Triggered threat indicators and risk scores', path: '/entities/threatIndicators', method: 'GET' },
      { type: 'audit_log', title: 'Exabeam Audit Logs', description: 'System and user audit logs', path: '/audit/logs', method: 'GET' },
      { type: 'configuration', title: 'Exabeam Data Sources', description: 'Connected data source configurations', path: '/datasources', method: 'GET' },
    ],
  },
  {
    id: 'logrhythm', name: 'LogRhythm', category: 'SIEM',
    apiBaseUrl: 'https://{instance}/lr-admin-api', apiDocsUrl: 'https://docs.logrhythm.com/lrsiem/en/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/actions',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'LogRhythm Alarms', description: 'SIEM alarm events and risk scores', path: '/alarms', method: 'GET' },
      { type: 'security_finding', title: 'LogRhythm AI Engine Rules', description: 'AI Engine rule configurations', path: '/ai-engine-rules', method: 'GET' },
      { type: 'audit_log', title: 'LogRhythm Log Sources', description: 'Log source collection status', path: '/logsources', method: 'GET' },
      { type: 'configuration', title: 'LogRhythm Entities', description: 'Entity and network configuration', path: '/entities', method: 'GET' },
    ],
  },
  {
    id: 'securonix', name: 'Securonix', category: 'SIEM',
    apiBaseUrl: 'https://{instance}.securonix.net/Snypr/ws', apiDocsUrl: 'https://documentation.securonix.com/onlinedoc/Content/Cloud/Content/REST-API/',
    authMethods: ['api-key', 'username-password'], testEndpoint: '/token/validate',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'Securonix Violations', description: 'Security policy violation events', path: '/violations/get', method: 'GET', params: { from: '01/01/2024 00:00:00', to: '12/31/2024 23:59:59' } },
      { type: 'security_finding', title: 'Securonix Threats', description: 'Identified threat indicators and cases', path: '/incident/get', method: 'GET' },
      { type: 'audit_log', title: 'Securonix Activity', description: 'User and system activity records', path: '/activity/get', method: 'GET' },
      { type: 'configuration', title: 'Securonix Policies', description: 'Security policy configurations', path: '/policy/get', method: 'GET' },
    ],
  },
  {
    id: 'devo', name: 'Devo', category: 'SIEM',
    apiBaseUrl: 'https://apiv2-{region}.devo.com', apiDocsUrl: 'https://docs.devo.com/space/latest/95128275/Devo+API',
    authMethods: ['api-key', 'oauth'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/system/ping',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'Devo Security Events', description: 'Queried security event data', path: '/search/query', method: 'POST', params: { query: 'from siem.logtrust.alert.info select *', from: '2024-01-01T00:00:00Z', to: 'now()', limit: 100 } },
      { type: 'security_finding', title: 'Devo Active Alerts', description: 'Active alert definitions and triggers', path: '/alerts/list', method: 'GET' },
      { type: 'audit_log', title: 'Devo Audit Trail', description: 'Platform audit trail events', path: '/search/query', method: 'POST', params: { query: 'from siem.logtrust.audit.global select *', from: '2024-01-01T00:00:00Z', to: 'now()', limit: 100 } },
      { type: 'configuration', title: 'Devo Domain Config', description: 'Domain and relay configuration', path: '/domain/config', method: 'GET' },
    ],
  },
  {
    id: 'swimlane', name: 'Swimlane', category: 'SIEM',
    apiBaseUrl: 'https://{instance}.swimlane.com/api', apiDocsUrl: 'https://swimlane.com/knowledge-center/docs/developer-guide/',
    authMethods: ['api-key', 'pat'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/user',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'Swimlane Records', description: 'Security incident and event records', path: '/app/{account}/record', method: 'GET' },
      { type: 'security_finding', title: 'Swimlane Workspaces', description: 'SOAR workspace and playbook configurations', path: '/workspaces', method: 'GET' },
      { type: 'audit_log', title: 'Swimlane Audit Trail', description: 'Platform audit trail events', path: '/audit', method: 'GET' },
      { type: 'configuration', title: 'Swimlane Applications', description: 'SOAR application configurations', path: '/app', method: 'GET' },
    ],
  },
  {
    id: 'phantom-splunk-soar', name: 'Splunk SOAR (Phantom)', category: 'SIEM',
    apiBaseUrl: 'https://{instance}/rest', apiDocsUrl: 'https://docs.splunk.com/Documentation/SOARonprem/latest/PlatformAPI/RESTReference',
    authMethods: ['api-key'], authHeader: 'ph-auth-token', authPrefix: '',
    testEndpoint: '/version',
    evidenceEndpoints: [
      { type: 'siem_event', title: 'SOAR Container Events', description: 'Security event containers and artifacts', path: '/container?page_size=100', method: 'GET' },
      { type: 'security_finding', title: 'SOAR Playbooks', description: 'Automated playbook definitions', path: '/playbook?page_size=100', method: 'GET' },
      { type: 'audit_log', title: 'SOAR Audit Log', description: 'Platform audit trail entries', path: '/audit?page_size=100&sort=time&order=desc', method: 'GET' },
      { type: 'configuration', title: 'SOAR Asset Config', description: 'Integration asset configurations', path: '/asset?page_size=100', method: 'GET' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MDM (15 providers)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'jamf', name: 'Jamf Pro', category: 'MDM',
    apiBaseUrl: 'https://{instance}.jamfcloud.com/api', apiDocsUrl: 'https://developer.jamf.com/jamf-pro/reference/',
    authMethods: ['api-key', 'oauth'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/v1/auth',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Jamf Computers', description: 'Managed computer device inventory', path: '/v1/computers-inventory', method: 'GET' },
      { type: 'endpoint_status', title: 'Jamf Mobile Devices', description: 'Managed mobile device status', path: 'https://{instance}.jamfcloud.com/JSSResource/mobiledevices', method: 'GET' },
      { type: 'policy_config', title: 'Jamf Policies', description: 'Device management policy configurations', path: 'https://{instance}.jamfcloud.com/JSSResource/policies', method: 'GET' },
      { type: 'encryption_status', title: 'Jamf FileVault', description: 'FileVault disk encryption status across devices', path: '/v1/computers-inventory?section=DISK_ENCRYPTION', method: 'GET' },
    ],
  },
  {
    id: 'kandji', name: 'Kandji', category: 'MDM',
    apiBaseUrl: 'https://{subdomain}.api.kandji.io/api/v1', apiDocsUrl: 'https://api-docs.kandji.io/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/devices',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Kandji Devices', description: 'Managed device inventory and details', path: '/devices', method: 'GET' },
      { type: 'endpoint_status', title: 'Kandji Device Status', description: 'Device compliance and status details', path: '/devices/{account}/status', method: 'GET' },
      { type: 'policy_config', title: 'Kandji Blueprints', description: 'Device blueprint configurations', path: '/blueprints', method: 'GET' },
      { type: 'encryption_status', title: 'Kandji FileVault', description: 'FileVault encryption key escrow status', path: '/devices/{account}/filevaultkey', method: 'GET' },
    ],
  },
  {
    id: 'mosyle', name: 'Mosyle', category: 'MDM',
    apiBaseUrl: 'https://managerapi.mosyle.com/v2', apiDocsUrl: 'https://business.mosyle.com/api',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/listdevices',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Mosyle Devices', description: 'Managed device inventory', path: '/listdevices', method: 'POST', params: { os: 'mac', page: 0 } },
      { type: 'endpoint_status', title: 'Mosyle Device Status', description: 'Device compliance and management status', path: '/listdevices', method: 'POST', params: { os: 'ios', page: 0 } },
      { type: 'policy_config', title: 'Mosyle Profiles', description: 'Configuration profile assignments', path: '/listprofiles', method: 'POST', params: { os: 'mac' } },
      { type: 'encryption_status', title: 'Mosyle Encryption', description: 'Device encryption status report', path: '/listdevices', method: 'POST', params: { os: 'mac', options: { encryption: true } } },
    ],
  },
  {
    id: 'addigy', name: 'Addigy', category: 'MDM',
    apiBaseUrl: 'https://prod.addigy.com/api', apiDocsUrl: 'https://addigy.freshdesk.com/support/solutions/articles/8000088930',
    authMethods: ['api-key-secret'], testEndpoint: '/policies',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Addigy Devices', description: 'Managed device inventory and details', path: '/devices', method: 'GET' },
      { type: 'endpoint_status', title: 'Addigy Online Devices', description: 'Device online/offline status', path: '/devices/online', method: 'GET' },
      { type: 'policy_config', title: 'Addigy Policies', description: 'Device policy configurations', path: '/policies', method: 'GET' },
      { type: 'encryption_status', title: 'Addigy Encryption Status', description: 'FileVault encryption compliance', path: '/devices', method: 'GET', params: { factName: 'filevault_status' } },
    ],
  },
  {
    id: 'hexnode', name: 'Hexnode UEM', category: 'MDM',
    apiBaseUrl: 'https://{instance}.hexnodemdm.com/api/v1', apiDocsUrl: 'https://www.hexnode.com/mobile-device-management/developers/api/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: '',
    testEndpoint: '/devices/',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Hexnode Devices', description: 'Managed device inventory', path: '/devices/', method: 'GET' },
      { type: 'endpoint_status', title: 'Hexnode Device Groups', description: 'Device groups and compliance status', path: '/devicegroups/', method: 'GET' },
      { type: 'policy_config', title: 'Hexnode Policies', description: 'Device policy configurations', path: '/policies/', method: 'GET' },
      { type: 'encryption_status', title: 'Hexnode Device Details', description: 'Device security and encryption details', path: '/devices/{account}/', method: 'GET' },
    ],
  },
  {
    id: 'microsoft-intune', name: 'Microsoft Intune', category: 'MDM',
    apiBaseUrl: 'https://graph.microsoft.com/v1.0', apiDocsUrl: 'https://learn.microsoft.com/en-us/graph/api/resources/intune-graph-overview',
    authMethods: ['oauth', 'service-account'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/deviceManagement',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Intune Managed Devices', description: 'All managed device inventory', path: '/deviceManagement/managedDevices', method: 'GET' },
      { type: 'endpoint_status', title: 'Intune Device Compliance', description: 'Device compliance evaluation status', path: '/deviceManagement/deviceCompliancePolicyDeviceStateSummary', method: 'GET' },
      { type: 'policy_config', title: 'Intune Compliance Policies', description: 'Device compliance policy configurations', path: '/deviceManagement/deviceCompliancePolicies', method: 'GET' },
      { type: 'encryption_status', title: 'Intune Encryption Report', description: 'Device encryption readiness and status', path: '/deviceManagement/managedDeviceEncryptionStates', method: 'GET' },
    ],
  },
  {
    id: 'vmware-workspace-one', name: 'VMware Workspace ONE', category: 'MDM',
    apiBaseUrl: 'https://{instance}.awmdm.com/API', apiDocsUrl: 'https://docs.vmware.com/en/VMware-Workspace-ONE-UEM/services/UEM_ConsoleBasics/GUID-BF20C949-5065-4DCF-889D-1E0151016B5A.html',
    authMethods: ['api-key', 'username-password'], authHeader: 'aw-tenant-code', authPrefix: '',
    testEndpoint: '/system/info',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'WS1 Device Search', description: 'Enrolled device inventory', path: '/mdm/devices/search', method: 'GET' },
      { type: 'endpoint_status', title: 'WS1 Device Compliance', description: 'Device compliance summary', path: '/mdm/devices/compliance', method: 'GET' },
      { type: 'policy_config', title: 'WS1 Profiles', description: 'Device profile configurations', path: '/mdm/profiles/search', method: 'GET' },
      { type: 'encryption_status', title: 'WS1 Encryption Status', description: 'BitLocker and FileVault encryption status', path: '/mdm/devices/security', method: 'GET' },
    ],
  },
  {
    id: 'soti', name: 'SOTI MobiControl', category: 'MDM',
    apiBaseUrl: 'https://{instance}/MobiControl/api', apiDocsUrl: 'https://www.soti.net/mc/help/v15.4/en/console/api/',
    authMethods: ['oauth', 'username-password'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/devices?take=1',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'SOTI Devices', description: 'Managed device inventory', path: '/devices', method: 'GET' },
      { type: 'endpoint_status', title: 'SOTI Device Groups', description: 'Device group structure and status', path: '/devicegroups', method: 'GET' },
      { type: 'policy_config', title: 'SOTI Profiles', description: 'Device configuration profiles', path: '/profiles', method: 'GET' },
      { type: 'encryption_status', title: 'SOTI Compliance Rules', description: 'Device compliance and encryption rules', path: '/policies', method: 'GET' },
    ],
  },
  {
    id: 'manageengine-mdm', name: 'ManageEngine MDM Plus', category: 'MDM',
    apiBaseUrl: 'https://{instance}.manageengine.com/api/v1/mdm', apiDocsUrl: 'https://www.manageengine.com/mobile-device-management/api/',
    authMethods: ['api-key', 'oauth'], authHeader: 'Authorization', authPrefix: 'Zoho-oauthtoken',
    testEndpoint: '/devices',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'ME MDM Devices', description: 'Enrolled device inventory', path: '/devices', method: 'GET' },
      { type: 'endpoint_status', title: 'ME MDM Compliance', description: 'Device compliance status summary', path: '/compliance/status', method: 'GET' },
      { type: 'policy_config', title: 'ME MDM Profiles', description: 'Configuration profile assignments', path: '/profiles', method: 'GET' },
      { type: 'encryption_status', title: 'ME MDM Security', description: 'Device security and encryption details', path: '/devices/security', method: 'GET' },
    ],
  },
  {
    id: 'ivanti-mdm', name: 'Ivanti Neurons for MDM', category: 'MDM',
    apiBaseUrl: 'https://{instance}.ivanti.com/api/v2', apiDocsUrl: 'https://help.ivanti.com/mi/help/en_us/ma/3.3/api/',
    authMethods: ['api-key', 'username-password'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/devices?limit=1',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Ivanti Devices', description: 'Managed device inventory', path: '/devices', method: 'GET' },
      { type: 'endpoint_status', title: 'Ivanti Compliance Status', description: 'Device compliance evaluation results', path: '/compliance/device_statuses', method: 'GET' },
      { type: 'policy_config', title: 'Ivanti Policies', description: 'Configuration and security policies', path: '/policies', method: 'GET' },
      { type: 'encryption_status', title: 'Ivanti Security', description: 'Encryption and security posture details', path: '/devices/security', method: 'GET' },
    ],
  },
  {
    id: 'tanium', name: 'Tanium', category: 'MDM',
    apiBaseUrl: 'https://{instance}/api/v2', apiDocsUrl: 'https://docs.tanium.com/platform_api/platform_api/',
    authMethods: ['api-key'], authHeader: 'session', authPrefix: '',
    testEndpoint: '/session/current',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Tanium Endpoints', description: 'Managed endpoint inventory', path: '/computers', method: 'GET' },
      { type: 'endpoint_status', title: 'Tanium Comply Results', description: 'Tanium Comply compliance scan results', path: '/plugin/products/comply/v1/results', method: 'GET' },
      { type: 'policy_config', title: 'Tanium Enforce Policies', description: 'Tanium Enforce policy configurations', path: '/plugin/products/enforce/v1/policies', method: 'GET' },
      { type: 'encryption_status', title: 'Tanium Encryption Status', description: 'Endpoint encryption compliance from Tanium Comply', path: '/plugin/products/comply/v1/results?filter=encryption', method: 'GET' },
    ],
  },
  {
    id: 'automox', name: 'Automox', category: 'MDM',
    apiBaseUrl: 'https://console.automox.com/api', apiDocsUrl: 'https://developer.automox.com/openapi/axconsole/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/orgs',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Automox Devices', description: 'Managed device inventory and OS details', path: '/servers', method: 'GET' },
      { type: 'endpoint_status', title: 'Automox Device Status', description: 'Patch compliance and agent status', path: '/servers', method: 'GET', params: { patchStatus: 'needsPatch' } },
      { type: 'policy_config', title: 'Automox Policies', description: 'Patching and worklet policy configurations', path: '/policies', method: 'GET' },
      { type: 'encryption_status', title: 'Automox Software Inventory', description: 'Software inventory including encryption tools', path: '/servers/{account}/packages', method: 'GET' },
    ],
  },
  {
    id: 'fleetdm', name: 'Fleet', category: 'MDM',
    apiBaseUrl: 'https://{instance}/api/v1/fleet', apiDocsUrl: 'https://fleetdm.com/docs/rest-api/rest-api',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/me',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Fleet Hosts', description: 'Enrolled host device inventory', path: '/hosts', method: 'GET' },
      { type: 'endpoint_status', title: 'Fleet Host Summary', description: 'Host online/offline and OS status summary', path: '/host_summary', method: 'GET' },
      { type: 'policy_config', title: 'Fleet Policies', description: 'Compliance policy definitions and pass rates', path: '/policies', method: 'GET' },
      { type: 'encryption_status', title: 'Fleet Disk Encryption', description: 'Disk encryption status across enrolled hosts', path: '/hosts?disk_encryption_enabled=true', method: 'GET' },
    ],
  },
  {
    id: 'osquery', name: 'osquery', category: 'MDM',
    apiBaseUrl: 'https://{instance}/api/v1', apiDocsUrl: 'https://osquery.readthedocs.io/en/stable/',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/nodes',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'osquery Nodes', description: 'Enrolled osquery node inventory', path: '/nodes', method: 'GET' },
      { type: 'endpoint_status', title: 'osquery Node Status', description: 'Node check-in and health status', path: '/nodes/status', method: 'GET' },
      { type: 'policy_config', title: 'osquery Packs', description: 'Query pack configurations and schedules', path: '/packs', method: 'GET' },
      { type: 'encryption_status', title: 'osquery Disk Encryption', description: 'Disk encryption query results from endpoints', path: '/queries/results', method: 'POST', params: { query: 'SELECT * FROM disk_encryption;' } },
    ],
  },
  {
    id: 'kolide', name: 'Kolide', category: 'MDM',
    apiBaseUrl: 'https://k2.kolide.com/api/v0', apiDocsUrl: 'https://www.kolide.com/docs/developers/api',
    authMethods: ['api-key'], authHeader: 'Authorization', authPrefix: 'Bearer',
    testEndpoint: '/auth/whoami',
    evidenceEndpoints: [
      { type: 'device_inventory', title: 'Kolide Devices', description: 'Enrolled device inventory', path: '/devices', method: 'GET' },
      { type: 'endpoint_status', title: 'Kolide Device Failures', description: 'Failing device compliance checks', path: '/issues', method: 'GET' },
      { type: 'policy_config', title: 'Kolide Checks', description: 'Device compliance check configurations', path: '/checks', method: 'GET' },
      { type: 'encryption_status', title: 'Kolide Encryption Checks', description: 'Disk encryption posture checks', path: '/checks?tag=encryption', method: 'GET' },
    ],
  },
];

export default createProviders(descriptors);
