-- =====================================================================
-- 20260604_enforce_rls — BREAKING tenant-isolation lockdown
-- =====================================================================
-- Finding A1/A2 remediation, step 5 (the breaking half).
--
-- This migration issues FORCE ROW LEVEL SECURITY on every tenant table so
-- that the org_isolation policies (defined in
-- prisma/migrations/rls_policies_all_tables.sql) apply EVEN TO THE TABLE
-- OWNER. Without FORCE, the table owner / a BYPASSRLS role silently
-- bypasses every policy and tenant isolation is non-functional.
--
-- !!! DO NOT APPLY IN ISOLATION !!!
-- This migration MUST be deployed together with BOTH of:
--   (a) the application code that injects org context per request via the
--       GUC "app.current_org" (server/src/config/orgContext.ts +
--       server/src/config/database.ts); and
--   (b) a DATABASE_URL pointed at a LEAST-PRIVILEGE application role that
--       does NOT have BYPASSRLS and does NOT own these tables.
--
-- Applying FORCE while the app still connects as a BYPASSRLS/owner role is
-- harmless (policies remain bypassed). Applying FORCE while the app
-- connects as a non-bypass role WITHOUT (a) in place would deny all rows.
-- Follow RLS_DEPLOY_RUNBOOK.md for the correct ordering.
--
-- Prerequisite: rls_policies_all_tables.sql must already be applied so the
-- accessor function and per-table policies exist. FORCE has no effect unless
-- each table already has RLS ENABLEd plus an org_isolation policy; that
-- prerequisite file is the one that issues `ENABLE ROW LEVEL SECURITY` and
-- `CREATE POLICY` for every table FORCE'd below (one ENABLE + one policy per
-- table). If you change the table set here, keep it a subset of the tables
-- ENABLEd there, or the extra FORCE statements will be inert.
-- =====================================================================

ALTER TABLE "AISuggestion" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AISystem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AITransparencyNotice" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AccessReview" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AgenticAction" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ApiKey" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Asset" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditEngagement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditFinding" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditorProfile" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AzurePolicyCompliance" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AzureResource" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AzureSecurityAlert" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AzureSecurityFinding" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AzureSyncJob" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AzureUser" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BCPPlan" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BCRProgram" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BrandingConfig" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BreachIncident" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BreachTemplate" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessAssociateAgreement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessProcess" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CEProduct" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CICDGatePolicy" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CICDGateResult" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Certification" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ChangeImpact" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ChatConversation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CompensatingControlWorksheet" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ComplianceCost" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ComplianceDeadline" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ComplianceDebt" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ComplianceException" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ComplianceFramework" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ComplianceGoal" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CompliancePolicy" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ComplianceTrajectory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ConsentPreference" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ConsentRecord" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ContinuousMonitor" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ControlEffectivenessRecord" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ControlLoop" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ControlLoopHistory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ControlTest" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CustomDashboard" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CustomReport" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CustomRole" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DMAComplianceReport" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DMAGatekeeper" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DMAObligationTracking" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DORAICTIncident" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DORAICTRiskAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DORAInformationRegister" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DORAResilienceTest" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DORAThirdPartyProvider" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DPOProfile" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DSAAdRepository" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DSAContentModeration" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DSAIllegalContentReport" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DSANonPersonalizedFeed" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DSAPlatform" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DSARRequest" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DSARiskAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DSATransparencyReport" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DashboardWidget" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DataDeletionRequest" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DataMap" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DataProtectionImpactAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DeviceTrust" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DigitalProductPassport" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ESGMetric" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EUAIActRiskAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EUAIActSystem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EUAIActTransparencyReport" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EdgeComplianceCheck" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EvidenceAnalysis" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EvidenceAttestation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EvidenceCollectionRule" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FeatureSubscription" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FederatedSwarmAggregation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FederatedSwarmPeer" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FileUpload" FORCE ROW LEVEL SECURITY;
ALTER TABLE "GNNModel" FORCE ROW LEVEL SECURITY;
ALTER TABLE "GRCWorkflow" FORCE ROW LEVEL SECURITY;
ALTER TABLE "GapAnalysis" FORCE ROW LEVEL SECURITY;
ALTER TABLE "GovernanceBody" FORCE ROW LEVEL SECURITY;
ALTER TABLE "GrcIncident" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HIPAABreachRiskAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ISO27001Assessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ISO27001CorrectiveAction" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ISO27001RiskScenario" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ISO27001SoA" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Integration" FORCE ROW LEVEL SECURITY;
ALTER TABLE "IoTDevice" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Issue" FORCE ROW LEVEL SECURITY;
ALTER TABLE "JITAccessRequest" FORCE ROW LEVEL SECURITY;
ALTER TABLE "JITPrivacyNotice" FORCE ROW LEVEL SECURITY;
ALTER TABLE "JITSession" FORCE ROW LEVEL SECURITY;
ALTER TABLE "KeyRotationPolicy" FORCE ROW LEVEL SECURITY;
ALTER TABLE "KeyUsage" FORCE ROW LEVEL SECURITY;
ALTER TABLE "KnowledgeGraphEntity" FORCE ROW LEVEL SECURITY;
ALTER TABLE "KnowledgeGraphRelationship" FORCE ROW LEVEL SECURITY;
ALTER TABLE "LDAPRoleMapping" FORCE ROW LEVEL SECURITY;
ALTER TABLE "LifecycleAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "LivenessChallenge" FORCE ROW LEVEL SECURITY;
ALTER TABLE "MDMPolicy" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ManagedDevice" FORCE ROW LEVEL SECURITY;
ALTER TABLE "MaterialityAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "MaturityAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "MetricsHistory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NPSInvitation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NPSResponse" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NetworkSegment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NeuroSymbolicReasoning" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NistCsfActionItem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NistCsfGapAnalysis" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NistCsfProfile" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NistCsfSubcategoryAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Notification" FORCE ROW LEVEL SECURITY;
ALTER TABLE "OnboardingChecklist" FORCE ROW LEVEL SECURITY;
ALTER TABLE "OnboardingEvent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "OnboardingProgress" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PCIAOC" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PCIEvidence" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PCIROC" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PCIRequirement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PCIScope" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PHIAccessGrant" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PHIRecord" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Personnel" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PhishingTraining" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Policy" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PolicyTemplate" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PrivacyBudgetLedger" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ProcessMap" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ProcessingActivityRecord" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ProcessingRestriction" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ProductDecommission" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ProductLifecycle" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ProductRecall" FORCE ROW LEVEL SECURITY;
ALTER TABLE "QSAFinding" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Questionnaire" FORCE ROW LEVEL SECURITY;
ALTER TABLE "QuestionnaireTemplate" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RFPResponse" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RedTeamResult" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RegulationModuleData" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RegulatoryChange" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RegulatoryChangeImpact" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RegulatoryContact" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RegulatoryFeed" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ReportTemplate" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RetentionPolicy" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RiskAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RiskItem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RiskPrediction" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RuleInference" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SBOMEntry" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SBOMRepository" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SCAFFOLDControlVariate" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SCCTemplate" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SCIMConfiguration" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SOC2CUEC" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SOC2Control" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SOC2Engagement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SOC2EvidenceSample" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SOC2Exception" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SOC2ManagementAssertion" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SOXAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SOXControl" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SSOConfiguration" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SearchIndex" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SecurityTraining" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SecurityTrainingRecord" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SimulationResult" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SimulationScenario" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SoDRule" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SoDViolation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SubscriptionHistory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SurveillancePlan" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SwarmAgent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SwarmInsight" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SwarmTask" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SwarmTaskAlert" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SwarmTaskMetric" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TIAAssessment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TranscriptionResult" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TrustCertificate" FORCE ROW LEVEL SECURITY;
ALTER TABLE "UsageTracking" FORCE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
ALTER TABLE "UserSession" FORCE ROW LEVEL SECURITY;
ALTER TABLE "UserSigningKey" FORCE ROW LEVEL SECURITY;
ALTER TABLE "VRCollaborativeSession" FORCE ROW LEVEL SECURITY;
ALTER TABLE "VRTrainingScenario" FORCE ROW LEVEL SECURITY;
ALTER TABLE "VRTrainingSession" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Vendor" FORCE ROW LEVEL SECURITY;
ALTER TABLE "VendorMonitoringCheck" FORCE ROW LEVEL SECURITY;
ALTER TABLE "WebRTCSession" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Webhook" FORCE ROW LEVEL SECURITY;
ALTER TABLE "WebhookEvent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ZeroTrustPolicy" FORCE ROW LEVEL SECURITY;
