/**
 * EU Regulations Control Templates Service
 * 
 * Provides comprehensive control templates for:
 * - EU AI Act (Regulation 2024/1689)
 * - Digital Markets Act (DMA) (Regulation 2022/1925)
 * - Digital Services Act (DSA) (Regulation 2022/2065)
 * 
 * Automatically creates controls when EU frameworks are added to an organization.
 */

// FrameworkType enum values - matching frontend types.ts
enum FrameworkType {
  SOC2 = 'SOC 2 Type II',
  GDPR = 'GDPR',
  HIPAA = 'HIPAA',
  ISO27001 = 'ISO 27001',
  PCI_DSS = 'PCI DSS',
  CCPA = 'CCPA',
  NIST = 'NIST 800-53',
  EU_AI_ACT = 'EU AI Act',
  DMA = 'Digital Markets Act (DMA)',
  DSA = 'Digital Services Act (DSA)'
}

export interface ControlTemplate {
  name: string;
  description: string;
  category: string;
  evidenceRequired: boolean;
  status: string;
  mappedControls?: any;
}

export class EURegulationsControlTemplatesService {
  /**
   * Get control templates for EU AI Act
   */
  getEUAIActControls(): ControlTemplate[] {
    return [
      // Risk Classification Controls
      {
        name: 'AI-ACT-001: Risk Classification System',
        description: 'Implement and maintain a risk-based classification system that categorizes AI systems as Unacceptable, High, Limited, or Minimal risk according to Article 6 of the EU AI Act.',
        category: 'Risk Classification',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-002: Prohibited Practices Detection',
        description: 'Establish automated detection and blocking mechanisms for prohibited AI practices including cognitive manipulation, social scoring, and unauthorized biometric identification (Article 5).',
        category: 'Prohibited Practices',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-003: High-Risk AI System Registration',
        description: 'Register all high-risk AI systems in the EU database before placing them on the market or putting them into service (Article 51).',
        category: 'Registration',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-004: Risk Management System',
        description: 'Establish, document, and maintain a risk management system for high-risk AI systems that identifies, analyzes, evaluates, and addresses risks (Article 9).',
        category: 'Risk Management',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-005: Data Governance',
        description: 'Implement data governance and management practices for training, validation, and testing datasets used in high-risk AI systems (Article 10).',
        category: 'Data Governance',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-006: Technical Documentation',
        description: 'Create and maintain technical documentation for high-risk AI systems that demonstrates compliance with the AI Act requirements (Article 11).',
        category: 'Documentation',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-007: Record Keeping',
        description: 'Maintain logs automatically generated by high-risk AI systems to enable traceability and post-market monitoring (Article 12).',
        category: 'Record Keeping',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-008: Transparency and User Information',
        description: 'Provide users with clear and adequate information about high-risk AI systems, including capabilities, limitations, and expected performance (Article 13).',
        category: 'Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-009: Human Oversight',
        description: 'Implement human oversight measures to minimize risks and enable human intervention in high-risk AI systems (Article 14).',
        category: 'Human Oversight',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-010: Accuracy, Robustness, and Cybersecurity',
        description: 'Ensure high-risk AI systems achieve appropriate levels of accuracy, robustness, and cybersecurity throughout their lifecycle (Article 15).',
        category: 'System Quality',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-011: Quality Management System',
        description: 'Establish a quality management system for high-risk AI systems that covers design, development, production, and post-market monitoring (Article 17).',
        category: 'Quality Management',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-012: Conformity Assessment',
        description: 'Conduct conformity assessment procedures for high-risk AI systems before placing them on the market (Article 19).',
        category: 'Conformity Assessment',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-013: Generative AI Content Labeling',
        description: 'Label AI-generated content (text, images, audio, video) to inform users that the content was generated by AI (Article 50).',
        category: 'Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-014: Copyright Data Summary',
        description: 'Publish summaries of copyrighted data used for training general-purpose AI models (Article 53).',
        category: 'Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-015: Illegal Content Prevention',
        description: 'Design and train general-purpose AI models to prevent generation of illegal content (Article 53).',
        category: 'Content Safety',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-016: High-Impact General-Purpose AI Model Evaluation',
        description: 'Conduct thorough evaluations and report serious incidents to the European Commission for high-impact general-purpose AI models (Article 55).',
        category: 'Evaluation',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-017: Post-Market Monitoring',
        description: 'Establish post-market monitoring systems to continuously evaluate high-risk AI systems in real-world conditions (Article 72).',
        category: 'Monitoring',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-018: Serious Incident Reporting',
        description: 'Report serious incidents involving high-risk AI systems to the relevant national authority without undue delay (Article 73).',
        category: 'Incident Management',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-019: Corrective Actions',
        description: 'Take immediate corrective actions when high-risk AI systems present a risk to health, safety, or fundamental rights (Article 74).',
        category: 'Corrective Actions',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'AI-ACT-020: Transparency Report Submission',
        description: 'Generate and submit transparency reports to the European Commission for generative AI systems (Article 53).',
        category: 'Reporting',
        evidenceRequired: true,
        status: 'Pending',
      },
    ];
  }

  /**
   * Get control templates for Digital Markets Act (DMA)
   */
  getDMAControls(): ControlTemplate[] {
    return [
      // Gatekeeper Designation
      {
        name: 'DMA-001: Gatekeeper Designation Assessment',
        description: 'Assess whether the organization meets gatekeeper criteria: €75B annual revenue or €750B market cap, 45M+ monthly active users in EU, and operation of core platform services (Article 3).',
        category: 'Gatekeeper Designation',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-002: Core Platform Services Identification',
        description: 'Identify and document all core platform services (CPS) operated by the organization, including online search engines, social networking, video sharing, operating systems, cloud computing, advertising, and web browsers (Article 2).',
        category: 'Core Platform Services',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Data Portability and Interoperability
      {
        name: 'DMA-003: Data Portability for End Users',
        description: 'Enable end users to easily port their data to other services, including continuous and real-time data portability (Article 6(9)).',
        category: 'Data Portability',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-004: Data Portability for Business Users',
        description: 'Enable business users to easily port their data, including advertising performance data, to other services (Article 6(9)).',
        category: 'Data Portability',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-005: Interoperability with Complementary Services',
        description: 'Ensure interoperability with complementary services and hardware, including third-party services and software applications (Article 6(7)).',
        category: 'Interoperability',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-006: Interoperability with Hardware',
        description: 'Ensure interoperability with hardware, including third-party hardware and software applications (Article 6(7)).',
        category: 'Interoperability',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Fair Access
      {
        name: 'DMA-007: Fair Access to Platform Services',
        description: 'Provide fair, reasonable, and non-discriminatory access to platform services for business users (Article 6(12)).',
        category: 'Fair Access',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-008: Data Access for Business Users',
        description: 'Provide business users with access to data generated through their use of the platform, including advertising performance data (Article 6(9)).',
        category: 'Data Access',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Prohibited Practices
      {
        name: 'DMA-009: Prohibition of Self-Preferencing',
        description: 'Prohibit self-preferencing of own services and products over third-party services and products in ranking and related indexing and crawling (Article 6(5)).',
        category: 'Prohibited Practices',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-010: Prohibition of Bundling',
        description: 'Prohibit bundling of services without explicit user consent and clear information about the bundle (Article 5(2)).',
        category: 'Prohibited Practices',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-011: Prohibition of Tying',
        description: 'Prohibit tying of services that are not necessary for the functioning of the core platform service (Article 5(3)).',
        category: 'Prohibited Practices',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-012: Prohibition of Most-Favored-Nation Clauses',
        description: 'Prohibit most-favored-nation clauses in contracts with business users that restrict their ability to offer different prices or conditions on other platforms (Article 5(4)).',
        category: 'Prohibited Practices',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-013: Prohibition of Restrictive Contracts',
        description: 'Prohibit restrictive contractual terms that prevent business users from promoting offers and entering into contracts with end users outside the gatekeeper platform (Article 5(5)).',
        category: 'Prohibited Practices',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Transparency
      {
        name: 'DMA-014: Transparency in Ranking Parameters',
        description: 'Provide transparency on ranking parameters and criteria used for ranking, including any differential treatment of own services (Article 6(5)).',
        category: 'Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-015: Transparency in Advertising Services',
        description: 'Provide transparency on advertising services, including pricing, targeting criteria, and performance metrics (Article 6(8)).',
        category: 'Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-016: Transparency in Measurement Tools',
        description: 'Provide transparency on measurement tools and methodologies used for advertising and other services (Article 6(8)).',
        category: 'Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Compliance and Reporting
      {
        name: 'DMA-017: Compliance Program',
        description: 'Establish and maintain a compliance program to ensure adherence to DMA obligations, including regular audits and assessments (Article 8).',
        category: 'Compliance',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-018: Compliance Reporting',
        description: 'Submit annual compliance reports to the European Commission detailing measures taken to comply with DMA obligations (Article 11).',
        category: 'Reporting',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-019: Audit Trail Maintenance',
        description: 'Maintain comprehensive audit trails of all actions taken to comply with DMA obligations, including data portability and interoperability measures (Article 8).',
        category: 'Audit Trail',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DMA-020: Obligation Tracking System',
        description: 'Implement a system to track compliance status of each DMA obligation, including evidence collection and verification (Article 8).',
        category: 'Obligation Tracking',
        evidenceRequired: true,
        status: 'Pending',
      },
    ];
  }

  /**
   * Get control templates for Digital Services Act (DSA)
   */
  getDSAControls(): ControlTemplate[] {
    return [
      // Platform Classification
      {
        name: 'DSA-001: Platform Type Classification',
        description: 'Classify the platform type (online platform, VLOP, VLOSE, intermediary service) and maintain accurate classification based on user count and service type (Article 2).',
        category: 'Platform Classification',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-002: VLOP/VLOSE Designation',
        description: 'Monitor monthly active users and automatically designate as Very Large Online Platform (VLOP) or Very Large Online Search Engine (VLOSE) if exceeding 45M users in EU (Article 33).',
        category: 'VLOP/VLOSE Designation',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Content Moderation
      {
        name: 'DSA-003: Content Moderation Policy',
        description: 'Establish and publish clear terms and conditions for content moderation, including rules, procedures, and measures for enforcement (Article 14).',
        category: 'Content Moderation',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-004: Content Moderation Transparency',
        description: 'Provide transparency on content moderation decisions, including reasons for removal, suspension, or restriction of content (Article 15).',
        category: 'Content Moderation',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-005: Automated Content Detection',
        description: 'Implement and maintain automated content detection systems with appropriate safeguards and human oversight (Article 14).',
        category: 'Content Moderation',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-006: Appeal Process for Content Moderation',
        description: 'Provide users with an effective and timely internal complaint-handling system for content moderation decisions (Article 20).',
        category: 'User Rights',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-007: Out-of-Court Dispute Settlement',
        description: 'Enable users to seek out-of-court dispute settlement for content moderation decisions through certified bodies (Article 21).',
        category: 'User Rights',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Illegal Content
      {
        name: 'DSA-008: Illegal Content Reporting Mechanism',
        description: 'Provide users with an easy-to-use mechanism to report illegal content, goods, or services (Article 16).',
        category: 'Illegal Content',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-009: Trusted Flagger Program',
        description: 'Establish and maintain a trusted flagger program with priority processing for reports from certified trusted flaggers (Article 22).',
        category: 'Illegal Content',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-010: Illegal Content Response Time',
        description: 'Respond to illegal content reports within reasonable timeframes (typically 24-48 hours) and take appropriate action (Article 16).',
        category: 'Illegal Content',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-011: Illegal Content Action Tracking',
        description: 'Maintain records of all illegal content reports, actions taken, and response times for transparency and accountability (Article 16).',
        category: 'Illegal Content',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Protection of Minors
      {
        name: 'DSA-012: Age-Appropriate Design',
        description: 'Design services to minimize risks to minors, including age-inappropriate content like gambling or pornography (Article 28).',
        category: 'Protection of Minors',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-013: Prohibition of Targeted Ads to Minors',
        description: 'Prohibit showing targeted advertisements to minors based on their personal data (Article 28).',
        category: 'Protection of Minors',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-014: Age Verification Measures',
        description: 'Implement appropriate age verification measures to prevent minors from accessing age-inappropriate content (Article 28).',
        category: 'Protection of Minors',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Ad Transparency (VLOP Requirement)
      {
        name: 'DSA-015: Ad Repository (VLOP)',
        description: 'Maintain a publicly accessible repository of all advertisements displayed on the platform, including advertiser information and targeting criteria (Article 39).',
        category: 'Ad Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-016: Ad Labeling',
        description: 'Clearly label all advertisements and provide information about who placed them and why users are seeing them (Article 26).',
        category: 'Ad Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-017: Political Ad Identification',
        description: 'Identify and label political advertisements in the ad repository with clear indicators (Article 39).',
        category: 'Ad Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-018: Sensitive Data Ad Targeting Prohibition',
        description: 'Prohibit showing ads based on sensitive personal data such as sexual orientation, religion, or race (Article 26).',
        category: 'Ad Transparency',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Dark Patterns
      {
        name: 'DSA-019: Dark Patterns Prohibition',
        description: 'Prohibit deceptive design tactics, such as aggressive pop-ups, confusing consent buttons, or misleading interfaces that manipulate user choices (Article 25).',
        category: 'Dark Patterns',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-020: User Interface Design Review',
        description: 'Conduct regular reviews of user interfaces to identify and eliminate dark patterns that may manipulate user behavior (Article 25).',
        category: 'Dark Patterns',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Transparency Reporting (VLOP/VLOSE Requirement)
      {
        name: 'DSA-021: Transparency Report Generation (VLOP/VLOSE)',
        description: 'Generate and publish annual transparency reports covering content moderation, user reports, trusted flagger activities, and automated detection (Article 42).',
        category: 'Transparency Reporting',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-022: Transparency Report Submission',
        description: 'Submit transparency reports to the European Commission and make them publicly available (Article 42).',
        category: 'Transparency Reporting',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-023: Content Moderation Statistics',
        description: 'Track and report statistics on content moderation actions, including removals, suspensions, restrictions, and appeals (Article 42).',
        category: 'Transparency Reporting',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-024: User Report Statistics',
        description: 'Track and report statistics on user-reported content, including response times and actions taken (Article 42).',
        category: 'Transparency Reporting',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-025: Automated Detection Statistics',
        description: 'Track and report statistics on automated content detection, including false positive rates and accuracy metrics (Article 42).',
        category: 'Transparency Reporting',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Verified Sellers (Marketplaces)
      {
        name: 'DSA-026: Seller Verification (Marketplaces)',
        description: 'Verify and display contact details of sellers on online marketplaces to enable direct communication with consumers (Article 22).',
        category: 'Marketplace Requirements',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-027: Product Traceability (Marketplaces)',
        description: 'Make reasonable efforts to perform random checks on products sold on the marketplace or adopt new technologies for product traceability (Article 22).',
        category: 'Marketplace Requirements',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Non-Personalized Feeds (VLOP)
      {
        name: 'DSA-028: Non-Personalized Feed Option (VLOP)',
        description: 'Provide users with the option to opt for non-personalized feeds that are not based on algorithmic recommendations (Article 27).',
        category: 'User Choice',
        evidenceRequired: true,
        status: 'Pending',
      },
      // Compliance
      {
        name: 'DSA-029: Compliance Program',
        description: 'Establish and maintain a compliance program to ensure adherence to DSA obligations, including regular audits and assessments (Article 12).',
        category: 'Compliance',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-030: Risk Assessment (VLOP/VLOSE)',
        description: 'Conduct and document risk assessments for systemic risks, including illegal content, fundamental rights, public security, and protection of minors (Article 34).',
        category: 'Risk Assessment',
        evidenceRequired: true,
        status: 'Pending',
      },
      {
        name: 'DSA-031: Mitigation Measures (VLOP/VLOSE)',
        description: 'Implement appropriate mitigation measures to address identified systemic risks, including content moderation, user safety, and algorithmic transparency (Article 35).',
        category: 'Risk Mitigation',
        evidenceRequired: true,
        status: 'Pending',
      },
    ];
  }

  /**
   * Get all control templates for a specific framework
   */
  getControlsForFramework(frameworkName: string): ControlTemplate[] {
    switch (frameworkName) {
      case FrameworkType.EU_AI_ACT:
        return this.getEUAIActControls();
      case FrameworkType.DMA:
        return this.getDMAControls();
      case FrameworkType.DSA:
        return this.getDSAControls();
      default:
        return [];
    }
  }

  /**
   * Get total control count for a framework
   */
  getControlCount(frameworkName: string): number {
    return this.getControlsForFramework(frameworkName).length;
  }
}

export default new EURegulationsControlTemplatesService();

